import {systemThemes,isSystemThemeId,systemThemeStorageKey} from './system-theme';
import {uiScaleOptions,defaultUiScale,uiScaleStorageKey,isUiScaleId} from './ui-scale';
export const appearanceKey='labnest.appearance';
export const appearanceDefaults={schemaVersion:1,mode:'system',colorSchemeId:'moon-dai',uiFontId:'system-sans',dataFontId:'mono',uiScaleId:defaultUiScale,iconPackId:'lab-soft'} as const;
export type AppearancePreferences={schemaVersion:1;mode:'light'|'dark'|'system';colorSchemeId:string;uiFontId:'system-sans'|'system-serif';dataFontId:'system'|'mono';uiScaleId:string;iconPackId:'classic-line'|'lab-soft'};
export const preferenceIds={mode:['light','dark','system'],colorSchemeId:systemThemes.map(t=>t.id),uiFontId:['system-sans','system-serif'],dataFontId:['system','mono'],uiScaleId:uiScaleOptions.map(s=>s.id),iconPackId:['classic-line','lab-soft']};
/** Unknown IDs fall back for display only; original bytes remain available to recover. */
export function parseAppearance(raw:string|null,legacyTheme:string|null,legacyScale:string|null,existingUser:boolean):{value:AppearancePreferences;preserve:boolean}{
 const base:AppearancePreferences={...appearanceDefaults,colorSchemeId:isSystemThemeId(legacyTheme)?legacyTheme:'moon-dai',uiScaleId:isUiScaleId(legacyScale)?legacyScale:defaultUiScale,iconPackId:existingUser?'classic-line':'lab-soft'};
 if(raw===null)return {value:base,preserve:false};
 try {const data=JSON.parse(raw);if(data?.schemaVersion!==1)return {value:base,preserve:true};let preserve=false;for(const [key,ids] of Object.entries(preferenceIds)){if((ids as readonly string[]).includes(data[key]))(base as unknown as Record<string,unknown>)[key]=data[key];else preserve=true;}if(Object.keys(data).some(key=>key!=='schemaVersion'&&!Object.prototype.hasOwnProperty.call(preferenceIds,key)))preserve=true;return {value:base,preserve};}catch{return {value:base,preserve:true};}
}
export function applyAppearance(value:AppearancePreferences,root:HTMLElement,systemDark:boolean){root.dataset.labnestTheme=value.colorSchemeId;root.dataset.labnestUiScale=value.uiScaleId;root.dataset.labnestMode=value.mode==='system'?(systemDark?'dark':'light'):value.mode;root.dataset.labnestUiFont=value.uiFontId;root.dataset.labnestDataFont=value.dataFontId;root.dataset.labnestIconPack=value.iconPackId;}
export function appearanceBootstrap(){return `(()=>{try{const raw=localStorage.getItem(${JSON.stringify(appearanceKey)}),legacy=localStorage.getItem(${JSON.stringify(systemThemeStorageKey)}),scale=localStorage.getItem(${JSON.stringify(uiScaleStorageKey)});const defaults=${JSON.stringify(appearanceDefaults)},ids=${JSON.stringify(preferenceIds)};let data={};try{data=JSON.parse(raw||'{}')}catch{};const v={...defaults};if(ids.colorSchemeId.includes(legacy))v.colorSchemeId=legacy;if(ids.uiScaleId.includes(scale))v.uiScaleId=scale;if(legacy!==null||scale!==null||localStorage.getItem('labnest.calculators.v1')!==null)v.iconPackId='classic-line';if(data.schemaVersion===1)for(const key of Object.keys(ids))if(ids[key].includes(data[key]))v[key]=data[key];const r=document.documentElement;r.dataset.labnestTheme=v.colorSchemeId;r.dataset.labnestUiScale=v.uiScaleId;r.dataset.labnestMode=v.mode==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):v.mode;r.dataset.labnestUiFont=v.uiFontId;r.dataset.labnestDataFont=v.dataFontId;r.dataset.labnestIconPack=v.iconPackId;}catch{}})()`;}
