import { createProtocolRunPreview, createProtocolVersionFromParameterChange } from "./protocol";
import { gcPercent, sequenceLength, translateDna } from "./sequence";
import type {
  AIProviderRecord,
  ActivityItem,
  EntityRecord,
  Entry,
  Experiment,
  InventoryItem,
  InventoryTransaction,
  Project,
  ProcurementInquiry,
  ProcurementQuoteLine,
  Protocol,
  ProtocolVersionData,
  ProposedAction,
  PurchaseRequest,
  ReferenceConnectorRecord,
  RelevantItem,
  ResultRecord,
  SampleLifecycleEvent,
  SampleProfile,
  SequenceRecord,
} from "./types";

const now = "2026-07-07T21:30:00+08:00";

export const projects: Project[] = [
  {
    id: "proj-gfp",
    name: "GFP transfection optimization",
    description:
      "A personal/small-lab workflow for tuning HEK293T transient transfection while keeping protocol versions, inventory, and results connected.",
    status: "active",
    tags: ["HEK293T", "GFP", "optimization"],
  },
  {
    id: "proj-methods",
    name: "Methods notebook",
    description: "Reusable protocol templates and method notes that can be versioned before experiment use.",
    status: "active",
    tags: ["templates", "methods"],
  },
];

export const cellTransfectionVersion: ProtocolVersionData = {
  id: "pv-cell-transfection-v1",
  protocolId: "protocol-cell-transfection",
  revision: 1,
  displayVersion: "0.1",
  reviewStage: "reviewed",
  recordStatus: "reviewed",
  changeSummary: "Initial reviewed protocol template.",
  title: "Cell transfection v0.1",
  purpose: "Run a small-scale transient transfection while preserving reviewable consumption proposals.",
  background:
    "Protocol calculations are deterministic helpers. They create pending actions only; the user still confirms material source and quantity.",
  scope: "Personal and small-lab wet-lab documentation; not a regulated GxP workflow.",
  notes: "Adjust seeding density and DNA mass only after recording deviation notes.",
  parameters: [
    { name: "well_count", type: "number", default: 2, required: true },
    { name: "cell_line", type: "entity", entity_type: "cell_line", required: true },
    { name: "plasmid", type: "entity", entity_type: "plasmid", required: true },
  ],
  materials: [
    { name: "Lipofectamine 3000", unit: "uL", role: "transfection reagent" },
    { name: "Complete DMEM", unit: "mL", role: "culture medium" },
    { name: "Opti-MEM", unit: "mL", role: "complex formation" },
  ],
  equipment: [
    { name: "CO2 incubator", notes: "37 C, 5% CO2" },
    { name: "Fluorescence microscope", notes: "GFP channel" },
  ],
  steps: [
    {
      order: 1,
      title: "Seed cells",
      description: "Seed {{cell_line}} into {{well_count}} wells at the planned density.",
      requires_confirmation: true,
      allows_deviation: true,
    },
    {
      order: 2,
      title: "Prepare DNA-lipid complexes",
      description: "Prepare complexes for {{plasmid}} using scaled reagent volumes.",
      requires_confirmation: true,
      allows_deviation: true,
    },
    {
      order: 3,
      title: "Add complexes and incubate",
      description: "Add complexes dropwise, return plate to incubator, and record any toxicity.",
      requires_confirmation: true,
      allows_deviation: true,
    },
    {
      order: 4,
      title: "Capture expression readout",
      description: "Image representative wells and record GFP expression at the selected timepoint.",
      requires_confirmation: false,
      allows_deviation: true,
    },
  ],
  consumptionRules: [
    {
      material_name: "Lipofectamine 3000",
      formula: "well_count * 4",
      unit: "uL",
      requires_inventory_selection: true,
    },
    {
      material_name: "Complete DMEM",
      formula: "well_count * 2",
      unit: "mL",
      requires_inventory_selection: true,
    },
  ],
  resultTemplates: [
    {
      result_type: "fluorescence_expression",
      fields: [
        { name: "timepoint", type: "number", unit: "h", required: true },
        {
          name: "gfp_expression",
          type: "select",
          options: ["positive", "weak", "negative"],
          required: true,
        },
        { name: "transfection_efficiency", type: "number", unit: "%", required: false },
        { name: "microscopy_images", type: "attachment[]", required: false },
      ],
    },
  ],
  createdAt: "2026-07-07T09:00:00+08:00",
};

export const cellTransfectionVersionV2 = createProtocolVersionFromParameterChange({
  previousVersion: cellTransfectionVersion,
  parameterChanges: [{ name: "well_count", updates: { default: 3 } }],
  changeSummary: "Confirmed local parameter update: default pilot scale changed from 2 wells to 3 wells.",
  createdAt: "2026-07-08T09:20:00+08:00",
});

const pcrVersion: ProtocolVersionData = {
  ...cellTransfectionVersion,
  id: "pv-pcr-v1",
  protocolId: "protocol-pcr",
  title: "PCR v0.1",
  reviewStage: "ready_for_review",
  recordStatus: "submitted",
  changeSummary: "Submitted method template awaiting review.",
  purpose: "Endpoint PCR with explicit reaction count and annealing temperature.",
  parameters: [
    { name: "reaction_count", type: "number", default: 8, required: true },
    { name: "annealing_temp", type: "number", unit: "C", default: 60, required: true },
  ],
  materials: [
    { name: "2x PCR Master Mix", unit: "uL", role: "enzyme mix" },
    { name: "Forward/reverse primers", unit: "uM", role: "amplification" },
  ],
  steps: [
    {
      order: 1,
      title: "Prepare master mix",
      description: "Prepare master mix for {{reaction_count}} reactions.",
      requires_confirmation: true,
      allows_deviation: true,
    },
    {
      order: 2,
      title: "Run thermocycler",
      description: "Run PCR with annealing at {{annealing_temp}} C.",
      requires_confirmation: true,
      allows_deviation: true,
    },
  ],
  consumptionRules: [],
  resultTemplates: [],
};

export const protocols: Protocol[] = [
  {
    id: "protocol-cell-transfection",
    title: "Cell transfection",
    description: "Plate-based transfection with parameterized reagent scaling and result templates.",
    availability: "active",
    scope: "general",
    recordStatus: "recorded",
    tags: ["cell-culture", "transfection"],
    currentVersion: cellTransfectionVersionV2,
    versions: [cellTransfectionVersion, cellTransfectionVersionV2],
    updatedAt: now,
  },
  {
    id: "protocol-pcr",
    title: "PCR",
    description: "Endpoint PCR template with reaction-count parameters and gel readout notes.",
    availability: "active",
    scope: "general",
    recordStatus: "submitted",
    tags: ["molecular", "PCR"],
    currentVersion: pcrVersion,
    versions: [pcrVersion],
    updatedAt: "2026-07-06T15:15:00+08:00",
  },
  {
    id: "protocol-qpcr",
    title: "qPCR",
    description: "Ct capture template with replicate-aware result forms.",
    availability: "draft",
    scope: "general",
    recordStatus: "draft",
    tags: ["qPCR", "expression"],
    currentVersion: {
      ...pcrVersion,
      id: "pv-qpcr-v1",
      protocolId: "protocol-qpcr",
      title: "qPCR v0.1",
      reviewStage: "draft",
      recordStatus: "draft",
      changeSummary: "Initial draft protocol template.",
    },
    versions: [],
    updatedAt: "2026-07-05T11:10:00+08:00",
  },
  {
    id: "protocol-western",
    title: "Western blot",
    description: "Protein blot workflow with antibody and loading metadata.",
    availability: "draft",
    scope: "general",
    recordStatus: "draft",
    tags: ["protein", "WB"],
    currentVersion: {
      ...pcrVersion,
      id: "pv-western-v1",
      protocolId: "protocol-western",
      title: "Western blot v0.1",
      reviewStage: "draft",
      recordStatus: "draft",
      changeSummary: "Initial draft protocol template.",
    },
    versions: [],
    updatedAt: "2026-07-04T10:00:00+08:00",
  },
];

const runPreview = createProtocolRunPreview(cellTransfectionVersion, {
  well_count: 2,
  cell_line: "HEK293T",
  plasmid: "pLenti-GFP",
});

export const relevantItems: RelevantItem[] = [
  {
    id: "rel-protocol",
    type: "protocol_version",
    title: "Cell transfection v1",
    relation: "derived_from",
    createdBy: "system",
  },
  {
    id: "rel-cell",
    type: "entity",
    title: "HEK293T",
    relation: "uses",
    createdBy: "user",
  },
  {
    id: "rel-plasmid",
    type: "entity",
    title: "pLenti-GFP",
    relation: "uses",
    createdBy: "user",
  },
  {
    id: "rel-result",
    type: "result",
    title: "24 h GFP expression placeholder",
    relation: "generated_result",
    createdBy: "system",
  },
];

export const entries: Entry[] = [
  {
    id: "entry-density",
    title: "Adjusted seeding density before GFP transfection",
    body:
      "Cells looked slightly over-confluent in two wells. Reduce seeding density by 15% and document whether expression improves at 24 h.",
    occurredAt: "2026-07-07T20:40:00+08:00",
    projectId: "proj-gfp",
    projectName: "GFP transfection optimization",
    tags: ["observation", "transfection"],
    sourceType: "text",
    recordStatus: "recorded",
    moodStatus: "needs follow-up",
    attachmentCount: 1,
    relevantItems: relevantItems.slice(1, 3),
    pendingActionCount: 1,
  },
  {
    id: "entry-media",
    title: "Medium bottle near expiry",
    body:
      "Complete DMEM expires soon. Use for pilot only if morphology remains normal; otherwise prepare a replacement purchase request.",
    occurredAt: "2026-07-07T09:15:00+08:00",
    projectId: "proj-gfp",
    projectName: "GFP transfection optimization",
    tags: ["inventory", "expiry"],
    sourceType: "text",
    recordStatus: "recorded",
    attachmentCount: 0,
    relevantItems: [
      {
        id: "rel-dmem",
        type: "inventory_item",
        title: "Complete DMEM",
        relation: "references",
        createdBy: "user",
      },
    ],
    pendingActionCount: 0,
  },
];

export const experiments: Experiment[] = [
  {
    id: "exp-transfection-pilot",
    title: "GFP transfection pilot - 2 well scale",
    projectId: "proj-gfp",
    projectName: "GFP transfection optimization",
    status: "running",
    recordStatus: "recorded",
    date: "2026-07-07T14:00:00+08:00",
    purpose:
      "Pilot a 2-well HEK293T transfection and confirm that protocol-derived consumption remains reviewable.",
    primaryProtocolVersionId: "pv-cell-transfection-v1",
    protocolRunId: runPreview.protocolRunId,
    tags: ["demo", "protocol-run"],
    steps: runPreview.steps.map((step, index) => ({
      ...step,
      completed: index === 0,
      completedAt: index === 0 ? "2026-07-07T14:08:00+08:00" : undefined,
    })),
  },
  {
    id: "exp-pcr-check",
    title: "GAPDH primer gradient check",
    projectId: "proj-methods",
    projectName: "Methods notebook",
    status: "planned",
    recordStatus: "draft",
    date: "2026-07-08T10:00:00+08:00",
    purpose: "Check primer performance across annealing temperatures before qPCR use.",
    primaryProtocolVersionId: "pv-pcr-v1",
    tags: ["PCR", "primer"],
    steps: [],
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv-lipo",
    name: "Lipofectamine 3000",
    containerType: "tube",
    lotNumber: "LIPO-DEMO-24",
    vendor: "Thermo Fisher",
    catalogNumber: "L3000008",
    currentQuantity: 120,
    unit: "uL",
    location: "4C fridge A / reagent box",
    expiryDate: "2026-10-01",
    storageCondition: "4 C, protect from light",
    status: "active",
    lowThreshold: 30,
  },
  {
    id: "inv-dmem",
    name: "Complete DMEM",
    containerType: "bottle",
    lotNumber: "DMEM-DEMO-07",
    vendor: "Gibco",
    currentQuantity: 38,
    unit: "mL",
    location: "4C fridge A",
    expiryDate: "2026-07-25",
    storageCondition: "4 C",
    status: "active",
    lowThreshold: 25,
  },
  {
    id: "inv-hek-wcb-a01",
    entityId: "entity-hek-wcb",
    name: "HEK293T working cell bank A01",
    containerType: "cryovial",
    barcode: "LN-SMP-HEK-WCB-A01",
    aliquotCode: "HEK-WCB-A01",
    lotNumber: "WCB-DEMO-01",
    currentQuantity: 0,
    unit: "vial",
    concentration: "1.2e6 cells/vial",
    location: "-80C freezer A / rack 1 / box HEK-WCB",
    positionCode: "A01",
    expiryDate: "2027-01-15",
    storageCondition: "-80 C",
    freezeThawCount: 1,
    status: "archived",
    notes: "Thawed to seed the transfection pilot; retained as an audit record.",
  },
  {
    id: "inv-hek-wcb-a02",
    entityId: "entity-hek-wcb",
    name: "HEK293T working cell bank A02",
    containerType: "cryovial",
    barcode: "LN-SMP-HEK-WCB-A02",
    aliquotCode: "HEK-WCB-A02",
    lotNumber: "WCB-DEMO-01",
    currentQuantity: 1,
    unit: "vial",
    concentration: "1.2e6 cells/vial",
    location: "-80C freezer A / rack 1 / box HEK-WCB",
    positionCode: "A02",
    expiryDate: "2027-01-15",
    storageCondition: "-80 C",
    freezeThawCount: 0,
    status: "active",
    notes: "Reserve aliquot from the same working cell bank preparation.",
  },
  {
    id: "inv-agarose",
    name: "Agarose",
    containerType: "bottle",
    lotNumber: "AGR-DEMO-01",
    vendor: "Bio-Rad",
    currentQuantity: 9,
    unit: "g",
    location: "Room shelf 2",
    expiryDate: "2027-02-01",
    status: "active",
    lowThreshold: 20,
  },
];

export const inventoryTransactions: InventoryTransaction[] = [
  {
    id: "txn-lipo-receive",
    inventoryItemId: "inv-lipo",
    type: "receive",
    quantityChange: 120,
    unit: "uL",
    toLocation: "4C fridge A / reagent box",
    notes: "Initial demo receive transaction.",
    createdAt: "2026-07-06T16:00:00+08:00",
  },
  {
    id: "txn-dmem-receive",
    inventoryItemId: "inv-dmem",
    type: "receive",
    quantityChange: 38,
    unit: "mL",
    toLocation: "4C fridge A",
    notes: "Initial demo receive transaction.",
    createdAt: "2026-07-06T16:05:00+08:00",
  },
  {
    id: "txn-hek-a01-aliquot",
    inventoryItemId: "inv-hek-wcb-a01",
    type: "aliquot",
    quantityChange: 1,
    unit: "vial",
    toLocation: "-80C freezer A / rack 1 / box HEK-WCB / A01",
    notes: "Created cryovial aliquot from the working cell bank preparation.",
    createdAt: "2026-07-06T17:00:00+08:00",
  },
  {
    id: "txn-hek-a02-aliquot",
    inventoryItemId: "inv-hek-wcb-a02",
    type: "aliquot",
    quantityChange: 1,
    unit: "vial",
    toLocation: "-80C freezer A / rack 1 / box HEK-WCB / A02",
    notes: "Created reserve cryovial aliquot from the same preparation.",
    createdAt: "2026-07-06T17:02:00+08:00",
  },
  {
    id: "txn-hek-a01-thaw",
    inventoryItemId: "inv-hek-wcb-a01",
    type: "thaw",
    quantityChange: -1,
    unit: "vial",
    fromLocation: "-80C freezer A / rack 1 / box HEK-WCB / A01",
    experimentId: "exp-transfection-pilot",
    notes: "Thawed for the GFP transfection pilot; vial-level stock closed.",
    createdAt: "2026-07-07T13:20:00+08:00",
  },
];

export const proposedActions: ProposedAction[] = [
  ...runPreview.proposedActions.map((action, index) => ({
    ...action,
    id: index === 0 ? "pa-lipo" : "pa-dmem",
    affectedItem: index === 0 ? "Lipofectamine 3000" : "Complete DMEM",
    payload: {
      ...action.payload,
      inventory_item_id: index === 0 ? "inv-lipo" : "inv-dmem",
    },
  })),
  {
    id: "pa-entry-experiment",
    sourceType: "entry",
    sourceLabel: "Quick entry",
    actionType: "create_experiment",
    status: "pending",
    confidence: 0.74,
    reason: "Entry suggests a follow-up comparison of confluence at transfection.",
    payload: {
      title: "Compare 85% vs 70% confluence at transfection",
      project_id: "proj-gfp",
    },
    affectedItem: "Experiment draft",
    createdAt: now,
  },
];

export const entities: EntityRecord[] = [
  {
    id: "entity-hek",
    name: "HEK293T",
    type: "cell_line",
    code: "CL-HEK293T",
    projectName: "GFP transfection optimization",
    status: "active",
    description: "Demo mammalian cell line for protocol run examples.",
  },
  {
    id: "entity-plasmid",
    name: "pLenti-GFP",
    type: "plasmid",
    code: "PL-GFP-001",
    projectName: "GFP transfection optimization",
    status: "active",
    description: "Demo plasmid linked to the sequence library.",
  },
  {
    id: "entity-primer",
    name: "GAPDH primer pair",
    type: "primer",
    code: "PR-GAPDH-001",
    projectName: "Methods notebook",
    status: "active",
    description: "Demo qPCR housekeeping primer pair.",
  },
  {
    id: "entity-hek-wcb",
    name: "HEK293T working cell bank",
    type: "sample",
    code: "SMP-HEK-WCB-001",
    projectName: "GFP transfection optimization",
    status: "active",
    description: "Lightweight sample profile with aliquots, storage position, and lifecycle events.",
  },
];

export const sampleProfiles: SampleProfile[] = [
  {
    id: "sample-hek-wcb",
    entityId: "entity-hek-wcb",
    name: "HEK293T working cell bank",
    sampleCode: "SMP-HEK-WCB-001",
    sampleType: "cell_line_bank",
    sourceLabel: "HEK293T master culture P18",
    sourceType: "cell_culture",
    projectId: "proj-gfp",
    projectName: "GFP transfection optimization",
    status: "stocked",
    collectedAt: "2026-07-06T15:30:00+08:00",
    preparedAt: "2026-07-06T16:50:00+08:00",
    biosafetyLevel: "BSL-2",
    storageRequirement: "-80 C cryovial storage",
    freezeThawCount: 1,
    aliquotCount: 2,
    totalQuantity: 1,
    unit: "vial",
    primaryLocation: "-80C freezer A / rack 1 / box HEK-WCB",
    relatedExperimentIds: ["exp-transfection-pilot"],
    warnings: [
      {
        type: "freeze_thaw",
        severity: "watch",
        message: "One aliquot has been thawed; keep remaining vial as the active reserve.",
      },
    ],
    notes: "Sample-level identity is separated from vial-level aliquots so experiments can cite the same biological source.",
  },
];

export const sampleLifecycleEvents: SampleLifecycleEvent[] = [
  {
    id: "sample-event-register",
    sampleProfileId: "sample-hek-wcb",
    type: "register",
    title: "Registered working cell bank profile",
    occurredAt: "2026-07-06T15:30:00+08:00",
    notes: "Created as a sample profile linked to the GFP optimization project.",
  },
  {
    id: "sample-event-aliquot-a01",
    sampleProfileId: "sample-hek-wcb",
    type: "aliquot",
    title: "Created cryovial aliquot A01",
    occurredAt: "2026-07-06T17:00:00+08:00",
    inventoryItemId: "inv-hek-wcb-a01",
    aliquotCode: "HEK-WCB-A01",
    toLocation: "-80C freezer A / rack 1 / box HEK-WCB / A01",
    quantityChange: 1,
    unit: "vial",
  },
  {
    id: "sample-event-aliquot-a02",
    sampleProfileId: "sample-hek-wcb",
    type: "aliquot",
    title: "Created cryovial aliquot A02",
    occurredAt: "2026-07-06T17:02:00+08:00",
    inventoryItemId: "inv-hek-wcb-a02",
    aliquotCode: "HEK-WCB-A02",
    toLocation: "-80C freezer A / rack 1 / box HEK-WCB / A02",
    quantityChange: 1,
    unit: "vial",
  },
  {
    id: "sample-event-thaw-a01",
    sampleProfileId: "sample-hek-wcb",
    type: "thaw",
    title: "Thawed aliquot A01 for transfection setup",
    occurredAt: "2026-07-07T13:20:00+08:00",
    experimentId: "exp-transfection-pilot",
    experimentTitle: "GFP transfection pilot - 2 well scale",
    inventoryItemId: "inv-hek-wcb-a01",
    aliquotCode: "HEK-WCB-A01",
    fromLocation: "-80C freezer A / rack 1 / box HEK-WCB / A01",
    quantityChange: -1,
    unit: "vial",
    notes: "Lifecycle event mirrors the inventory transaction and keeps the sample lineage visible.",
  },
  {
    id: "sample-event-result-link",
    sampleProfileId: "sample-hek-wcb",
    type: "result_link",
    title: "Linked to pending 24 h fluorescence readout",
    occurredAt: "2026-07-07T14:00:00+08:00",
    experimentId: "exp-transfection-pilot",
    experimentTitle: "GFP transfection pilot - 2 well scale",
    notes: "No biological conclusion is recorded yet; this only preserves provenance.",
  },
];

export const results: ResultRecord[] = [
  {
    id: "result-gfp-24h",
    title: "24 h GFP expression placeholder",
    resultType: "fluorescence_expression",
    experimentTitle: "GFP transfection pilot - 2 well scale",
    entityName: "pLenti-GFP",
    projectName: "GFP transfection optimization",
    status: "active",
    textValue: "pending",
    notes: "Result form seeded from protocol template. No measured result yet.",
  },
  {
    id: "result-pcr-template",
    title: "PCR lane map template",
    resultType: "gel_lane_map",
    experimentTitle: "GAPDH primer gradient check",
    projectName: "Methods notebook",
    status: "active",
    notes: "Structured placeholder for future gel image attachment.",
  },
];

export const procurementInquiries: ProcurementInquiry[] = [
  {
    id: "inq-july-reagents",
    title: "July reagent and consumable inquiry",
    status: "selected",
    sourceType: "excel",
    projectId: "proj-gfp",
    projectName: "GFP transfection optimization",
    importedFileName: "2026-07-self-purchase-quotes.xlsx",
    supplierScope: "multi_supplier",
    quotedAt: "2026-07-08T09:10:00+08:00",
    notes: "Imported as a lightweight inquiry sheet. Only selected rows should become purchase requests.",
    quoteLineIds: [
      "quote-agarose-biorad",
      "quote-agarose-alt",
      "quote-tips-rainin",
      "quote-tips-alt",
    ],
    createdAt: "2026-07-08T09:00:00+08:00",
  },
];

export const procurementQuoteLines: ProcurementQuoteLine[] = [
  {
    id: "quote-agarose-biorad",
    inquiryId: "inq-july-reagents",
    status: "selected",
    supplierName: "Bio-Rad",
    productCategory: "化学试剂",
    productName: "Agarose",
    casNumber: "9012-36-6",
    specification: "100 g",
    quantity: 1,
    packageUnit: "瓶",
    amountExclTax: 88,
    taxAmount: 11.44,
    unitPriceExclTax: 88,
    capacity: 100,
    capacityUnit: "g",
    brand: "Bio-Rad",
    catalogNumber: "1613100",
    decisionReason: "Selected for valid chemical fields and existing supplier reliability.",
    selectedAt: "2026-07-08T10:00:00+08:00",
    purchaseRequestId: "purchase-agarose",
  },
  {
    id: "quote-agarose-alt",
    inquiryId: "inq-july-reagents",
    status: "not_selected",
    supplierName: "Reagent Supplier B",
    productCategory: "化学试剂",
    productName: "Agarose",
    casNumber: "9012-36-6",
    specification: "100 g",
    quantity: 1,
    packageUnit: "瓶",
    amountExclTax: 126,
    taxAmount: 16.38,
    unitPriceExclTax: 126,
    capacity: 100,
    capacityUnit: "g",
    brand: "Supplier B",
    catalogNumber: "AG-100",
    decisionReason: "Not selected: higher total price for the same specification.",
  },
  {
    id: "quote-tips-rainin",
    inquiryId: "inq-july-reagents",
    status: "selected",
    supplierName: "Rainin",
    productCategory: "实验材料",
    productName: "Filtered P20 tip reloads",
    specification: "10 racks",
    quantity: 10,
    packageUnit: "盒",
    amountExclTax: 620,
    taxAmount: 80.6,
    unitPriceExclTax: 62,
    brand: "Rainin",
    catalogNumber: "RT-L10F",
    decisionReason: "Selected because it matches the pipette platform already in use.",
    selectedAt: "2026-07-08T10:05:00+08:00",
    purchaseRequestId: "purchase-tips",
  },
  {
    id: "quote-tips-alt",
    inquiryId: "inq-july-reagents",
    status: "future_candidate",
    supplierName: "Consumable Supplier C",
    productCategory: "实验材料",
    productName: "Filtered P20 tip reloads",
    specification: "10 racks",
    quantity: 10,
    packageUnit: "盒",
    amountExclTax: 460,
    taxAmount: 59.8,
    unitPriceExclTax: 46,
    brand: "Supplier C",
    catalogNumber: "P20-F-10",
    decisionReason: "Lower price, but compatibility should be checked before switching.",
  },
];

export const purchases: PurchaseRequest[] = [
  {
    id: "purchase-agarose",
    title: "Agarose refill",
    status: "planned",
    vendor: "Bio-Rad",
    catalogNumber: "1613100",
    procurementQuoteLineId: "quote-agarose-biorad",
    quantity: 1,
    unit: "瓶",
    price: 99.44,
    notes: "Selected from the July inquiry sheet; receive into inventory as 100 g after purchase.",
  },
  {
    id: "purchase-tips",
    title: "Filtered P20 tip reloads",
    status: "ordered",
    vendor: "Rainin",
    catalogNumber: "RT-L10F",
    procurementQuoteLineId: "quote-tips-rainin",
    quantity: 10,
    unit: "盒",
    price: 700.6,
    orderDate: "2026-07-05",
  },
];

const gfpSequence =
  "ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAG";

export const sequences: SequenceRecord[] = [
  {
    id: "seq-gfp",
    code: "SEQ-000001",
    name: "GFP insert demo",
    designType: "fragment",
    status: "active",
    type: "DNA",
    sequence: gfpSequence,
    version: "1.0",
    validationStatus: "unverified",
    description: `Length ${sequenceLength(gfpSequence)} bp; GC ${gcPercent(
      gfpSequence,
    )}%; translation preview ${translateDna(gfpSequence).slice(0, 16)}...`,
    linkedEntity: "pLenti-GFP",
  },
];

export const aiProviders: AIProviderRecord[] = [
  {
    id: "ai-manual",
    name: "Manual copy-paste mode",
    type: "manual_copy_paste",
    defaultModel: "external web subscription",
    capabilities: ["text", "structured_output"],
    enabled: true,
  },
  {
    id: "ai-openai-placeholder",
    name: "OpenAI API placeholder",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    maskedKey: "not configured",
    defaultModel: "gpt-4.1",
    capabilities: ["text", "structured_output", "vision", "embeddings"],
    enabled: false,
  },
  {
    id: "ai-compatible-placeholder",
    name: "OpenAI-compatible local endpoint",
    type: "openai_compatible",
    baseUrl: "http://localhost:11434/v1",
    maskedKey: "not required",
    defaultModel: "local-model",
    capabilities: ["text", "local"],
    enabled: false,
  },
];

export const referenceConnectors: ReferenceConnectorRecord[] = [
  {
    id: "ref-zotero-local",
    provider: "zotero",
    displayName: "Zotero local library",
    libraryScope: "Personal methods and protocol references",
    baseUrl: "http://127.0.0.1:23119",
    enabled: false,
    notes: "Connector placeholder only; LabNest should link citations and attachments without embedding the full literature manager.",
  },
  {
    id: "ref-endnote-ris",
    provider: "endnote",
    displayName: "EndNote RIS import",
    libraryScope: "Collaborator-shared reference exports",
    enabled: false,
    notes: "Batch import/export adapter placeholder for future reference links.",
  },
];

export const activity: ActivityItem[] = [
  {
    id: "act-run",
    action: "create_protocol_run",
    targetType: "protocol_run",
    targetTitle: "GFP transfection pilot - 2 well scale",
    createdAt: "2026-07-07T14:00:00+08:00",
    detail: "Created experiment draft from Cell transfection v1.",
  },
  {
    id: "act-pa",
    action: "create_proposed_actions",
    targetType: "experiment",
    targetTitle: "GFP transfection pilot - 2 well scale",
    createdAt: "2026-07-07T14:01:00+08:00",
    detail: "Generated 2 pending inventory consumption proposals.",
  },
  {
    id: "act-entry",
    action: "create_entry",
    targetType: "entry",
    targetTitle: "Adjusted seeding density before GFP transfection",
    createdAt: "2026-07-07T20:40:00+08:00",
    detail: "Captured journal-like note with linked entities.",
  },
];

export const dashboardStats = {
  pendingActions: proposedActions.filter((action) => action.status === "pending").length,
  runningExperiments: experiments.filter((experiment) => experiment.status === "running").length,
  activeProtocols: protocols.filter((protocol) => protocol.availability === "active").length,
  lowInventory: inventoryItems.filter(
    (item) => item.lowThreshold !== undefined && item.currentQuantity < item.lowThreshold,
  ).length,
};
