import { prisma } from "@/lib/db";
import { downloadResponse, formatExportTimestamp } from "@/lib/export";

export const runtime = "nodejs";

export async function GET() {
  const [
    projects,
    researchPlans,
    entries,
    experiments,
    protocols,
    entities,
    sampleProfiles,
    inventoryLocations,
    inventoryItems,
    inventoryTransactions,
    results,
    resultDatasets,
    reports,
    procurementInquiries,
    purchaseRequests,
    attachments,
    sequences,
    itemLinks,
    proposedActions,
    aiProviders,
    referenceConnectors,
  ] = await Promise.all([
    prisma.project.findMany(),
    prisma.researchPlan.findMany({ include: { protocols: true } }),
    prisma.entry.findMany(),
    prisma.experiment.findMany({ include: { steps: true, protocolRun: true, protocolVersions: true } }),
    prisma.protocol.findMany({ include: { versions: true } }),
    prisma.entity.findMany(),
    prisma.sampleProfile.findMany({ include: { events: true } }),
    prisma.inventoryLocation.findMany(),
    prisma.inventoryItem.findMany(),
    prisma.inventoryTransaction.findMany(),
    prisma.result.findMany(),
    prisma.resultDataset.findMany(),
    prisma.report.findMany({ include: { sources: true } }),
    prisma.procurementInquiry.findMany({ include: { quoteLines: true } }),
    prisma.purchaseRequest.findMany(),
    prisma.attachment.findMany({ include: { links: true } }),
    prisma.sequence.findMany({ include: { versions: { include: { features: true, modifications: true, collectionMembers: true } }, entityLinks: true } }),
    prisma.itemLink.findMany(),
    prisma.proposedAction.findMany(),
    prisma.aIProvider.findMany({
      select: {
        id: true,
        name: true,
        type: true,
        baseUrl: true,
        defaultModel: true,
        capabilitiesJson: true,
        enabled: true,
        createdAt: true,
        updatedAt: true,
      },
    }),
    prisma.referenceConnector.findMany(),
  ]);

  const backup = {
    app: "LabNest",
    version: 2,
    exportedAt: new Date().toISOString(),
    note: "File binaries are not embedded; attachment and ResultDataset metadata include storage paths or external references for local recovery.",
    data: {
      projects,
      researchPlans,
      entries,
      experiments,
      protocols,
      entities,
      sampleProfiles,
      inventoryLocations,
      inventoryItems,
      inventoryTransactions,
      results,
      resultDatasets,
      reports,
      procurementInquiries,
      purchaseRequests,
      attachments,
      sequences,
      itemLinks,
      proposedActions,
      aiProviders,
      referenceConnectors,
    },
  };

  return downloadResponse(
    JSON.stringify(backup, null, 2),
    `labnest-backup-${formatExportTimestamp()}.json`,
    "application/json; charset=utf-8",
  );
}
