import {validateDisplayUnits} from "./result-presentation";
import {applyPipettingOptions} from "./pipetting";
import { enhanceDefinition, newDefinitions, isFieldVisible } from "./task-definitions";
import { dilution, addStock, serialPlan, mixPlan, batchPlan, wbPlan, type MixRow, type SampleRow } from "./planning";
import { convert, parseScalar, units, normalizeUnit, canonicalUnits } from "./quantities";
export type CalculatorCategory = "cell-culture" | "solutions" | "molecular-biology" | "virology-microbiology" | "general" | "protein";

export type CalculatorField = {
  key: string;
  label: string;
  labelZh: string;
  type: "number" | "text" | "textarea" | "select";
  unit?: string;
  placeholder?: string;
  defaultValue?: string | number;
  min?: number;
  step?: number;
  options?: Array<{ value: string; label: string; labelZh: string }>;
};

export type CalculatorDefinition = {
  id: string;
  name: string;
  nameZh: string;
  shortDescription: string;
  shortDescriptionZh: string;
  category: CalculatorCategory;
  aliases: string[];
  plateAware: boolean;
  method: string;
  methodZh: string;
  methodVersion: string;
  fields: CalculatorField[];
  exampleInputs: Record<string, unknown>;
};

export type CalculatorRequest = { calculatorId: string; inputs: Record<string, unknown> };
export type CalculatorOutput = { key: string; label: string; labelZh: string; value: number | string; unit?: string };
export type CalculatorResult = {
  operations?: import("./operations").LiquidOperation[];
  structuredWarnings?: import("./pipetting").PipettingWarning[];
  displayUnits?: Record<string,string>;
  schemaVersion?: number;
  status?: "valid" | "estimate" | "partial";
  mode?: string;
  rawInputs?: Record<string, unknown>;
  normalizedInputs?: Record<string, unknown>;
  calculatorId: string;
  methodVersion: string;
  outputs: CalculatorOutput[];
  outputMap: Record<string, number | string>;
  warnings: string[];
  notes: string[];
  table?: Array<Record<string, number | string>>;
};

const numberField = (key: string, label: string, labelZh: string, defaultValue: number, unit?: string, min = 0): CalculatorField => ({ key, label, labelZh, type: "number", defaultValue, unit, min, step: "integer" === unit ? 1 : 0.01 });
const textField = (key: string, label: string, labelZh: string, defaultValue: string, textarea = false): CalculatorField => ({ key, label, labelZh, type: textarea ? "textarea" : "text", defaultValue });
const selectField = (key: string, label: string, labelZh: string, defaultValue: string, options: Array<[string, string, string]>): CalculatorField => ({ key, label, labelZh, type: "select", defaultValue, options: options.map(([value, en, zh]) => ({ value, label: en, labelZh: zh })) });

const definitions: CalculatorDefinition[] = [
  { id: "hemocytometer", name: "Hemocytometer", nameZh: "血球计数板", shortDescription: "Cell concentration from counted quadrants", shortDescriptionZh: "根据计数区和稀释倍数计算细胞浓度", category: "cell-culture", aliases: ["cell count", "细胞计数"], plateAware: false, method: "Average count × dilution factor × 10⁴ cells/mL", methodZh: "平均计数 × 稀释倍数 × 10⁴ cells/mL", methodVersion: "hemocytometer-v1", fields: [textField("counts", "Quadrant counts", "计数区细胞数", "13,11,14,17"), numberField("dilutionFactor", "Dilution factor", "稀释倍数", 2), numberField("viabilityPercent", "Viability", "细胞活率", 90, "%")], exampleInputs: { counts: "13,11,14,17", dilutionFactor: 3, viabilityPercent: 90 } },
  { id: "seeding", name: "Seeding", nameZh: "细胞铺板", shortDescription: "Cells and suspension volume per well", shortDescriptionZh: "计算每孔细胞量及整批细胞悬液", category: "cell-culture", aliases: ["plating", "铺板"], plateAware: true, method: "Cell requirement and volume balance with overage applied once", methodZh: "按总孔数计算细胞需求并仅统一加入一次余量", methodVersion: "seeding-v1", fields: [numberField("stockCellsPerMl", "Stock cell density", "细胞原液浓度", 1_000_000, "cells/mL"), numberField("wells", "Wells", "孔数", 24, "integer", 1), numberField("plates", "Plates", "板数", 1, "integer", 1), numberField("cellsPerWell", "Cells per well", "每孔细胞数", 50_000, "cells"), numberField("volumePerWellUl", "Volume per well", "每孔体积", 500, "µL"), numberField("overagePercent", "Overage", "额外余量", 10, "%")], exampleInputs: { stockCellsPerMl: 1_000_000, wells: 24, plates: 1, cellsPerWell: 50_000, volumePerWellUl: 500, overagePercent: 10 } },
  { id: "hydrogel", name: "Hydrogel", nameZh: "水凝胶培养", shortDescription: "3D cell and hydrogel mixture", shortDescriptionZh: "计算3D培养的细胞与水凝胶混合体系", category: "cell-culture", aliases: ["3D culture", "Matrigel", "三维培养"], plateAware: true, method: "Target cells plus gel-to-cell-suspension volume ratio", methodZh: "依据目标细胞量及凝胶与细胞悬液体积比计算", methodVersion: "hydrogel-v1", fields: [numberField("stockCellsPerMl", "Stock cell density", "细胞原液浓度", 2_000_000, "cells/mL"), numberField("targetCellsPerMl", "Target density", "目标细胞密度", 1_000_000, "cells/mL"), numberField("wells", "Wells", "孔数", 10, "integer", 1), numberField("volumePerWellUl", "Volume per well", "每孔体积", 100, "µL"), numberField("gelParts", "Hydrogel parts", "水凝胶份数", 4), numberField("suspensionParts", "Cell suspension parts", "细胞悬液份数", 1)], exampleInputs: { stockCellsPerMl: 10_000_000, targetCellsPerMl: 1_000_000, wells: 10, volumePerWellUl: 100, gelParts: 4, suspensionParts: 1 } },
  { id: "split", name: "Split Calculator", nameZh: "细胞传代", shortDescription: "Post-split confluency and readiness estimate", shortDescriptionZh: "估算传代后汇合度及达到目标的时间", category: "cell-culture", aliases: ["passage", "传代", "confluency"], plateAware: false, method: "Exponential growth estimate from confluency, split ratio, and doubling time", methodZh: "根据汇合度、传代比例和倍增时间进行指数生长估算", methodVersion: "split-v1", fields: [numberField("currentConfluency", "Current confluency", "当前汇合度", 90, "%"), numberField("splitRatio", "Split denominator", "传代比例分母", 4), numberField("targetConfluency", "Target confluency", "目标汇合度", 80, "%"), numberField("doublingTimeHours", "Doubling time", "倍增时间", 24, "h")], exampleInputs: { currentConfluency: 90, splitRatio: 4, targetConfluency: 80, doublingTimeHours: 24 } },
  { id: "freezing", name: "Freezing", nameZh: "细胞冻存", shortDescription: "Cryovials and freezing-medium composition", shortDescriptionZh: "计算冻存管数和冻存液组成", category: "cell-culture", aliases: ["cryopreservation", "冻存"], plateAware: false, method: "Available cells divided by target cells per vial; medium components by percentage", methodZh: "按每管目标细胞数及冻存液百分比计算", methodVersion: "freezing-v1", fields: [numberField("totalCells", "Total cells", "总细胞数", 10_000_000, "cells"), numberField("cellsPerVial", "Cells per vial", "每管细胞数", 1_000_000, "cells"), numberField("volumePerVialMl", "Volume per vial", "每管体积", 1, "mL"), numberField("dmsoPercent", "DMSO", "DMSO比例", 10, "%"), numberField("serumPercent", "Serum", "血清比例", 20, "%")], exampleInputs: { totalCells: 10_000_000, cellsPerVial: 1_000_000, volumePerVialMl: 1, dmsoPercent: 10, serumPercent: 20 } },
  { id: "transfection", name: "Transfection", nameZh: "转染体系", shortDescription: "Nucleic acid and reagent master mix", shortDescriptionZh: "计算核酸、转染试剂和稀释液", category: "cell-culture", aliases: ["lipofection", "siRNA", "质粒转染"], plateAware: true, method: "Per-well nucleic acid and reagent ratio scaled by wells, replicates, and overage", methodZh: "按每孔核酸量、试剂比例、孔数及余量计算", methodVersion: "transfection-v1", fields: [numberField("wells", "Wells", "孔数", 6, "integer", 1), numberField("replicates", "Replicates", "重复数", 1, "integer", 1), numberField("dnaUgPerWell", "DNA per well", "每孔DNA", 2, "µg"), numberField("dnaConcentrationUgUl", "DNA stock concentration", "DNA母液浓度", 1, "µg/µL"), numberField("reagentUlPerUg", "Reagent per µg DNA", "每µg DNA试剂量", 3, "µL/µg"), numberField("complexVolumeUlPerWell", "Complex volume per well", "每孔复合物体积", 125, "µL"), numberField("overagePercent", "Overage", "额外余量", 10, "%")], exampleInputs: { wells: 6, replicates: 1, dnaUgPerWell: 2, dnaConcentrationUgUl: 1, reagentUlPerUg: 3, complexVolumeUlPerWell: 125, overagePercent: 10 } },
  { id: "kill-curve", name: "Kill Curve", nameZh: "杀灭曲线", shortDescription: "Antibiotic dose series and stock additions", shortDescriptionZh: "生成抗生素浓度梯度及母液加入量", category: "cell-culture", aliases: ["antibiotic", "筛选浓度"], plateAware: true, method: "Linear or logarithmic dose series followed by C1V1=C2V2", methodZh: "生成线性或对数浓度序列后按C1V1=C2V2计算", methodVersion: "kill-curve-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10, "mg/mL"), numberField("minimum", "Minimum dose", "最低浓度", 0.5, "µg/mL"), numberField("maximum", "Maximum dose", "最高浓度", 10, "µg/mL"), numberField("points", "Dose points", "浓度点数", 8, "integer", 2), numberField("volumePerWellMl", "Volume per well", "每孔体积", 0.5, "mL"), selectField("scale", "Scale", "梯度方式", "linear", [["linear", "Linear", "线性"], ["log", "Logarithmic", "对数"]])], exampleInputs: { stockConcentration: 10, minimum: 0.5, maximum: 10, points: 8, volumePerWellMl: 0.5, scale: "linear" } },
  { id: "viability", name: "Viability", nameZh: "细胞活率", shortDescription: "Live/dead cells and resuspension", shortDescriptionZh: "计算活细胞、死细胞及重悬体积", category: "cell-culture", aliases: ["trypan blue", "台盼蓝"], plateAware: false, method: "Total cells partitioned by viability; optional live-cell target density", methodZh: "按活率拆分活/死细胞，并可按目标活细胞浓度重悬", methodVersion: "viability-v1", fields: [numberField("totalCells", "Total cells", "总细胞数", 200_000, "cells"), numberField("viabilityPercent", "Viability", "细胞活率", 90, "%"), numberField("targetLiveCellsPerMl", "Target live-cell density", "目标活细胞浓度", 100_000, "cells/mL")], exampleInputs: { totalCells: 200_000, viabilityPercent: 90, targetLiveCellsPerMl: 100_000 } },
  { id: "od600", name: "OD600", nameZh: "OD600菌液浓度", shortDescription: "Optical density to estimated cell density", shortDescriptionZh: "根据OD600估算微生物浓度", category: "cell-culture", aliases: ["bacterial density", "菌液浓度"], plateAware: false, method: "OD600 corrected for path length and multiplied by an explicit empirical factor", methodZh: "按光程校正OD600后乘以明确的经验换算因子", methodVersion: "od600-v1", fields: [numberField("od600", "OD600", "OD600读数", 0.8), numberField("pathLengthCm", "Path length", "光程", 1, "cm"), numberField("cellsPerMlPerOd", "Empirical factor", "经验换算因子", 800_000_000, "cells/mL/OD"), numberField("cultureVolumeMl", "Culture volume", "培养体积", 5, "mL")], exampleInputs: { od600: 0.8, pathLengthCm: 1, cellsPerMlPerOd: 800_000_000, cultureVolumeMl: 5 } },
  { id: "cfu", name: "CFU/mL", nameZh: "菌落形成单位", shortDescription: "Colony-forming units from plated dilution", shortDescriptionZh: "根据菌落数、稀释倍数和涂板体积计算CFU/mL", category: "cell-culture", aliases: ["colony forming units", "菌落计数"], plateAware: false, method: "CFU/mL = colonies ÷ (dilution × plated volume in mL)", methodZh: "CFU/mL = 菌落数 ÷（稀释度 × 涂板体积mL）", methodVersion: "cfu-v1", fields: [numberField("colonies", "Colonies", "菌落数", 120, "integer", 1), numberField("dilution", "Dilution fraction", "稀释度", 0.000001), numberField("platedVolumeMl", "Plated volume", "涂板体积", 0.1, "mL"), numberField("dnaUg", "DNA amount (optional)", "DNA用量（可选）", 0, "µg")], exampleInputs: { colonies: 120, dilution: 0.000001, platedVolumeMl: 0.1, dnaUg: 2 } },
  { id: "colony-counter", name: "Colony & Plaque Counter", nameZh: "菌落与噬菌斑辅助计数", shortDescription: "Reviewable image-assisted counting", shortDescriptionZh: "可人工复核的图像辅助计数", category: "cell-culture", aliases: ["photo count", "菌落图片", "plaque counter"], plateAware: false, method: "Browser-local connected-region detection followed by mandatory human confirmation", methodZh: "浏览器本地连通区域识别，并要求人工确认", methodVersion: "colony-counter-v1", fields: [numberField("automaticCount", "Automatic count", "自动识别数", 42, "integer"), numberField("manualAdjustment", "Manual adjustment", "人工增减", 0, "integer", -100000)], exampleInputs: { automaticCount: 42, manualAdjustment: -2 } },

  { id: "reagent-dosing", name: "Reagent Dosing", nameZh: "试剂加药", shortDescription: "Stock addition to a desired final concentration", shortDescriptionZh: "从母液计算目标终浓度所需加入量", category: "solutions", aliases: ["dose", "C1V1", "加药"], plateAware: true, method: "C1V1 = C2V2", methodZh: "C1V1 = C2V2", methodVersion: "reagent-dosing-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10, "mM"), numberField("targetConcentration", "Final concentration", "目标终浓度", 10, "µM"), numberField("finalVolumeMl", "Final volume", "最终体积", 10, "mL"), numberField("stockToTargetFactor", "Stock-unit to target-unit factor", "母液单位相对目标单位倍数", 1000)], exampleInputs: { stockConcentration: 10, targetConcentration: 10, finalVolumeMl: 10, stockToTargetFactor: 1000 } },
  { id: "dilution", name: "Dilution", nameZh: "常规稀释", shortDescription: "Dilute a stock to a working concentration", shortDescriptionZh: "将浓缩母液稀释至工作浓度", category: "solutions", aliases: ["C1V1=C2V2", "母液稀释"], plateAware: true, method: "C1V1 = C2V2 with compatible concentration units", methodZh: "使用兼容浓度单位的C1V1=C2V2", methodVersion: "dilution-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10), numberField("targetConcentration", "Target concentration", "目标浓度", 1), numberField("finalVolume", "Final volume", "目标总体积", 10), selectField("volumeUnit", "Volume unit", "体积单位", "mL", [["µL", "µL", "µL"], ["mL", "mL", "mL"], ["L", "L", "L"]])], exampleInputs: { stockConcentration: 10, targetConcentration: 1, finalVolume: 10, volumeUnit: "mL" } },
  { id: "fold-dilution", name: "Fold Dilution", nameZh: "倍数稀释", shortDescription: "Prepare 1× from a concentrated stock", shortDescriptionZh: "由浓缩液配制1×工作液", category: "solutions", aliases: ["2x", "10x", "倍液"], plateAware: true, method: "Concentrated-stock volume = final volume ÷ fold", methodZh: "浓缩液体积 = 最终体积 ÷ 倍数", methodVersion: "fold-dilution-v1", fields: [numberField("fold", "Stock fold", "浓缩倍数", 10), numberField("finalVolume", "Final volume", "最终体积", 100, "mL")], exampleInputs: { fold: 10, finalVolume: 100 } },
  { id: "serial-dilution", name: "Serial Dilution", nameZh: "连续稀释", shortDescription: "Multi-step fixed-factor dilution", shortDescriptionZh: "生成多级固定倍数稀释步骤", category: "solutions", aliases: ["梯度稀释", "serial"], plateAware: true, method: "Each level transfers total volume ÷ dilution factor from the prior level", methodZh: "每一级从前一级转移目标总体积除以稀释倍数", methodVersion: "serial-dilution-v1", fields: [numberField("startingConcentration", "Starting concentration", "起始浓度", 100), numberField("dilutionFactor", "Dilution factor", "每级稀释倍数", 10), numberField("levels", "Levels", "级数", 6, "integer", 1), numberField("totalVolumePerLevel", "Volume per level", "每级总体积", 100, "µL")], exampleInputs: { startingConcentration: 100, dilutionFactor: 10, levels: 6, totalVolumePerLevel: 100 } },
  { id: "molarity", name: "Molarity", nameZh: "摩尔浓度", shortDescription: "Concentration, mass, or volume from molecular weight", shortDescriptionZh: "根据分子量求浓度、质量或体积", category: "solutions", aliases: ["moles", "摩尔", "称量"], plateAware: false, method: "Moles = mass ÷ molecular weight; molarity = moles ÷ volume", methodZh: "物质的量 = 质量 ÷ 分子量；摩尔浓度 = 物质的量 ÷ 体积", methodVersion: "molarity-v1", fields: [selectField("mode", "Solve for", "求解目标", "mass", [["mass", "Mass to weigh", "称量质量"], ["concentration", "Concentration", "浓度"], ["volume", "Volume", "体积"]]), numberField("molecularWeight", "Molecular weight", "分子量", 180.16, "g/mol"), numberField("concentrationM", "Concentration", "摩尔浓度", 0.1, "M"), numberField("volumeL", "Volume", "体积", 0.1, "L"), numberField("massG", "Mass", "质量", 1.8016, "g")], exampleInputs: { mode: "mass", molecularWeight: 180.16, concentrationM: 0.1, volumeL: 0.1, massG: 1.8016 } },
  { id: "percent-solution", name: "% Solution", nameZh: "百分比溶液", shortDescription: "w/v or v/v solution preparation", shortDescriptionZh: "配制w/v或v/v百分比溶液", category: "solutions", aliases: ["w/v", "v/v", "百分浓度"], plateAware: false, method: "% w/v = g per 100 mL; % v/v = mL per 100 mL", methodZh: "% w/v表示每100 mL中的克数；% v/v表示每100 mL中的毫升数", methodVersion: "percent-solution-v1", fields: [selectField("type", "Solution type", "溶液类型", "w/v", [["w/v", "w/v", "质量/体积"], ["v/v", "v/v", "体积/体积"]]), numberField("percentage", "Percentage", "百分浓度", 5, "%"), numberField("targetVolumeMl", "Target volume", "目标体积", 500, "mL")], exampleInputs: { type: "w/v", percentage: 5, targetVolumeMl: 500 } },
  { id: "media-recipe", name: "Media Recipe", nameZh: "培养基配方", shortDescription: "Scale a custom medium recipe", shortDescriptionZh: "按目标体积缩放培养基配方", category: "solutions", aliases: ["culture medium", "培养液"], plateAware: false, method: "Each component scales linearly from the recipe base volume", methodZh: "各组分按配方基础体积线性缩放", methodVersion: "media-recipe-v1", fields: [numberField("baseVolumeMl", "Recipe base volume", "配方基础体积", 500, "mL"), numberField("targetVolumeMl", "Target volume", "目标体积", 1000, "mL"), textField("components", "Components (name, amount, unit)", "组分（名称,用量,单位）", "FBS,50,mL\nPen/Strep,5,mL", true)], exampleInputs: { baseVolumeMl: 500, targetVolumeMl: 1000, components: "FBS,50,mL\nPen/Strep,5,mL" } },
  { id: "buffer-recipe", name: "Buffer Recipe", nameZh: "缓冲液配方", shortDescription: "Scale a custom buffer recipe", shortDescriptionZh: "按目标体积缩放缓冲液配方", category: "solutions", aliases: ["PBS", "Tris", "缓冲液"], plateAware: false, method: "Each component scales linearly from the recipe base volume", methodZh: "各组分按配方基础体积线性缩放", methodVersion: "buffer-recipe-v1", fields: [numberField("baseVolumeMl", "Recipe base volume", "配方基础体积", 1000, "mL"), numberField("targetVolumeMl", "Target volume", "目标体积", 500, "mL"), textField("components", "Components (name, amount, unit)", "组分（名称,用量,单位）", "NaCl,8,g\nKCl,0.2,g", true)], exampleInputs: { baseVolumeMl: 1000, targetVolumeMl: 500, components: "NaCl,8,g\nKCl,0.2,g" } },
  { id: "ic50-ec50", name: "IC50 / EC50", nameZh: "IC50 / EC50拟合", shortDescription: "Four-parameter logistic dose-response fit", shortDescriptionZh: "四参数Logistic剂量反应拟合", category: "solutions", aliases: ["4PL", "dose response", "半数抑制"], plateAware: false, method: "Four-parameter logistic model fitted by deterministic coordinate descent", methodZh: "使用确定性坐标下降拟合四参数Logistic模型", methodVersion: "four-pl-v2", fields: [selectField("mode", "Response direction", "反应方向", "activation", [["inhibition", "Remaining response (falling)", "残存反应（下降）"], ["activation", "Activation (rising)", "激活反应（上升）"]]), textField("points", "Dose,response pairs", "浓度,反应值", "0.1,1\n1,10\n10,50\n100,90\n1000,99", true)], exampleInputs: { mode: "activation", points: "0.1,1\n1,10\n10,50\n100,90\n1000,99" } },

  { id: "master-mix", name: "Master Mix", nameZh: "Master Mix体系", shortDescription: "Scale repeated reaction components", shortDescriptionZh: "按反应数和余量计算整批反应体系", category: "molecular-biology", aliases: ["PCR mix", "反应体系"], plateAware: true, method: "Per-reaction components × reactions × (1 + overage)", methodZh: "单反应组分 × 反应数 ×（1 + 余量）", methodVersion: "master-mix-v1", fields: [numberField("reactions", "Reactions", "反应数", 10, "integer", 1), numberField("overagePercent", "Overage", "额外余量", 10, "%"), textField("components", "Components (name, µL/reaction)", "组分（名称,每反应µL）", "2× SYBR Mix,10\nForward primer,0.5\nReverse primer,0.5\nWater,8", true)], exampleInputs: { reactions: 10, overagePercent: 10, components: "2× SYBR Mix,10\nForward primer,0.5\nReverse primer,0.5\nWater,8" } },
  { id: "ligation", name: "Ligation", nameZh: "连接反应", shortDescription: "Insert mass for a vector:insert molar ratio", shortDescriptionZh: "按载体与插入片段摩尔比计算插入片段质量", category: "molecular-biology", aliases: ["cloning", "载体连接"], plateAware: false, method: "Insert ng = vector ng × insert bp ÷ vector bp × molar ratio", methodZh: "插入片段ng = 载体ng × 插入片段bp ÷ 载体bp × 摩尔比", methodVersion: "ligation-v1", fields: [numberField("vectorBp", "Vector length", "载体长度", 5000, "bp"), numberField("insertBp", "Insert length", "插入片段长度", 1000, "bp"), numberField("vectorNg", "Vector mass", "载体质量", 50, "ng"), numberField("molarRatio", "Insert:vector molar ratio", "插入:载体摩尔比", 3)], exampleInputs: { vectorBp: 5000, insertBp: 1000, vectorNg: 50, molarRatio: 3 } },
  { id: "tm", name: "Tm Calculator", nameZh: "引物Tm计算", shortDescription: "Primer melting-temperature estimate", shortDescriptionZh: "根据序列与盐条件估算引物熔解温度", category: "molecular-biology", aliases: ["primer", "melting temperature", "引物"], plateAware: false, method: "Wallace rule for short oligos; empirical long-oligo formula with monovalent-salt correction", methodZh: "短寡核苷酸使用Wallace规则，长序列使用含单价盐校正的经验公式", methodVersion: "tm-basic-v1", fields: [textField("sequence", "Primer sequence", "引物序列", "ATGCGTACGTTAGCTAAGCT"), numberField("sodiumMm", "Monovalent salt", "单价盐浓度", 50, "mM")], exampleInputs: { sequence: "ATGCGTACGTTAGCTAAGCT", sodiumMm: 50 } },
  { id: "dna-rna-conversion", name: "DNA / RNA Conversions", nameZh: "DNA / RNA换算", shortDescription: "Mass, moles, molecules, and concentration", shortDescriptionZh: "质量、摩尔数、分子数和浓度换算", category: "molecular-biology", aliases: ["copies", "molecules", "核酸换算"], plateAware: false, method: "Molecular weight from length and nucleic-acid type; molecules from Avogadro constant", methodZh: "按长度与核酸类型估算分子量，再用阿伏伽德罗常数计算分子数", methodVersion: "nucleic-acid-conversion-v1", fields: [selectField("type", "Nucleic acid", "核酸类型", "dsDNA", [["dsDNA", "dsDNA", "双链DNA"], ["ssDNA", "ssDNA", "单链DNA"], ["RNA", "RNA", "RNA"]]), numberField("length", "Length", "长度", 500, "nt/bp"), numberField("massUg", "Mass", "质量", 1, "µg"), numberField("volumeUl", "Volume", "体积", 20, "µL")], exampleInputs: { type: "dsDNA", length: 500, massUg: 1, volumeUl: 20 } },
  { id: "bradford-bca", name: "Bradford / BCA", nameZh: "Bradford / BCA蛋白定量", shortDescription: "Protein standard curve and sample back-calculation", shortDescriptionZh: "蛋白标准曲线拟合与样品浓度回算", category: "molecular-biology", aliases: ["protein assay", "标准曲线", "蛋白浓度"], plateAware: false, method: "Blank-corrected ordinary least-squares linear standard curve", methodZh: "空白扣除后的普通最小二乘线性标准曲线", methodVersion: "protein-linear-v1", fields: [textField("standards", "Standards (concentration, absorbance)", "标准品（浓度,吸光度）", "0,0.05\n0.25,0.18\n0.5,0.31\n1,0.57\n1.5,0.82", true), numberField("sampleAbsorbance", "Sample absorbance", "样品吸光度", 0.44), numberField("dilutionFactor", "Sample dilution factor", "样品稀释倍数", 2)], exampleInputs: { standards: "0,0.05\n0.25,0.18\n0.5,0.31\n1,0.57\n1.5,0.82", sampleAbsorbance: 0.44, dilutionFactor: 2 } },
  { id: "elisa-4pl", name: "ELISA 4PL", nameZh: "ELISA四参数拟合", shortDescription: "ELISA standard curve and sample back-calculation", shortDescriptionZh: "ELISA标准曲线拟合和样品浓度回算", category: "molecular-biology", aliases: ["ELISA", "4PL", "免疫测定"], plateAware: false, method: "Four-parameter logistic standard curve with inverse sample calculation", methodZh: "四参数Logistic标准曲线及样品反算", methodVersion: "elisa-four-pl-v1", fields: [textField("standards", "Standards (concentration, signal)", "标准品（浓度,信号）", "0.1,0.08\n1,0.2\n10,1.0\n100,1.8\n1000,1.95", true), numberField("sampleSignal", "Sample signal", "样品信号", 1), numberField("dilutionFactor", "Sample dilution factor", "样品稀释倍数", 1)], exampleInputs: { standards: "0.1,0.08\n1,0.2\n10,1.0\n100,1.8\n1000,1.95", sampleSignal: 1, dilutionFactor: 1 } },
  { id: "wb-loading", name: "WB Loading", nameZh: "Western Blot上样", shortDescription: "Sample, loading buffer, and reducing agent", shortDescriptionZh: "计算样品、Loading Buffer与还原剂", category: "molecular-biology", aliases: ["western blot", "上样体系"], plateAware: false, method: "Sample volume from target protein mass; concentrated buffer by final fold", methodZh: "按目标蛋白质量计算样品体积，并按终浓度计算浓缩上样缓冲液", methodVersion: "wb-loading-v1", fields: [numberField("sampleConcentrationUgUl", "Sample concentration", "样品浓度", 2, "µg/µL"), numberField("targetProteinUg", "Protein per lane", "每孔蛋白量", 20, "µg"), numberField("finalLoadingVolumeUl", "Final loading volume", "最终上样体积", 20, "µL"), numberField("bufferFold", "Loading buffer stock", "Loading Buffer倍数", 4), numberField("reducingAgentPercent", "Reducing agent", "还原剂比例", 5, "%")], exampleInputs: { sampleConcentrationUgUl: 2, targetProteinUg: 20, finalLoadingVolumeUl: 20, bufferFold: 4, reducingAgentPercent: 5 } },

  { id: "moi", name: "MOI", nameZh: "感染复数 MOI", shortDescription: "Virus amount and Poisson infection probabilities", shortDescriptionZh: "计算病毒用量及泊松感染概率", category: "virology-microbiology", aliases: ["multiplicity of infection", "病毒感染"], plateAware: true, method: "Particles required = cells × MOI; Poisson probabilities use e^-MOI", methodZh: "所需感染单位 = 细胞数 × MOI；感染概率按e^-MOI计算", methodVersion: "moi-v1", fields: [numberField("cells", "Cells", "细胞数", 1_000_000, "cells"), numberField("desiredMoi", "Desired MOI", "目标MOI", 1), numberField("titer", "Virus titer", "病毒滴度", 100_000_000), selectField("titerUnit", "Titer unit", "滴度单位", "PFU/mL", [["PFU/mL", "PFU/mL", "PFU/mL"], ["IU/mL", "IU/mL", "IU/mL"], ["TU/mL", "TU/mL", "TU/mL"], ["VG/mL", "VG/mL", "VG/mL"]])], exampleInputs: { cells: 1_000_000, desiredMoi: 1, titer: 100_000_000, titerUnit: "PFU/mL" } },
  { id: "virus-titer", name: "Virus Titer", nameZh: "病毒滴度", shortDescription: "Plaque-assay PFU/mL or TCID50 estimate", shortDescriptionZh: "噬菌斑PFU/mL或TCID50估算", category: "virology-microbiology", aliases: ["PFU", "TCID50", "病毒滴度"], plateAware: false, method: "Plaque assay: plaques ÷ (dilution × inoculum mL); TCID50 remains a distinct mode", methodZh: "噬菌斑法：斑数 ÷（稀释度 × 接种体积mL）；TCID50保持独立模式", methodVersion: "virus-titer-v1", fields: [selectField("mode", "Method", "方法", "plaque", [["plaque", "Plaque assay", "噬菌斑法"], ["tcid50", "TCID50", "TCID50"]]), numberField("plaques", "Plaques", "噬菌斑数", 20, "integer", 1), numberField("dilution", "Dilution fraction", "稀释度", 0.000001), numberField("inoculumMl", "Inoculum volume", "接种体积", 0.1, "mL"), textField("tcidSeries", "TCID50 positive wells (dilution,positive,total)", "TCID50阳性孔（稀释度,阳性数,总孔数）", "0.001,8,8\n0.0001,6,8\n0.00001,2,8\n0.000001,0,8", true)], exampleInputs: { mode: "plaque", plaques: 20, dilution: 0.000001, inoculumMl: 0.1 } },

  { id: "unit-converter", name: "Unit Converter", nameZh: "单位换算", shortDescription: "Mass, volume, concentration, and temperature", shortDescriptionZh: "质量、体积、浓度和温度换算", category: "general", aliases: ["convert", "换算"], plateAware: false, method: "Dimension-specific SI conversion; temperature uses affine conversion", methodZh: "同维度SI单位换算；温度使用仿射换算", methodVersion: "unit-converter-v1", fields: [selectField("dimension", "Dimension", "换算类型", "volume", [["mass", "Mass", "质量"], ["volume", "Volume", "体积"], ["concentration", "Concentration", "浓度"], ["temperature", "Temperature", "温度"]]), numberField("value", "Value", "数值", 1), textField("fromUnit", "From unit", "原单位", "mL"), textField("toUnit", "To unit", "目标单位", "µL")], exampleInputs: { dimension: "volume", value: 1, fromUnit: "mL", toUnit: "µL" } },
  { id: "centrifuge", name: "Centrifuge", nameZh: "离心换算", shortDescription: "RPM and RCF conversion", shortDescriptionZh: "RPM与RCF相互换算", category: "general", aliases: ["g force", "转速", "离心力"], plateAware: false, method: "RCF = 1.118 × 10⁻⁵ × radius(cm) × RPM²", methodZh: "RCF = 1.118 × 10⁻⁵ × 半径(cm) × RPM²", methodVersion: "centrifuge-v1", fields: [selectField("mode", "Conversion", "换算方向", "rpm-to-rcf", [["rpm-to-rcf", "RPM to RCF", "RPM转RCF"], ["rcf-to-rpm", "RCF to RPM", "RCF转RPM"]]), numberField("rpm", "RPM", "转速", 10_000, "rpm"), numberField("rcf", "RCF", "相对离心力", 11_180, "×g"), numberField("radiusCm", "Rotor radius", "转子半径", 10, "cm")], exampleInputs: { mode: "rpm-to-rcf", rpm: 10_000, radiusCm: 10 } },
];

definitions.push(...newDefinitions);
const byId = new Map(definitions.map((definition) => [definition.id, definition]));
const round = (value: number) => value;
const num = (inputs: Record<string, unknown>, key: string, options: { min?: number; positive?: boolean } = {}) => {
  const value = parseScalar(inputs[key]);
  if (key === "dilution" && value > 1) throw new Error("稀释度不得超过1 / Dilution fraction must not exceed 1");
  if (["points", "levels"].includes(key) && value > 384) throw new Error("最多384个浓度点 / Maximum 384 concentration points");
  if (["wells", "plates", "replicates", "points", "levels", "reactions", "colonies", "plaques", "automaticCount", "manualAdjustment", "samples", "controls", "cells", "cellsPerWell", "vectorBp", "insertBp", "length"].includes(key) && !Number.isInteger(value)) throw new Error(`${key}: 必须是整数 / Must be an integer`);
  if (["viabilityPercent", "currentConfluency", "targetConfluency"].includes(key) && value > 100) throw new Error(`${key}: 不得超过100% / Must not exceed 100%`);
  if (!Number.isFinite(value) || (options.positive && value <= 0) || (options.min !== undefined && value < options.min)) throw new Error(`${key} must be a valid number${options.positive ? " greater than zero" : ""}.`);
  return value;
};
const str = (inputs: Record<string, unknown>, key: string) => String(inputs[key] ?? "").trim();
const parseNumbers = (value: unknown) => String(value ?? "").trim().split(/[\s,;]+/).map((item) => { const n = parseScalar(item); if (n < 0 || !Number.isInteger(n)) throw new Error("计数必须是非负整数 / Counts must be nonnegative integers"); return n; });
const parseRows = (value: unknown, columns = 2) => String(value ?? "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((line) => line.split(/[,\t]/).map((part) => part.trim())).map((row) => { if (row.length < columns || row.some(cell => !cell)) throw new Error("表格含不完整行 / Incomplete table row"); return row; });
const out = (key: string, label: string, labelZh: string, value: number | string, unit?: string): CalculatorOutput => ({ key, label, labelZh, value: typeof value === "number" ? round(value) : value, unit });
const finish = (definition: CalculatorDefinition, outputs: CalculatorOutput[], warnings: string[] = [], notes: string[] = [], table?: Array<Record<string, number | string>>): CalculatorResult => ({ calculatorId: definition.id, methodVersion: definition.methodVersion.replace(/-v1$/, "-v2"), outputs, outputMap: Object.fromEntries(outputs.map((item) => [item.key, item.value])), warnings, notes, table });
function linearRegression(rows: number[][]) {
  if (rows.length < 2 || rows.some(row => row.some(n => !Number.isFinite(n)))) throw new Error("At least two finite standard points are required.");
  const n = rows.length;
  const sx = rows.reduce((s, r) => s + r[0], 0), sy = rows.reduce((s, r) => s + r[1], 0);
  const sxx = rows.reduce((s, r) => s + r[0] ** 2, 0), sxy = rows.reduce((s, r) => s + r[0] * r[1], 0);
  const denominator = n * sxx - sx ** 2;
  if (Math.abs(denominator) < 1e-12) throw new Error("Standard concentrations must not all be identical.");
  const slope = (n * sxy - sx * sy) / denominator;
  const intercept = (sy - slope * sx) / n;
  const mean = sy / n;
  const ssTotal = rows.reduce((s, r) => s + (r[1] - mean) ** 2, 0);
  const ssResidual = rows.reduce((s, r) => s + (r[1] - (slope * r[0] + intercept)) ** 2, 0);
  return { slope, intercept, r2: ssTotal ? 1 - ssResidual / ssTotal : 1 };
}

type FourPl = { bottom: number; top: number; ec50: number; hill: number; r2: number; converged: boolean };
function fourPlFit(rows: number[][], responseDirection?: number): FourPl {
  if (rows.some(([x, y]) => !Number.isFinite(x) || x <= 0 || !Number.isFinite(y))) throw new Error("4PL要求完整的正浓度数据 / 4PL requires finite positive concentration data");
  const points = [...rows].sort((a, b) => a[0] - b[0]);
  if (points.length < 4) throw new Error("At least four positive-concentration points are required for 4PL fitting.");
  if(new Set(points.map(point=>point[0])).size<4)throw new Error("4PL至少需要四个不同浓度 / At least four distinct concentrations required");
  const ys = points.map((p) => p[1]);
  if(Math.max(...ys)===Math.min(...ys))throw new Error("反应值没有变化，无法拟合 / Constant response cannot identify a curve");
  if(responseDirection && (ys.at(-1)!-ys[0])*responseDirection<=0)throw new Error("Response data do not support the selected curve direction.");
  let params = [Math.min(...ys), Math.max(...ys), points[Math.floor(points.length / 2)][0], points.at(-1)![1] >= points[0][1] ? 1 : -1];
  const score = (p: number[]) => points.reduce((sum, [x, y]) => { const e = y - (p[0] + (p[1] - p[0]) / (1 + (p[2] / x) ** p[3])); return sum + e * e; }, 0);
  let step = [Math.max(1, Math.abs(params[1] - params[0]) * 0.1), Math.max(1, Math.abs(params[1] - params[0]) * 0.1), params[2] * 0.5, 0.5];
  let best = score(params);
  for (let iteration = 0; iteration < 800; iteration += 1) {
    let improved = false;
    for (let index = 0; index < 4; index += 1) for (const direction of [-1, 1]) {
      const candidate = [...params]; candidate[index] += step[index] * direction;
      if (candidate[1] <= candidate[0] || candidate[2] <= 0 || Math.abs(candidate[3]) <= 0.05 || Math.abs(candidate[3]) > 10 || (responseDirection !== undefined && candidate[3]*responseDirection<=0.05)) continue;
      const next = score(candidate);
      if (next < best) { params = candidate; best = next; improved = true; }
    }
    if (!improved) step = step.map((value) => value * 0.7);
    if (Math.max(...step) < 1e-8) break;
  }
  const mean = ys.reduce((a, b) => a + b, 0) / ys.length;
  const total = ys.reduce((s, y) => s + (y - mean) ** 2, 0);
  return { bottom: params[0], top: params[1], ec50: params[2], hill: params[3], converged: Math.max(...step) < 1e-8, r2: total ? 1 - best / total : 1 };
}

export function getCalculatorCatalog(): CalculatorDefinition[] { return definitions.map((definition) => enhanceDefinition({ ...definition, exampleInputs: { ...definition.exampleInputs }, fields: definition.fields.map((field) => ({ ...field })) })); }
export function getCalculatorDefinition(id: string): CalculatorDefinition {
  const definition = byId.get(id);
  if (!definition) throw new Error(`Unknown calculator: ${id}`);
  return enhanceDefinition({ ...definition, exampleInputs: { ...definition.exampleInputs }, fields: definition.fields.map((field) => ({ ...field })) });
}

function calculateInternal(request: CalculatorRequest): CalculatorResult {
  const definition = byId.get(request.calculatorId);
  if (!definition) throw new Error(`Unknown calculator: ${request.calculatorId}`);
  const i = { ...request.inputs };
  const current = getCalculatorDefinition(definition.id);
  if(["ic50-ec50","bradford-bca","elisa-4pl"].includes(definition.id)&&i.concentrationUnit==="")throw new Error("请选择浓度单位 / Choose concentration units");
  for (const field of current.fields) {
    if (!isFieldVisible(definition.id, field.key, i)) continue;
    if (field.type === "select" && i[field.key] !== undefined && !field.options?.some(option => option.value === i[field.key])) throw new Error(`${field.labelZh} / ${field.label}: 无效选项 / Invalid option`);
    if(["dilution","reagent-dosing","fold-dilution"].includes(definition.id)&&["stockConcentration","targetConcentration","initialConcentration"].includes(field.key))continue;
    const selectedUnit = i[`${field.key}Unit`];
    if (field.unit && typeof selectedUnit === "string") i[field.key] = convert(parseScalar(i[field.key]), selectedUnit, field.unit);
  }
  if(definition.id === "wb-loading" && i.bufferContainsReducingAgent === "yes")i.reducingAgentPercent=0;
  if (definition.id === "seeding" && i.plates === undefined) i.plates = 1;
  if (definition.id === "molarity" && (i.purityPercent === "" || i.purityPercent === undefined)) i.purityPercent = 100;

  switch (definition.id) {
    case "hemocytometer": { const counts = parseNumbers(i.counts); if (!counts.length) throw new Error("Enter at least one quadrant count."); const average = counts.reduce((a, b) => a + b, 0) / counts.length; const concentration = average * num(i, "dilutionFactor", { positive: true }) * (i.countRegion === "custom" ? 1000 / (num(i,"areaMm2",{positive:true}) * num(i,"depthMm",{positive:true})) : 10000); const viability = num(i, "viabilityPercent", { min: 0 }); return finish(definition, [out("averageCount", "Average count", "平均计数", average, "cells/quadrant"), out("concentrationCellsPerMl", "Cell concentration", "细胞浓度", concentration, "cells/mL"), out("viableCellsPerMl", "Viable-cell concentration", "活细胞浓度", concentration * viability / 100, "cells/mL")], viability > 100 ? ["Viability exceeds 100%. Check the input."] : []); }
    case "seeding": { const wells = num(i, "wells", { positive: true }) * num(i, "plates", { positive: true }); const factor = 1 + num(i, "overagePercent", { min: 0 }) / 100; const totalCells = num(i, "cellsPerWell", { positive: true }) * wells * factor; const finalMl = num(i, "volumePerWellUl", { positive: true }) * wells * factor / 1000; const stockMl = totalCells / num(i, "stockCellsPerMl", { positive: true }); if (stockMl > finalMl) throw new Error("Stock cell density is too low for the requested seeding density and volume."); return finish(definition, [out("totalCells", "Total cells", "总细胞数", totalCells, "cells"), out("stockVolumeMl", "Cell suspension", "细胞悬液", stockMl, "mL"), out("mediumVolumeMl", "Medium", "培养基", finalMl - stockMl, "mL"), out("finalVolumeMl", "Final suspension", "最终悬液", finalMl, "mL")]); }
    case "hydrogel": { const totalUl = num(i, "wells", { positive: true }) * num(i, "volumePerWellUl", { positive: true }); const totalCells = num(i, "targetCellsPerMl", { positive: true }) * totalUl / 1000; const cellStockUl = totalCells / num(i, "stockCellsPerMl", { positive: true }) * 1000; const parts = num(i, "gelParts", { positive: true }) + num(i, "suspensionParts", { positive: true }); const gelUl = totalUl * num(i, "gelParts", { positive: true }) / parts; const suspensionUl = totalUl - gelUl; if (cellStockUl > suspensionUl) throw new Error("细胞原液超过悬液分量 / Cell stock exceeds suspension fraction"); return finish(definition, [out("totalCells", "Total cells", "总细胞数", totalCells, "cells"), out("hydrogelUl", "Hydrogel", "水凝胶", gelUl, "µL"), out("cellStockUl", "Cell stock", "细胞原液", cellStockUl, "µL"), out("mediumUl", "Suspension medium", "悬液培养基", Math.max(0, suspensionUl - cellStockUl), "µL")], cellStockUl > suspensionUl ? ["The requested cells do not fit in the cell-suspension fraction; increase stock density or suspension fraction."] : []); }
    case "split": { const post = num(i, "currentConfluency", { positive: true }) / num(i, "splitRatio", { positive: true }) * (i.areaMode === "different" ? num(i,"sourceAreaCm2",{positive:true}) / num(i,"targetAreaCm2",{positive:true}) : 1); const target = num(i, "targetConfluency", { positive: true }); const hours = target <= post ? 0 : Math.log2(target / post) * num(i, "doublingTimeHours", { positive: true }); return finish(definition, [out("postSplitConfluency", "Post-split confluency", "传代后汇合度", post, "%"), out("hoursToTarget", "Estimated time to target", "预计达到目标时间", hours, "h"), out("daysToTarget", "Estimated days", "预计天数", hours / 24, "days")], [], ["This is an exponential-growth estimate; attachment lag and density effects are not modeled."]); }
    case "freezing": { const vials = Math.floor(num(i, "totalCells", { min: 0 }) / num(i, "cellsPerVial", { positive: true })); const total = vials * num(i, "volumePerVialMl", { positive: true }); const dmso = total * num(i, "dmsoPercent", { min: 0 }) / 100; const serum = total * num(i, "serumPercent", { min: 0 }) / 100; if (num(i, "dmsoPercent") + num(i, "serumPercent") > 100) throw new Error("配方比例超过100% / Recipe exceeds 100%"); return finish(definition, [out("vials", "Complete vials", "可冻存整管数", vials, "vials"), out("remainingCells", "Remaining cells", "剩余细胞", num(i, "totalCells") - vials * num(i, "cellsPerVial"), "cells"), out("totalMediumMl", "Total freezing medium", "冻存液总量", total, "mL"), out("dmsoMl", "DMSO", "DMSO", dmso, "mL"), out("serumMl", "Serum", "血清", serum, "mL"), out("baseMediumMl", "Base medium", "基础培养基", total - dmso - serum, "mL")], dmso + serum > total ? ["DMSO and serum percentages exceed 100% combined."] : []); }
    case "transfection": { const n = num(i, "wells", { positive: true }) * num(i, "replicates", { positive: true }); const f = 1 + num(i, "overagePercent", { min: 0 }) / 100; const dna = num(i, "dnaUgPerWell", { min: 0 }) * n * f; const reagent = dna * num(i, "reagentUlPerUg", { min: 0 }); const total = num(i, "complexVolumeUlPerWell", { positive: true }) * n * f; const dnaVolume = dna / num(i, "dnaConcentrationUgUl", { positive: true }); if (dnaVolume + reagent > total) throw new Error("核酸和试剂超过复合物体积 / DNA and reagent exceed complex volume");
      let tubeTable;
      if(i.complexMode==='two-tube'){const a=num(i,'tubeAVolumeUl',{positive:true})*n*f,b=total-a;if(a<dnaVolume||b<reagent)throw new Error('核酸或试剂超过对应管体积 / DNA or reagent exceeds its tube volume');tubeTable=[{tube:'A',component:'核酸原液 / DNA stock',volumeUl:dnaVolume},{tube:'A',component:'稀释液 / Diluent',volumeUl:a-dnaVolume},{tube:'B',component:'试剂 / Reagent',volumeUl:reagent},{tube:'B',component:'稀释液 / Diluent',volumeUl:b-reagent}];}
      return finish(definition, [out("dnaUg", "DNA", "DNA", dna, "µg"), out("reagentUl", "Transfection reagent", "转染试剂", reagent, "µL"), out("dnaVolumeUl", "DNA solution", "DNA原液", dnaVolume, "µL"), out("diluentUl", "Diluent", "稀释液", total - reagent - dnaVolume, "µL"), out("totalComplexUl", "Total complex", "复合物总量", total, "µL")], [], ["试剂、稀释液及混合顺序遵循所用产品说明 / Follow product-specific reagent, diluent and mixing instructions"], tubeTable); }
    case "kill-curve": { const points = num(i, "points", { positive: true }); if(points<2)throw new Error("至少两个浓度点 / At least two dose points required"); const min = num(i, "minimum", { min: 0 }), max = num(i, "maximum", { positive: true }); if (max < min) throw new Error("Maximum dose must be at least the minimum dose."); const doses = Array.from({ length: points }, (_, index) => str(i, "scale") === "log" ? min * (max / min) ** (index / Math.max(1, points - 1)) : min + (max - min) * index / Math.max(1, points - 1)); if (str(i,"scale")==="log" && min<=0) throw new Error("对数梯度最低浓度必须大于0 / Log minimum must be positive"); const stockUgMl = num(i, "stockConcentration", { positive: true }) * 1000; if(max>stockUgMl)throw new Error("目标浓度超过母液 / Target exceeds stock"); const volume = num(i, "volumePerWellMl", { positive: true }); const table = doses.map((dose, index) => ({ level: index + 1, doseUgMl: round(dose), stockToAddUl: round(dose * volume / stockUgMl * 1000) })); return finish(definition, [out("dosePoints", "Dose points", "浓度点数", points), out("highestStockAdditionUl", "Highest stock addition", "最高浓度母液加入量", table.at(-1)?.stockToAddUl ?? 0, "µL")], [], [], table); }
    case "viability": { const total = num(i, "totalCells", { min: 0 }), viability = num(i, "viabilityPercent", { min: 0 }); const live = total * viability / 100; const target = num(i, "targetLiveCellsPerMl", { positive: true }); return finish(definition, [out("liveCells", "Live cells", "活细胞", live, "cells"), out("deadCells", "Dead cells", "死细胞", total - live, "cells"), out("resuspensionVolumeMl", "Resuspension volume", "重悬体积", live / target, "mL")], viability > 100 ? ["Viability exceeds 100%."] : []); }
    case "od600": { const corrected = num(i, "od600", { min: 0 }) / num(i, "pathLengthCm", { positive: true }); const density = corrected * num(i, "cellsPerMlPerOd", { positive: true }); return finish(definition, [out("pathCorrectedOd", "Path-corrected OD600", "光程校正OD600", corrected), out("estimatedCellsPerMl", "Estimated density", "估算细胞浓度", density, "cells/mL"), out("estimatedTotalCells", "Estimated total cells", "估算总细胞数", density * num(i, "cultureVolumeMl", { min: 0 }), "cells")], [], ["The conversion factor is organism-, instrument-, and growth-condition-specific."]); }
    case "cfu": { const cfu = num(i, "colonies", { min: 0 }) / (num(i, "dilution", { positive: true }) * num(i, "platedVolumeMl", { positive: true })); const dna = num(i, "dnaUg", { min: 0 }); return finish(definition, [out("cfuPerMl", "CFU/mL", "CFU/mL", cfu, "CFU/mL"), out("log10CfuPerMl", "log10 CFU/mL", "log10 CFU/mL", cfu > 0 ? Math.log10(cfu) : "未检出 / Not detected"), dna > 0 ? out("transformantsPerUg", "Transformation efficiency", "转化效率", cfu / dna, "CFU/µg") : out("transformantsPerUg", "Transformation efficiency", "转化效率", "Not calculated")], num(i, "colonies", { min: 0 }) < 30 ? ["Low colony count may be statistically unstable."] : []); }
    case "colony-counter": { if(num(i,"automaticCount",{min:0})+num(i,"manualAdjustment")<0)throw new Error("计数不可为负 / Count cannot be negative"); const automatic = Math.round(num(i, "automaticCount", { min: 0 })); const adjustment = Math.round(num(i, "manualAdjustment")); return finish(definition, [out("automaticCount", "Automatic detections", "自动识别数", automatic), out("confirmedCount", "Human-confirmed count", "人工确认计数", Math.max(0, automatic + adjustment))], [], ["Uploaded images are transient and are not included in saved calculation records."]); }
    case "reagent-dosing": case "dilution": case "fold-dilution": {
      const mode = str(i, "mode") || (definition.id === "fold-dilution" ? "fold" : "final");
      // Old requests retain their documented fixed units. New requests always declare a mode.
      const modern = Boolean(i.mode);
      const volume = num(i, definition.id === "reagent-dosing" && !modern ? "finalVolumeMl" : "finalVolume", {positive:true});
      let stock = 1, target = 1, initial = 0;
      if (mode === "fold") { stock=num(i, modern?"stockFold":"fold",{positive:true});target=modern?num(i,"targetFold",{positive:true}):1; }
      else if (mode === "ratio") {stock=num(i,"ratio",{positive:true});if(stock<1)throw new Error("稀释分母至少为1 / Ratio denominator must be at least 1");}
      else if (mode === "parts") {target=num(i,"stockParts",{positive:true});stock=target+num(i,"diluentParts",{min:0});}
      else {
        stock=num(i,"stockConcentration",{positive:true});target=num(i,"targetConcentration",{min:0});
        if(modern) {
          const from=String(i.stockConcentrationUnit??'mM'),to=String(i.targetConcentrationUnit??'µM');
          const source=units[normalizeUnit(from)],targetUnit=units[normalizeUnit(to)];
          if(!source||!targetUnit||![source.dimension,targetUnit.dimension].every(d=>['mass-concentration','molar-concentration'].includes(d)))throw new Error('浓度单位无效 / Invalid concentration unit');
          if(source.dimension===targetUnit.dimension)stock=convert(stock,from,to);
          else {const mw=num(i,'molecularWeight',{positive:true});stock=stock*source.factor*(source.dimension==='molar-concentration'?mw:1/mw)/targetUnit.factor;}
        }
        else if(definition.id==='reagent-dosing') { if(num(i,"stockToTargetFactor")!==1000)throw new Error("旧倍率与单位冲突，请确认单位 / Legacy factor conflicts with units");stock*=1000; }
        if(mode==='add')initial=convert(num(i,"initialConcentration",{min:0}),String(i.initialConcentrationUnit??'µM'),String(i.targetConcentrationUnit??'µM'));
      }
      const plan=mode==='add'?addStock(stock,target,initial,volume):dilution(stock,target,volume);
      const unit=modern?'mL':definition.id==='dilution'?str(i,'volumeUnit'):'mL';
      return finish(current,[out('stockVolume','Take stock','取母液',plan.sample,unit),out('stockVolumeUl','Take stock','取母液',convert(plan.sample,unit,'µL'),'µL'),out('diluentVolume','Diluent','稀释液',mode==='add'?0:plan.diluent,unit),out('finalVolume','Final volume','最终体积',plan.final,unit)],[],['体积可加和近似 / Assumes additive volumes.']);
    }
    case "serial-dilution": {
      if(i.gradientMode==='linear'||i.gradientMode==='custom') {
        const start=i.gradientMode==='linear'?num(i,'startingConcentration',{min:0}):0;
        const count=i.gradientMode==='linear'?num(i,'levels',{positive:true}):1;if(count>384)throw new Error('最多384点 / Maximum 384 points');
        const targets=i.gradientMode==='custom'?String(i.customTargets??'').split(/\r?\n/).map(value=>parseScalar(value)):Array.from({length:count},(_,index)=>start+(num(i,'endingConcentration',{min:0})-start)*index/Math.max(1,count-1));
        const table=targets.map((concentration,index)=>{const plan=dilution(num(i,'sourceConcentration',{positive:true}),concentration,num(i,'totalVolumePerLevel',{positive:true}));return {tube:index+1,concentration,source:'母液 / Stock',takeUl:plan.sample,diluentUl:plan.diluent,mixedUl:plan.final,transferUl:0,remainingUl:plan.final};});
        return finish(current,[out('levels','Concentration points','浓度点数',table.length)],[],['并行配制；浓度µM，体积µL / Parallel preparation; µM and µL'],table);
      }
      const table=serialPlan(num(i,'startingConcentration',{positive:true}),num(i,'dilutionFactor',{positive:true}),num(i,'levels',{positive:true}),num(i,'totalVolumePerLevel',{positive:true}),i.volumeMode==='retained');
      if(i.firstSource==='stock'){const first=table[0];const plan=dilution(num(i,'sourceConcentration',{positive:true}),num(i,'startingConcentration',{positive:true}),first.mixedUl);first.source='母液 / Stock';first.takeUl=plan.sample;first.diluentUl=plan.diluent;}
      const required=i.requiredVolumeUl?num(i,'requiredVolumeUl',{min:0}):i.volumeMode==='retained'?num(i,'totalVolumePerLevel',{positive:true}):undefined;
      const planned=table.map(row=>({...row,requiredUl:required??'未设置 / Unspecified',sufficient:required===undefined?'未评估 / Not assessed':row.remainingUl>=required?'是 / Yes':'否 / No'}));
      return finish(current,[out('levels','Points including start','浓度点数（含起始点）',table.length),out('transferVolume','First transfer','首次转移',table[0].transferUl,'µL')],required!==undefined&&table.some(row=>row.remainingUl<required)?['部分管保留量不足，请调整规划 / Some tubes retain insufficient volume; revise the plan']:[],[i.firstSource==='stock'?'首管从更浓母液制备 / Prepare first tube from stock':'第一管为已备起始液 / First tube is prepared starting solution','对照单独设置；浓度µM，体积µL / Controls separate; concentrations µM, volumes µL'],planned);
    }
    case "molarity": {
      const mw = num(i, "molecularWeight", { positive: true });
      const mode = str(i, "mode");
      const purity = i.purityPercent === undefined ? 1 : num(i, "purityPercent", { positive: true }) / 100;
      if (purity > 1) throw new Error("纯度不得超过100% / Purity exceeds 100%");
      if (mode === "mass") return finish(definition, [out("massG", "Mass to weigh", "称量质量", mw * num(i, "concentrationM", { positive: true }) * num(i, "volumeL", { positive: true }) / purity, "g")], [], ["溶解后定容；纯度按质量分数 / Dissolve then bring to final volume; purity is a mass fraction."]);
      if (mode === "concentration") return finish(definition, [out("concentrationM", "Molarity", "摩尔浓度", num(i, "massG", { positive: true }) * purity / mw / num(i, "volumeL", { positive: true }), "M")]);
      if (mode !== "volume") throw new Error("请选择求解目标 / Select a solve mode");
      return finish(definition, [out("volumeL", "Required volume", "定容体积", num(i, "massG", { positive: true }) * purity / mw / num(i, "concentrationM", { positive: true }), "L")]);
    }
    case "percent-solution": { if (num(i,"percentage",{min:0})>100 && str(i,"type")!=='w/v')throw new Error('比例超过100% / Fraction exceeds 100%');
      if(str(i,'type')==='w/w'){const final=num(i,'targetMassG',{positive:true});const mass=final*num(i,'percentage',{min:0})/100;return finish(current,[out('soluteAmount','Solute mass','溶质质量',mass,'g'),out('otherMassG','Other components','其他组分合计',final-mass,'g')]);}
      const amount = num(i, "percentage", { min: 0 }) * num(i, "targetVolumeMl", { positive: true }) / 100; return finish(definition, [out("soluteAmount", str(i, "type") === "w/v" ? "Solute mass" : "Liquid solute", str(i, "type") === "w/v" ? "溶质质量" : "液体溶质体积", amount, str(i, "type") === "w/v" ? "g" : "mL"), out("targetVolumeMl", "Bring to final volume", "定容至", num(i, "targetVolumeMl", { positive: true }), "mL")]); }
    case "media-recipe": case "buffer-recipe": { const scale = num(i, "targetVolumeMl", { positive: true }) / num(i, "baseVolumeMl", { positive: true }); const source = Array.isArray(i.recipeRows) ? (i.recipeRows as Array<{name:string;amount:string;unit:string;inputMode?:string;stock?:string;target?:string;stockUnit?:string;targetUnit?:string}>).map(row=>{
        if(row.inputMode==='concentration'){if(i.recipeMode==='add')throw new Error('目标浓度模式需明确最终体积，请选择定容模式 / Target concentration requires final-volume mode');const plan=dilution(convert(parseScalar(row.stock),row.stockUnit??'mM',row.targetUnit??'µM'),parseScalar(row.target),num(i,'targetVolumeMl',{positive:true}));return[row.name,String(plan.sample/scale),'mL'];}
        return [row.name,row.amount,row.unit];
      }) : parseRows(i.components, 3); const table = source.map(([name, amount, unit]) => ({ component: name, amount: parseScalar(amount) * scale, unit }));
      if(table.some(row=>!row.component.trim()||row.amount<0))throw new Error('组分名称或用量无效 / Invalid component name or amount');
      const liquidMl=table.filter(row=>['mL','µL','L'].includes(row.unit)).reduce((sum,row)=>sum+convert(row.amount,row.unit,'mL'),0);
      if(i.recipeMode==='final'&&liquidMl>num(i,'targetVolumeMl'))throw new Error('液体组分超过最终体积 / Liquid components exceed final volume');
      if(i.recipeMode==='final')table.push({component:'溶解后定容至 / Dissolve then bring to',amount:num(i,'targetVolumeMl'),unit:'mL'}); if (!table.length || table.some((row) => !Number.isFinite(Number(row.amount)))) throw new Error("Enter components as name, amount, unit."); return finish(definition, [out("scaleFactor", "Scale factor", "缩放倍数", scale), out("componentCount", "Components", "组分数", table.length)], [], [], table); }
    case "ic50-ec50": { const rows = parseRows(i.points).map((row) => [Number(row[0]), Number(row[1])]); const fit = fourPlFit(rows,str(i,"mode")==="inhibition"?-1:1); return finish(definition, [out("midpoint", "Relative 4PL midpoint", "相对4PL曲线中点", fit.ec50), out("bottom", "Bottom", "下平台", fit.bottom), out("top", "Top", "上平台", fit.top), out("hillSlope", "Hill slope", "Hill斜率", fit.hill), out("rSquared", "R²", "R²", fit.r2), out('converged','Converged','数值收敛',fit.converged?'Yes / 是':'No / 否')], fit.r2 < 0.9 || !fit.converged ? ["拟合需复核：R²不代表模型可靠性 / Review fit; R² alone is not validation"] : [], ['相对中点不是所有定义的绝对50%效应；检查平台和量程 / Relative midpoint is not necessarily absolute 50% effect; inspect plateaus and range.'], rows.map(([x,y])=>({concentration:x,observed:y,fitted:fit.bottom+(fit.top-fit.bottom)/(1+(fit.ec50/x)**fit.hill)}))); }
    case "master-mix": {
      if(Array.isArray(i.groups)){
        const groups=i.groups as Array<{name:string;reactions:string;rows:MixRow[]}>;
        if(!groups.length||groups.some(group=>!group.name.trim())||new Set(groups.map(group=>group.name.trim())).size!==groups.length)throw new Error('配液组名称缺失或重复 / Missing or duplicate mix group name');
        const plans=groups.map(group=>{const reactions=parseScalar(group.reactions);return {group,plan:mixPlan(group.rows,reactions,reactions*num(i,'overagePercent',{min:0})/100,num(i,'reactionVolumeUl',{positive:true}))};});
        return finish(current,[out('groups','Separate mix groups','独立配液组',groups.length),out('totalMasterMixUl','Total across separate groups','各组预混总量（分别配制）',plans.reduce((sum,item)=>sum+item.plan.total,0),'µL')],[],['不同组分别配制，不合并模板 / Prepare each group separately; never pool templates'],plans.flatMap(({group,plan})=>plan.table.map(row=>({...row,group:group.name}))));
      }
      const reactions=i.samples!==undefined?num(i,'samples',{positive:true})*num(i,'replicates',{positive:true})+num(i,'controls',{min:0}):num(i,'reactions',{positive:true});
      if(!Number.isInteger(reactions))throw new Error('反应数必须是整数 / Reaction count must be an integer');
      const rows=Array.isArray(i.rows)?i.rows as MixRow[]:parseRows(i.components).map(([name,volume])=>({name,volume,premix:true}));
      const final=i.reactionVolumeUl!==undefined?num(i,'reactionVolumeUl',{positive:true}):rows.reduce((s,row)=>s+parseScalar(row.volume),0);
      const extra=reactions*num(i,'overagePercent',{min:0})/100;
      const plan=mixPlan(rows,reactions,extra,final);
      return finish(current,[out('actualReactions','Actual reactions','实际反应数',reactions),out('preparedReactions','Premix equivalents','预混反应当量',reactions+extra),out('totalMasterMixUl','Prepare premix','配制预混液',plan.total,'µL'),out('dispenseUl','Premix per reaction','每反应分装预混液',final-plan.separate,'µL'),out('separateUl','Separate sample per reaction','每反应独立加样',plan.separate,'µL')],[],[],plan.table);
    }
    case "resuspension": {
      const mode=str(i,'mode');let volume;
      if(mode==='amount')volume=num(i,'amount',{positive:true})*1e-9/(num(i,'targetMolar',{positive:true})*1e-6);
      else if(mode==='mass')volume=num(i,'mass',{positive:true})*1e-3/num(i,'targetMass',{positive:true});
      else volume=num(i,'mass',{positive:true})*1e-3/num(i,'molecularWeight',{positive:true})/(num(i,'targetMolar',{positive:true})*1e-6);
      return finish(current,[out('finalVolumeUl','Final solution volume','最终溶液体积',volume*1e6,'µL')],[],['以COA量或分子量为依据；溶剂及复溶操作遵循产品说明 / Use COA amount or MW and product instructions.']);
    }
    case "normalization": {
      if(!Array.isArray(i.samples)||!i.samples.length)throw new Error('请输入样本 / Enter samples');
      const table=batchPlan(i.samples as SampleRow[],num(i,'targetConcentration',{min:0}),num(i,'finalVolume',{positive:true}));
      return finish(current,[out('validRows','Valid samples','有效样本',table.filter(row=>typeof row.sampleUl==='number').length)],[],['浓度单位ng/µL，体积单位µL；无效行不提供移液量 / Concentrations ng/µL, volumes µL; invalid rows have no volumes.'],table);
    }
    case "ligation": { const insert = num(i, "vectorNg", { positive: true }) * num(i, "insertBp", { positive: true }) / num(i, "vectorBp", { positive: true }) * num(i, "molarRatio", { positive: true }); return finish(definition, [out("insertNg", "Insert DNA required", "所需插入片段DNA", insert, "ng"), out("vectorNg", "Vector DNA", "载体DNA", num(i, "vectorNg", { positive: true }), "ng")]); }
    case "tm": { const sequence = str(i, "sequence").toUpperCase(); if (!/^[ACGT]+$/.test(sequence) || sequence.length < 4) throw new Error("Enter a DNA primer sequence containing A, C, G, and T."); const gc = [...sequence].filter((base) => base === "G" || base === "C").length; const saltM = num(i, "sodiumMm", { positive: true }) / 1000; const tm = sequence.length < 14 ? 2 * (sequence.length - gc) + 4 * gc : 64.9 + 41 * (gc - 16.4) / sequence.length + 16.6 * Math.log10(saltM); return finish(definition, [out("length", "Primer length", "引物长度", sequence.length, "nt"), out("gcPercent", "GC content", "GC含量", gc / sequence.length * 100, "%"), out("tmC", "Estimated Tm", "估算Tm", tm, "°C")], [], ["This screening estimate does not model Mg²⁺, dNTPs, mismatches, or nearest-neighbor thermodynamics."]); }
    case "dna-rna-conversion": { const factor = str(i, "type") === "dsDNA" ? 660 : str(i, "type") === "ssDNA" ? 330 : 340; const mw = num(i, "length", { positive: true }) * factor; const grams = num(i, "massUg", { min: 0 }) * 1e-6; const moles = grams / mw; const molecules = moles * 6.02214076e23; return finish(definition, [out("molecularWeight", "Estimated molecular weight", "估算分子量", mw, "g/mol"), out("concentrationNm", "Estimated molar concentration", "估算摩尔浓度", moles / (num(i,"volumeUl",{positive:true}) * 1e-6) * 1e9, "nM"), out("moles", "Amount", "物质的量", moles, "mol"), out("molecules", "Molecules", "分子数", molecules, "molecules"), out("concentrationUgUl", "Mass concentration", "质量浓度", num(i, "massUg", { min: 0 }) / num(i, "volumeUl", { positive: true }), "µg/µL")]); }
    case "bradford-bca": { const rows = parseRows(i.standards).map((row) => [Number(row[0]), Number(row[1])]); const fit = linearRegression(rows); if (fit.slope <= 0) throw new Error("The standard curve slope must be positive."); const concentration = (num(i, "sampleAbsorbance", { min: 0 }) - fit.intercept) / fit.slope * num(i, "dilutionFactor", { positive: true }); if(concentration<0)throw new Error("样品信号低于可反算范围 / Sample signal is below the invertible range"); const minX = Math.min(...rows.map((r) => r[0])), maxX = Math.max(...rows.map((r) => r[0])); return finish(definition, [out("slope", "Slope", "斜率", fit.slope), out("intercept", "Intercept", "截距", fit.intercept), out("rSquared", "R²", "R²", fit.r2), out("sampleConcentration", "Sample concentration", "样品浓度", concentration)], concentration / num(i, "dilutionFactor", { positive: true }) < minX || concentration / num(i, "dilutionFactor", { positive: true }) > maxX ? ["Back-calculated concentration is outside the standard range."] : [], ["仅在已验证线性量程内使用 / Use only within the validated linear range"], rows.map(([x,y])=>({concentration:x,observed:y,fitted:fit.intercept+fit.slope*x}))); }
    case "elisa-4pl": { const rows = parseRows(i.standards).map((row) => [Number(row[0]), Number(row[1])]); const fit = fourPlFit(rows); const signal = num(i, "sampleSignal", { min: 0 }); const ratio = (fit.top - fit.bottom) / (signal - fit.bottom) - 1; const concentration = ratio > 0 ? fit.ec50 / ratio ** (1 / fit.hill) * num(i, "dilutionFactor", { positive: true }) : NaN; if (!Number.isFinite(concentration)) throw new Error("Sample signal cannot be inverted within the fitted 4PL range."); return finish(definition, [out("sampleConcentration", "Sample concentration", "样品浓度", concentration), out("ec50", "Curve midpoint", "曲线中点", fit.ec50), out("hillSlope", "Hill slope", "Hill斜率", fit.hill), out("rSquared", "R²", "R²", fit.r2),out('bottom','Bottom','下平台',fit.bottom),out('top','Top','上平台',fit.top),out('converged','Converged','数值收敛',fit.converged?'Yes / 是':'No / 否')], concentration/num(i,'dilutionFactor',{positive:true})<Math.min(...rows.map(row=>row[0]))||concentration/num(i,'dilutionFactor',{positive:true})>Math.max(...rows.map(row=>row[0]))?['稀释样本反算浓度超出标准范围 / Diluted sample is outside the standard range']:[],['检查标准曲线覆盖范围、平台与收敛 / Inspect range, plateaus and convergence'],rows.map(([x,y])=>({concentration:x,observed:y,fitted:fit.bottom+(fit.top-fit.bottom)/(1+(fit.ec50/x)**fit.hill)}))); }
    case "wb-loading": {
      const inclusion=str(i,'bufferContainsReducingAgent');
      if(!['yes','no'].includes(inclusion))throw new Error('请确认Buffer是否含还原剂 / Confirm whether buffer contains reducing agent');
      const final=num(i,'finalLoadingVolumeUl',{positive:true});
      const mode=inclusion==='yes'?'included':str(i,'reducingMode')||'volume-fraction';
      const percent=inclusion==='yes'?0:num(i,'reducingAgentPercent',{min:0});
      let reducing=final*percent/100;
      if(mode==='target-concentration') {const stock=num(i,'reducingStockPercent',{positive:true});if(percent>stock||stock>100)throw new Error('还原剂浓度不可行 / Invalid reducing-agent concentration');reducing=final*percent/stock;}
      if(reducing>final)throw new Error('还原剂超过总体积 / Reducing agent exceeds total volume');
      const name=inclusion==='yes'?'已包含于Buffer / Included in buffer':str(i,'reducingAgentName') || (reducing===0?'无独立还原剂 / None':'');
      if(!name)throw new Error('请注明还原剂原液名称 / Name the reducing-agent stock');
      const definition=mode==='included'?'已包含于Buffer / Included in buffer':mode==='target-concentration'?`目标 ${percent}%；原液 ${i.reducingStockPercent}% / Target and stock concentrations`:`最终体积的 ${percent}% v/v 原液；不代表有效成分终浓度 / Fraction of final volume, not active concentration`;
      const rows=Array.isArray(i.samples)?i.samples as SampleRow[]:[{id:'Sample',concentration:String(i.sampleConcentrationUgUl??''),available:''}];
      const table=wbPlan(rows,num(i,'targetProteinUg',{positive:true}),final,num(i,'bufferFold',{positive:true}),{name,mode:mode as 'included'|'volume-fraction'|'target-concentration',volumeUl:reducing,definition});
      if(!Array.isArray(i.samples)&&typeof table[0]?.sampleUl!=='number')throw new Error(table[0]?.status??'Invalid WB sample');
      const row=table[0];
      const outputs=Array.isArray(i.samples)?[out('validRows','Valid samples','有效样本',table.filter(r=>typeof r.sampleUl==='number').length)]:[out('sampleUl','Sample','样品',row.sampleUl,'µL'),out('loadingBufferUl','Loading buffer','Loading Buffer',row.bufferUl,'µL'),out('reducingAgentUl',name,name,row.reducingAgentUl,'µL'),out('waterUl','Water','水',row.diluentUl,'µL')];
      return finish(current,outputs,[],[definition],table);
    }
    case "moi": { if(str(i,"titerUnit")==="VG/mL")throw new Error("VG不是功能性滴度，请提供功能性滴度 / VG is not a functional titer"); const moi = num(i, "desiredMoi", { min: 0 }), units = num(i, "cells", { positive: true }) * moi; const volume = units / num(i, "titer", { positive: true }) * 1000; const p0 = Math.exp(-moi); const p1 = moi * p0; return finish(definition, [out("virusVolumeUl", "Virus volume", "病毒体积", volume, "µL"), out("probabilityUninfectedPercent", "Uninfected", "未感染概率", p0 * 100, "%"), out("probabilityExactlyOnePercent", "Exactly one event", "恰好一次感染概率", p1 * 100, "%"), out("probabilityAtLeastOnePercent", "At least one event", "至少一次感染概率", (1 - p0) * 100, "%")], [], [`理论泊松模型：独立、均一事件假设，不代表确定感染率 / Theoretical Poisson model: independent homogeneous events. ${str(i, "titerUnit")}; PFU, IU, TU, TCID50, VG are not equivalent.`]); }
    case "virus-titer": { if (str(i, "mode") === "plaque") { const titer = num(i, "plaques", { min: 0 }) / (num(i, "dilution", { positive: true }) * num(i, "inoculumMl", { positive: true })); return finish(definition, [out("pfuPerMl", "Virus titer", "病毒滴度", titer, "PFU/mL"), out("log10PfuPerMl", "log10 titer", "log10滴度", titer > 0 ? Math.log10(titer) : "未检出 / Not detected")]); } const rows = parseRows(i.tcidSeries, 3).map((row) => [Number(row[0]), Number(row[1]), Number(row[2])]); if (rows.length < 2) throw new Error("Enter at least two TCID50 dilution rows."); if(rows.some(([d,p,t])=>!Number.isFinite(d)||d<=0||d>1||!Number.isInteger(p)||!Number.isInteger(t)||p<0||t<=0||p>t))throw new Error("终点行无效 / Invalid endpoint row"); const crossing = rows.find(([, positive, total]) => positive / total <= 0.5); if(!crossing)throw new Error("未跨越50%终点 / No 50% crossing observed"); return finish(definition, [out("approximateTcid50Dilution", "Approximate 50% endpoint dilution", "近似50%终点稀释度", crossing[0])], ["This quick endpoint identifies the first dilution at or below 50%; use a protocol-specific Reed–Muench or Spearman–Kärber workflow for formal reporting."]); }
    case "unit-converter": return finish(definition, [out("convertedValue", "Converted value", "换算结果", convert(num(i, "value"), str(i, "fromUnit"), str(i, "toUnit")), str(i, "toUnit"))]);
    case "centrifuge": { const radius = num(i, "radiusCm", { positive: true }); if (str(i, "mode") === "rcf-to-rpm") return finish(definition, [out("rpm", "RPM", "转速", Math.sqrt(num(i, "rcf", { min: 0 }) / (1.118e-5 * radius)), "rpm")]); return finish(definition, [out("rcf", "RCF", "相对离心力", 1.118e-5 * radius * num(i, "rpm", { min: 0 }) ** 2, "×g")]); }
    default: throw new Error(`Calculator implementation missing: ${definition.id}`);
  }
}

/** One result contract powers rendering, copying, history, and experiment writes. */
export function calculate(request: CalculatorRequest): CalculatorResult {
  const result=applyPipettingOptions(calculateInternal(request),request.inputs);
  if(['ic50-ec50','bradford-bca','elisa-4pl'].includes(request.calculatorId))result.outputs=result.outputs.map(output=>['midpoint','ec50','sampleConcentration'].includes(output.key)?{...output,unit:String(request.inputs.concentrationUnit??'未注明 / Unspecified')}:output);
  if(request.calculatorId==="dna-rna-conversion")result.notes.push("长度估算系数：dsDNA 660、ssDNA 330、RNA 340 g/mol/bp或nt。修饰核酸优先使用COA分子量 / Length-based estimate; prefer COA MW for modified nucleic acids.");
  const definition=getCalculatorDefinition(request.calculatorId);
  const normalizedInputs:Record<string,unknown>={};
  for(const field of definition.fields){
    if(!isFieldVisible(definition.id,field.key,request.inputs)||request.inputs[field.key]===undefined||request.inputs[field.key]==='')continue;
    normalizedInputs[field.key]=field.unit&&units[normalizeUnit(field.unit)]?{value:parseScalar(request.inputs[field.key])*units[normalizeUnit(String(request.inputs[`${field.key}Unit`]??field.unit))].factor+(units[normalizeUnit(String(request.inputs[`${field.key}Unit`]??field.unit))].offset??0),dimension:units[normalizeUnit(String(request.inputs[`${field.key}Unit`]??field.unit))].dimension,unit:canonicalUnits[units[normalizeUnit(String(request.inputs[`${field.key}Unit`]??field.unit))].dimension]??field.unit,sourceUnit:String(request.inputs[`${field.key}Unit`]??field.unit)}:request.inputs[field.key];
  }
  if(result.outputs.some(output=>typeof output.value==='number'&&!Number.isFinite(output.value)))throw new Error('计算溢出或条件无效 / Numerical overflow or invalid conditions');
  return {...result,displayUnits:validateDisplayUnits(result,request.inputs.__displayUnits),schemaVersion:2,status:['split','od600','tm','dna-rna-conversion','moi','virus-titer','ic50-ec50','elisa-4pl','bradford-bca'].includes(request.calculatorId)?'estimate':result.table?.some(row=>typeof row.status==='string'&&row.status!=='有效 / Valid')?'partial':'valid',mode:String(request.inputs.mode??'default'),rawInputs:structuredClone(request.inputs),normalizedInputs};
}
