import {enhanceDefinition,newDefinitions} from "./task-definitions";
export type CalculatorCategory = "cell-culture" | "solutions" | "molecular-biology" | "virology-microbiology" | "general" | "protein";

export type CalculatorField = {
  key: string;
  label: string;
  labelZh: string;
  type: "number" | "text" | "textarea" | "select";
  unit?: string;
  placeholder?: string;
  defaultValue?: string | number;
  min?: number;
  step?: number;
  options?: Array<{ value: string; label: string; labelZh: string }>;
};

export type CalculatorDefinition = {
  id: string;
  name: string;
  nameZh: string;
  shortDescription: string;
  shortDescriptionZh: string;
  category: CalculatorCategory;
  aliases: string[];
  plateAware: boolean;
  method: string;
  methodZh: string;
  methodVersion: string;
  fields: CalculatorField[];
  exampleInputs: Record<string, unknown>;
};

const numberField = (key: string, label: string, labelZh: string, defaultValue: number, unit?: string, min = 0): CalculatorField => ({ key, label, labelZh, type: "number", defaultValue, unit, min, step: "integer" === unit ? 1 : 0.01 });
const textField = (key: string, label: string, labelZh: string, defaultValue: string, textarea = false): CalculatorField => ({ key, label, labelZh, type: textarea ? "textarea" : "text", defaultValue });
const selectField = (key: string, label: string, labelZh: string, defaultValue: string, options: Array<[string, string, string]>): CalculatorField => ({ key, label, labelZh, type: "select", defaultValue, options: options.map(([value, en, zh]) => ({ value, label: en, labelZh: zh })) });

const definitions: CalculatorDefinition[] = [
  { id: "hemocytometer", name: "Hemocytometer", nameZh: "血球计数板", shortDescription: "Cell concentration from counted quadrants", shortDescriptionZh: "根据计数区和稀释倍数计算细胞浓度", category: "cell-culture", aliases: ["cell count", "细胞计数"], plateAware: false, method: "Average count × dilution factor × 10⁴ cells/mL", methodZh: "平均计数 × 稀释倍数 × 10⁴ cells/mL", methodVersion: "hemocytometer-v1", fields: [textField("counts", "Quadrant counts", "计数区细胞数", "13,11,14,17"), numberField("dilutionFactor", "Dilution factor", "稀释倍数", 2), numberField("viabilityPercent", "Viability", "细胞活率", 90, "%")], exampleInputs: { counts: "13,11,14,17", dilutionFactor: 3, viabilityPercent: 90 } },
  { id: "seeding", name: "Seeding", nameZh: "细胞铺板", shortDescription: "Cells and suspension volume per well", shortDescriptionZh: "计算每孔细胞量及整批细胞悬液", category: "cell-culture", aliases: ["plating", "铺板"], plateAware: true, method: "Cell requirement and volume balance with overage applied once", methodZh: "按总孔数计算细胞需求并仅统一加入一次余量", methodVersion: "seeding-v1", fields: [numberField("stockCellsPerMl", "Stock cell density", "细胞原液浓度", 1_000_000, "cells/mL"), numberField("wells", "Wells", "孔数", 24, "integer", 1), numberField("plates", "Plates", "板数", 1, "integer", 1), numberField("cellsPerWell", "Cells per well", "每孔细胞数", 50_000, "cells"), numberField("volumePerWellUl", "Volume per well", "每孔体积", 500, "µL"), numberField("overagePercent", "Overage", "额外余量", 10, "%")], exampleInputs: { stockCellsPerMl: 1_000_000, wells: 24, plates: 1, cellsPerWell: 50_000, volumePerWellUl: 500, overagePercent: 10 } },
  { id: "hydrogel", name: "Hydrogel", nameZh: "水凝胶培养", shortDescription: "3D cell and hydrogel mixture", shortDescriptionZh: "计算3D培养的细胞与水凝胶混合体系", category: "cell-culture", aliases: ["3D culture", "Matrigel", "三维培养"], plateAware: true, method: "Target cells plus gel-to-cell-suspension volume ratio", methodZh: "依据目标细胞量及凝胶与细胞悬液体积比计算", methodVersion: "hydrogel-v1", fields: [numberField("stockCellsPerMl", "Stock cell density", "细胞原液浓度", 2_000_000, "cells/mL"), numberField("targetCellsPerMl", "Target density", "目标细胞密度", 1_000_000, "cells/mL"), numberField("wells", "Wells", "孔数", 10, "integer", 1), numberField("volumePerWellUl", "Volume per well", "每孔体积", 100, "µL"), numberField("gelParts", "Hydrogel parts", "水凝胶份数", 4), numberField("suspensionParts", "Cell suspension parts", "细胞悬液份数", 1)], exampleInputs: { stockCellsPerMl: 10_000_000, targetCellsPerMl: 1_000_000, wells: 10, volumePerWellUl: 100, gelParts: 4, suspensionParts: 1 } },
  { id: "split", name: "Split Calculator", nameZh: "细胞传代", shortDescription: "Post-split confluency and readiness estimate", shortDescriptionZh: "估算传代后汇合度及达到目标的时间", category: "cell-culture", aliases: ["passage", "传代", "confluency"], plateAware: false, method: "Exponential growth estimate from confluency, split ratio, and doubling time", methodZh: "根据汇合度、传代比例和倍增时间进行指数生长估算", methodVersion: "split-v1", fields: [numberField("currentConfluency", "Current confluency", "当前汇合度", 90, "%"), numberField("splitRatio", "Split denominator", "传代比例分母", 4), numberField("targetConfluency", "Target confluency", "目标汇合度", 80, "%"), numberField("doublingTimeHours", "Doubling time", "倍增时间", 24, "h")], exampleInputs: { currentConfluency: 90, splitRatio: 4, targetConfluency: 80, doublingTimeHours: 24 } },
  { id: "freezing", name: "Freezing", nameZh: "细胞冻存", shortDescription: "Cryovials and freezing-medium composition", shortDescriptionZh: "计算冻存管数和冻存液组成", category: "cell-culture", aliases: ["cryopreservation", "冻存"], plateAware: false, method: "Available cells divided by target cells per vial; medium components by percentage", methodZh: "按每管目标细胞数及冻存液百分比计算", methodVersion: "freezing-v1", fields: [numberField("totalCells", "Total cells", "总细胞数", 10_000_000, "cells"), numberField("cellsPerVial", "Cells per vial", "每管细胞数", 1_000_000, "cells"), numberField("volumePerVialMl", "Volume per vial", "每管体积", 1, "mL"), numberField("dmsoPercent", "DMSO", "DMSO比例", 10, "%"), numberField("serumPercent", "Serum", "血清比例", 20, "%")], exampleInputs: { totalCells: 10_000_000, cellsPerVial: 1_000_000, volumePerVialMl: 1, dmsoPercent: 10, serumPercent: 20 } },
  { id: "transfection", name: "Transfection", nameZh: "转染体系", shortDescription: "Nucleic acid and reagent master mix", shortDescriptionZh: "计算核酸、转染试剂和稀释液", category: "cell-culture", aliases: ["lipofection", "siRNA", "质粒转染"], plateAware: true, method: "Per-well nucleic acid and reagent ratio scaled by wells, replicates, and overage", methodZh: "按每孔核酸量、试剂比例、孔数及余量计算", methodVersion: "transfection-v1", fields: [numberField("wells", "Wells", "孔数", 6, "integer", 1), numberField("replicates", "Replicates", "重复数", 1, "integer", 1), numberField("dnaUgPerWell", "DNA per well", "每孔DNA", 2, "µg"), numberField("dnaConcentrationUgUl", "DNA stock concentration", "DNA母液浓度", 1, "µg/µL"), numberField("reagentUlPerUg", "Reagent per µg DNA", "每µg DNA试剂量", 3, "µL/µg"), numberField("complexVolumeUlPerWell", "Complex volume per well", "每孔复合物体积", 125, "µL"), numberField("overagePercent", "Overage", "额外余量", 10, "%")], exampleInputs: { wells: 6, replicates: 1, dnaUgPerWell: 2, dnaConcentrationUgUl: 1, reagentUlPerUg: 3, complexVolumeUlPerWell: 125, overagePercent: 10 } },
  { id: "kill-curve", name: "Kill Curve", nameZh: "杀灭曲线", shortDescription: "Antibiotic dose series and stock additions", shortDescriptionZh: "生成抗生素浓度梯度及母液加入量", category: "cell-culture", aliases: ["antibiotic", "筛选浓度"], plateAware: true, method: "Linear or logarithmic dose series followed by C1V1=C2V2", methodZh: "生成线性或对数浓度序列后按C1V1=C2V2计算", methodVersion: "kill-curve-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10, "mg/mL"), numberField("minimum", "Minimum dose", "最低浓度", 0.5, "µg/mL"), numberField("maximum", "Maximum dose", "最高浓度", 10, "µg/mL"), numberField("points", "Dose points", "浓度点数", 8, "integer", 2), numberField("volumePerWellMl", "Volume per well", "每孔体积", 0.5, "mL"), selectField("scale", "Scale", "梯度方式", "linear", [["linear", "Linear", "线性"], ["log", "Logarithmic", "对数"]])], exampleInputs: { stockConcentration: 10, minimum: 0.5, maximum: 10, points: 8, volumePerWellMl: 0.5, scale: "linear" } },
  { id: "viability", name: "Viability", nameZh: "细胞活率", shortDescription: "Live/dead cells and resuspension", shortDescriptionZh: "计算活细胞、死细胞及重悬体积", category: "cell-culture", aliases: ["trypan blue", "台盼蓝"], plateAware: false, method: "Total cells partitioned by viability; optional live-cell target density", methodZh: "按活率拆分活/死细胞，并可按目标活细胞浓度重悬", methodVersion: "viability-v1", fields: [numberField("totalCells", "Total cells", "总细胞数", 200_000, "cells"), numberField("viabilityPercent", "Viability", "细胞活率", 90, "%"), numberField("targetLiveCellsPerMl", "Target live-cell density", "目标活细胞浓度", 100_000, "cells/mL")], exampleInputs: { totalCells: 200_000, viabilityPercent: 90, targetLiveCellsPerMl: 100_000 } },
  { id: "od600", name: "OD600", nameZh: "OD600菌液浓度", shortDescription: "Optical density to estimated cell density", shortDescriptionZh: "根据OD600估算微生物浓度", category: "cell-culture", aliases: ["bacterial density", "菌液浓度"], plateAware: false, method: "OD600 corrected for path length and multiplied by an explicit empirical factor", methodZh: "按光程校正OD600后乘以明确的经验换算因子", methodVersion: "od600-v1", fields: [numberField("od600", "OD600", "OD600读数", 0.8), numberField("pathLengthCm", "Path length", "光程", 1, "cm"), numberField("cellsPerMlPerOd", "Empirical factor", "经验换算因子", 800_000_000, "cells/mL/OD"), numberField("cultureVolumeMl", "Culture volume", "培养体积", 5, "mL")], exampleInputs: { od600: 0.8, pathLengthCm: 1, cellsPerMlPerOd: 800_000_000, cultureVolumeMl: 5 } },
  { id: "cfu", name: "CFU/mL", nameZh: "菌落形成单位", shortDescription: "Colony-forming units from plated dilution", shortDescriptionZh: "根据菌落数、稀释倍数和涂板体积计算CFU/mL", category: "cell-culture", aliases: ["colony forming units", "菌落计数"], plateAware: false, method: "CFU/mL = colonies ÷ (dilution × plated volume in mL)", methodZh: "CFU/mL = 菌落数 ÷（稀释度 × 涂板体积mL）", methodVersion: "cfu-v1", fields: [numberField("colonies", "Colonies", "菌落数", 120, "integer", 1), numberField("dilution", "Dilution fraction", "稀释度", 0.000001), numberField("platedVolumeMl", "Plated volume", "涂板体积", 0.1, "mL"), numberField("dnaUg", "DNA amount (optional)", "DNA用量（可选）", 0, "µg")], exampleInputs: { colonies: 120, dilution: 0.000001, platedVolumeMl: 0.1, dnaUg: 2 } },
  { id: "colony-counter", name: "Colony & Plaque Counter", nameZh: "菌落与噬菌斑辅助计数", shortDescription: "Reviewable image-assisted counting", shortDescriptionZh: "可人工复核的图像辅助计数", category: "cell-culture", aliases: ["photo count", "菌落图片", "plaque counter"], plateAware: false, method: "Browser-local connected-region detection followed by mandatory human confirmation", methodZh: "浏览器本地连通区域识别，并要求人工确认", methodVersion: "colony-counter-v1", fields: [numberField("automaticCount", "Automatic count", "自动识别数", 42, "integer"), numberField("manualAdjustment", "Manual adjustment", "人工增减", 0, "integer", -100000)], exampleInputs: { automaticCount: 42, manualAdjustment: -2 } },

  { id: "reagent-dosing", name: "Reagent Dosing", nameZh: "试剂加药", shortDescription: "Stock addition to a desired final concentration", shortDescriptionZh: "从母液计算目标终浓度所需加入量", category: "solutions", aliases: ["dose", "C1V1", "加药"], plateAware: true, method: "C1V1 = C2V2", methodZh: "C1V1 = C2V2", methodVersion: "reagent-dosing-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10, "mM"), numberField("targetConcentration", "Final concentration", "目标终浓度", 10, "µM"), numberField("finalVolumeMl", "Final volume", "最终体积", 10, "mL"), numberField("stockToTargetFactor", "Stock-unit to target-unit factor", "母液单位相对目标单位倍数", 1000)], exampleInputs: { stockConcentration: 10, targetConcentration: 10, finalVolumeMl: 10, stockToTargetFactor: 1000 } },
  { id: "dilution", name: "Dilution", nameZh: "常规稀释", shortDescription: "Dilute a stock to a working concentration", shortDescriptionZh: "将浓缩母液稀释至工作浓度", category: "solutions", aliases: ["C1V1=C2V2", "母液稀释"], plateAware: true, method: "C1V1 = C2V2 with compatible concentration units", methodZh: "使用兼容浓度单位的C1V1=C2V2", methodVersion: "dilution-v1", fields: [numberField("stockConcentration", "Stock concentration", "母液浓度", 10), numberField("targetConcentration", "Target concentration", "目标浓度", 1), numberField("finalVolume", "Final volume", "目标总体积", 10), selectField("volumeUnit", "Volume unit", "体积单位", "mL", [["µL", "µL", "µL"], ["mL", "mL", "mL"], ["L", "L", "L"]])], exampleInputs: { stockConcentration: 10, targetConcentration: 1, finalVolume: 10, volumeUnit: "mL" } },
  { id: "fold-dilution", name: "Fold Dilution", nameZh: "倍数稀释", shortDescription: "Prepare 1× from a concentrated stock", shortDescriptionZh: "由浓缩液配制1×工作液", category: "solutions", aliases: ["2x", "10x", "倍液"], plateAware: true, method: "Concentrated-stock volume = final volume ÷ fold", methodZh: "浓缩液体积 = 最终体积 ÷ 倍数", methodVersion: "fold-dilution-v1", fields: [numberField("fold", "Stock fold", "浓缩倍数", 10), numberField("finalVolume", "Final volume", "最终体积", 100, "mL")], exampleInputs: { fold: 10, finalVolume: 100 } },
  { id: "serial-dilution", name: "Serial Dilution", nameZh: "连续稀释", shortDescription: "Multi-step fixed-factor dilution", shortDescriptionZh: "生成多级固定倍数稀释步骤", category: "solutions", aliases: ["梯度稀释", "serial"], plateAware: true, method: "Each level transfers total volume ÷ dilution factor from the prior level", methodZh: "每一级从前一级转移目标总体积除以稀释倍数", methodVersion: "serial-dilution-v1", fields: [numberField("startingConcentration", "Starting concentration", "起始浓度", 100), numberField("dilutionFactor", "Dilution factor", "每级稀释倍数", 10), numberField("levels", "Levels", "级数", 6, "integer", 1), numberField("totalVolumePerLevel", "Volume per level", "每级总体积", 100, "µL")], exampleInputs: { startingConcentration: 100, dilutionFactor: 10, levels: 6, totalVolumePerLevel: 100 } },
  { id: "molarity", name: "Molarity", nameZh: "摩尔浓度", shortDescription: "Concentration, mass, or volume from molecular weight", shortDescriptionZh: "根据分子量求浓度、质量或体积", category: "solutions", aliases: ["moles", "摩尔", "称量"], plateAware: false, method: "Moles = mass ÷ molecular weight; molarity = moles ÷ volume", methodZh: "物质的量 = 质量 ÷ 分子量；摩尔浓度 = 物质的量 ÷ 体积", methodVersion: "molarity-v1", fields: [selectField("mode", "Solve for", "求解目标", "mass", [["mass", "Mass to weigh", "称量质量"], ["concentration", "Concentration", "浓度"], ["volume", "Volume", "体积"]]), numberField("molecularWeight", "Molecular weight", "分子量", 180.16, "g/mol"), numberField("concentrationM", "Concentration", "摩尔浓度", 0.1, "M"), numberField("volumeL", "Volume", "体积", 0.1, "L"), numberField("massG", "Mass", "质量", 1.8016, "g")], exampleInputs: { mode: "mass", molecularWeight: 180.16, concentrationM: 0.1, volumeL: 0.1, massG: 1.8016 } },
  { id: "percent-solution", name: "% Solution", nameZh: "百分比溶液", shortDescription: "w/v or v/v solution preparation", shortDescriptionZh: "配制w/v或v/v百分比溶液", category: "solutions", aliases: ["w/v", "v/v", "百分浓度"], plateAware: false, method: "% w/v = g per 100 mL; % v/v = mL per 100 mL", methodZh: "% w/v表示每100 mL中的克数；% v/v表示每100 mL中的毫升数", methodVersion: "percent-solution-v1", fields: [selectField("type", "Solution type", "溶液类型", "w/v", [["w/v", "w/v", "质量/体积"], ["v/v", "v/v", "体积/体积"]]), numberField("percentage", "Percentage", "百分浓度", 5, "%"), numberField("targetVolumeMl", "Target volume", "目标体积", 500, "mL")], exampleInputs: { type: "w/v", percentage: 5, targetVolumeMl: 500 } },
  { id: "media-recipe", name: "Media Recipe", nameZh: "培养基配方", shortDescription: "Scale a custom medium recipe", shortDescriptionZh: "按目标体积缩放培养基配方", category: "solutions", aliases: ["culture medium", "培养液"], plateAware: false, method: "Each component scales linearly from the recipe base volume", methodZh: "各组分按配方基础体积线性缩放", methodVersion: "media-recipe-v1", fields: [numberField("baseVolumeMl", "Recipe base volume", "配方基础体积", 500, "mL"), numberField("targetVolumeMl", "Target volume", "目标体积", 1000, "mL"), textField("components", "Components (name, amount, unit)", "组分（名称,用量,单位）", "FBS,50,mL\nPen/Strep,5,mL", true)], exampleInputs: { baseVolumeMl: 500, targetVolumeMl: 1000, components: "FBS,50,mL\nPen/Strep,5,mL" } },
  { id: "buffer-recipe", name: "Buffer Recipe", nameZh: "缓冲液配方", shortDescription: "Scale a custom buffer recipe", shortDescriptionZh: "按目标体积缩放缓冲液配方", category: "solutions", aliases: ["PBS", "Tris", "缓冲液"], plateAware: false, method: "Each component scales linearly from the recipe base volume", methodZh: "各组分按配方基础体积线性缩放", methodVersion: "buffer-recipe-v1", fields: [numberField("baseVolumeMl", "Recipe base volume", "配方基础体积", 1000, "mL"), numberField("targetVolumeMl", "Target volume", "目标体积", 500, "mL"), textField("components", "Components (name, amount, unit)", "组分（名称,用量,单位）", "NaCl,8,g\nKCl,0.2,g", true)], exampleInputs: { baseVolumeMl: 1000, targetVolumeMl: 500, components: "NaCl,8,g\nKCl,0.2,g" } },
  { id: "ic50-ec50", name: "IC50 / EC50", nameZh: "IC50 / EC50拟合", shortDescription: "Four-parameter logistic dose-response fit", shortDescriptionZh: "四参数Logistic剂量反应拟合", category: "solutions", aliases: ["4PL", "dose response", "半数抑制"], plateAware: false, method: "Four-parameter logistic model fitted by deterministic coordinate descent", methodZh: "使用确定性坐标下降拟合四参数Logistic模型", methodVersion: "four-pl-v2", fields: [selectField("mode", "Response direction", "反应方向", "activation", [["inhibition", "Remaining response (falling)", "残存反应（下降）"], ["activation", "Activation (rising)", "激活反应（上升）"]]), textField("points", "Dose,response pairs", "浓度,反应值", "0.1,1\n1,10\n10,50\n100,90\n1000,99", true)], exampleInputs: { mode: "activation", points: "0.1,1\n1,10\n10,50\n100,90\n1000,99" } },

  { id: "master-mix", name: "Master Mix", nameZh: "Master Mix体系", shortDescription: "Scale repeated reaction components", shortDescriptionZh: "按反应数和余量计算整批反应体系", category: "molecular-biology", aliases: ["PCR mix", "反应体系"], plateAware: true, method: "Per-reaction components × reactions × (1 + overage)", methodZh: "单反应组分 × 反应数 ×（1 + 余量）", methodVersion: "master-mix-v1", fields: [numberField("reactions", "Reactions", "反应数", 10, "integer", 1), numberField("overagePercent", "Overage", "额外余量", 10, "%"), textField("components", "Components (name, µL/reaction)", "组分（名称,每反应µL）", "2× SYBR Mix,10\nForward primer,0.5\nReverse primer,0.5\nWater,8", true)], exampleInputs: { reactions: 10, overagePercent: 10, components: "2× SYBR Mix,10\nForward primer,0.5\nReverse primer,0.5\nWater,8" } },
  { id: "ligation", name: "Ligation", nameZh: "连接反应", shortDescription: "Insert mass for a vector:insert molar ratio", shortDescriptionZh: "按载体与插入片段摩尔比计算插入片段质量", category: "molecular-biology", aliases: ["cloning", "载体连接"], plateAware: false, method: "Insert ng = vector ng × insert bp ÷ vector bp × molar ratio", methodZh: "插入片段ng = 载体ng × 插入片段bp ÷ 载体bp × 摩尔比", methodVersion: "ligation-v1", fields: [numberField("vectorBp", "Vector length", "载体长度", 5000, "bp"), numberField("insertBp", "Insert length", "插入片段长度", 1000, "bp"), numberField("vectorNg", "Vector mass", "载体质量", 50, "ng"), numberField("molarRatio", "Insert:vector molar ratio", "插入:载体摩尔比", 3)], exampleInputs: { vectorBp: 5000, insertBp: 1000, vectorNg: 50, molarRatio: 3 } },
  { id: "tm", name: "Tm Calculator", nameZh: "引物Tm计算", shortDescription: "Primer melting-temperature estimate", shortDescriptionZh: "根据序列与盐条件估算引物熔解温度", category: "molecular-biology", aliases: ["primer", "melting temperature", "引物"], plateAware: false, method: "Wallace rule for short oligos; empirical long-oligo formula with monovalent-salt correction", methodZh: "短寡核苷酸使用Wallace规则，长序列使用含单价盐校正的经验公式", methodVersion: "tm-basic-v1", fields: [textField("sequence", "Primer sequence", "引物序列", "ATGCGTACGTTAGCTAAGCT"), numberField("sodiumMm", "Monovalent salt", "单价盐浓度", 50, "mM")], exampleInputs: { sequence: "ATGCGTACGTTAGCTAAGCT", sodiumMm: 50 } },
  { id: "dna-rna-conversion", name: "DNA / RNA Conversions", nameZh: "DNA / RNA换算", shortDescription: "Mass, moles, molecules, and concentration", shortDescriptionZh: "质量、摩尔数、分子数和浓度换算", category: "molecular-biology", aliases: ["copies", "molecules", "核酸换算"], plateAware: false, method: "Molecular weight from length and nucleic-acid type; molecules from Avogadro constant", methodZh: "按长度与核酸类型估算分子量，再用阿伏伽德罗常数计算分子数", methodVersion: "nucleic-acid-conversion-v1", fields: [selectField("type", "Nucleic acid", "核酸类型", "dsDNA", [["dsDNA", "dsDNA", "双链DNA"], ["ssDNA", "ssDNA", "单链DNA"], ["RNA", "RNA", "RNA"]]), numberField("length", "Length", "长度", 500, "nt/bp"), numberField("massUg", "Mass", "质量", 1, "µg"), numberField("volumeUl", "Volume", "体积", 20, "µL")], exampleInputs: { type: "dsDNA", length: 500, massUg: 1, volumeUl: 20 } },
  { id: "bradford-bca", name: "Bradford / BCA", nameZh: "Bradford / BCA蛋白定量", shortDescription: "Protein standard curve and sample back-calculation", shortDescriptionZh: "蛋白标准曲线拟合与样品浓度回算", category: "molecular-biology", aliases: ["protein assay", "标准曲线", "蛋白浓度"], plateAware: false, method: "Blank-corrected ordinary least-squares linear standard curve", methodZh: "空白扣除后的普通最小二乘线性标准曲线", methodVersion: "protein-linear-v1", fields: [textField("standards", "Standards (concentration, absorbance)", "标准品（浓度,吸光度）", "0,0.05\n0.25,0.18\n0.5,0.31\n1,0.57\n1.5,0.82", true), numberField("sampleAbsorbance", "Sample absorbance", "样品吸光度", 0.44), numberField("dilutionFactor", "Sample dilution factor", "样品稀释倍数", 2)], exampleInputs: { standards: "0,0.05\n0.25,0.18\n0.5,0.31\n1,0.57\n1.5,0.82", sampleAbsorbance: 0.44, dilutionFactor: 2 } },
  { id: "elisa-4pl", name: "ELISA 4PL", nameZh: "ELISA四参数拟合", shortDescription: "ELISA standard curve and sample back-calculation", shortDescriptionZh: "ELISA标准曲线拟合和样品浓度回算", category: "molecular-biology", aliases: ["ELISA", "4PL", "免疫测定"], plateAware: false, method: "Four-parameter logistic standard curve with inverse sample calculation", methodZh: "四参数Logistic标准曲线及样品反算", methodVersion: "elisa-four-pl-v1", fields: [textField("standards", "Standards (concentration, signal)", "标准品（浓度,信号）", "0.1,0.08\n1,0.2\n10,1.0\n100,1.8\n1000,1.95", true), numberField("sampleSignal", "Sample signal", "样品信号", 1), numberField("dilutionFactor", "Sample dilution factor", "样品稀释倍数", 1)], exampleInputs: { standards: "0.1,0.08\n1,0.2\n10,1.0\n100,1.8\n1000,1.95", sampleSignal: 1, dilutionFactor: 1 } },
  { id: "wb-loading", name: "WB Loading", nameZh: "Western Blot上样", shortDescription: "Sample, loading buffer, and reducing agent", shortDescriptionZh: "计算样品、Loading Buffer与还原剂", category: "molecular-biology", aliases: ["western blot", "上样体系"], plateAware: false, method: "Sample volume from target protein mass; concentrated buffer by final fold", methodZh: "按目标蛋白质量计算样品体积，并按终浓度计算浓缩上样缓冲液", methodVersion: "wb-loading-v1", fields: [numberField("sampleConcentrationUgUl", "Sample concentration", "样品浓度", 2, "µg/µL"), numberField("targetProteinUg", "Protein per lane", "每孔蛋白量", 20, "µg"), numberField("finalLoadingVolumeUl", "Final loading volume", "最终上样体积", 20, "µL"), numberField("bufferFold", "Loading buffer stock", "Loading Buffer倍数", 4), numberField("reducingAgentPercent", "Reducing agent", "还原剂比例", 5, "%")], exampleInputs: { sampleConcentrationUgUl: 2, targetProteinUg: 20, finalLoadingVolumeUl: 20, bufferFold: 4, reducingAgentPercent: 5 } },

  { id: "moi", name: "MOI", nameZh: "感染复数 MOI", shortDescription: "Virus amount and Poisson infection probabilities", shortDescriptionZh: "计算病毒用量及泊松感染概率", category: "virology-microbiology", aliases: ["multiplicity of infection", "病毒感染"], plateAware: true, method: "Particles required = cells × MOI; Poisson probabilities use e^-MOI", methodZh: "所需感染单位 = 细胞数 × MOI；感染概率按e^-MOI计算", methodVersion: "moi-v1", fields: [numberField("cells", "Cells", "细胞数", 1_000_000, "cells"), numberField("desiredMoi", "Desired MOI", "目标MOI", 1), numberField("titer", "Virus titer", "病毒滴度", 100_000_000), selectField("titerUnit", "Titer unit", "滴度单位", "PFU/mL", [["PFU/mL", "PFU/mL", "PFU/mL"], ["IU/mL", "IU/mL", "IU/mL"], ["TU/mL", "TU/mL", "TU/mL"], ["VG/mL", "VG/mL", "VG/mL"]])], exampleInputs: { cells: 1_000_000, desiredMoi: 1, titer: 100_000_000, titerUnit: "PFU/mL" } },
  { id: "virus-titer", name: "Virus Titer", nameZh: "病毒滴度", shortDescription: "Plaque-assay PFU/mL or TCID50 estimate", shortDescriptionZh: "噬菌斑PFU/mL或TCID50估算", category: "virology-microbiology", aliases: ["PFU", "TCID50", "病毒滴度"], plateAware: false, method: "Plaque assay: plaques ÷ (dilution × inoculum mL); TCID50 remains a distinct mode", methodZh: "噬菌斑法：斑数 ÷（稀释度 × 接种体积mL）；TCID50保持独立模式", methodVersion: "virus-titer-v1", fields: [selectField("mode", "Method", "方法", "plaque", [["plaque", "Plaque assay", "噬菌斑法"], ["tcid50", "TCID50", "TCID50"]]), numberField("plaques", "Plaques", "噬菌斑数", 20, "integer", 1), numberField("dilution", "Dilution fraction", "稀释度", 0.000001), numberField("inoculumMl", "Inoculum volume", "接种体积", 0.1, "mL"), textField("tcidSeries", "TCID50 positive wells (dilution,positive,total)", "TCID50阳性孔（稀释度,阳性数,总孔数）", "0.001,8,8\n0.0001,6,8\n0.00001,2,8\n0.000001,0,8", true)], exampleInputs: { mode: "plaque", plaques: 20, dilution: 0.000001, inoculumMl: 0.1 } },

  { id: "unit-converter", name: "Unit Converter", nameZh: "单位换算", shortDescription: "Mass, volume, concentration, and temperature", shortDescriptionZh: "质量、体积、浓度和温度换算", category: "general", aliases: ["convert", "换算"], plateAware: false, method: "Dimension-specific SI conversion; temperature uses affine conversion", methodZh: "同维度SI单位换算；温度使用仿射换算", methodVersion: "unit-converter-v1", fields: [selectField("dimension", "Dimension", "换算类型", "volume", [["mass", "Mass", "质量"], ["volume", "Volume", "体积"], ["concentration", "Concentration", "浓度"], ["temperature", "Temperature", "温度"]]), numberField("value", "Value", "数值", 1), textField("fromUnit", "From unit", "原单位", "mL"), textField("toUnit", "To unit", "目标单位", "µL")], exampleInputs: { dimension: "volume", value: 1, fromUnit: "mL", toUnit: "µL" } },
  { id: "centrifuge", name: "Centrifuge", nameZh: "离心换算", shortDescription: "RPM and RCF conversion", shortDescriptionZh: "RPM与RCF相互换算", category: "general", aliases: ["g force", "转速", "离心力"], plateAware: false, method: "RCF = 1.118 × 10⁻⁵ × radius(cm) × RPM²", methodZh: "RCF = 1.118 × 10⁻⁵ × 半径(cm) × RPM²", methodVersion: "centrifuge-v1", fields: [selectField("mode", "Conversion", "换算方向", "rpm-to-rcf", [["rpm-to-rcf", "RPM to RCF", "RPM转RCF"], ["rcf-to-rpm", "RCF to RPM", "RCF转RPM"]]), numberField("rpm", "RPM", "转速", 10_000, "rpm"), numberField("rcf", "RCF", "相对离心力", 11_180, "×g"), numberField("radiusCm", "Rotor radius", "转子半径", 10, "cm")], exampleInputs: { mode: "rpm-to-rcf", rpm: 10_000, radiusCm: 10 } },
];

definitions.push(...newDefinitions);
export const byId = new Map(definitions.map((definition) => [definition.id, definition]));
export function getCalculatorCatalog(): CalculatorDefinition[] { return definitions.map((definition) => enhanceDefinition({ ...definition, exampleInputs: { ...definition.exampleInputs }, fields: definition.fields.map((field) => ({ ...field })) })); }
export function getCalculatorDefinition(id: string): CalculatorDefinition {
  const definition = byId.get(id);
  if (!definition) throw new Error(`Unknown calculator: ${id}`);
  return enhanceDefinition({ ...definition, exampleInputs: { ...definition.exampleInputs }, fields: definition.fields.map((field) => ({ ...field })) });
}
