import {describe,it,expect} from 'vitest';
import {parseCalculatorState,restoreLegacyInputs,createEmptyCalculatorState,addHistoryEntry} from './calculator-storage';
import {calculate,getCalculatorCatalog} from './calculator-engine';
describe('immutable migration',()=>{
 it('retains original history and resolves duplicate old pins in user order',()=>{const old={version:1,favorites:['reagent-dosing','seeding','dilution','fold-dilution'],presets:[],history:[{id:'old',calculatorId:'dilution',calculatorName:'Dilution',calculatorNameZh:'稀释',createdAt:'2020-01-01',methodVersion:'dilution-v1',inputs:{stockConcentration:10,targetConcentration:1,finalVolume:10},outputs:[],warnings:[]}]};const state=parseCalculatorState(JSON.stringify(old));expect(state.favorites).toEqual(['dilution','seeding']);expect(state.history).toEqual(old.history);expect(restoreLegacyInputs('dilution',old.history[0].inputs).warning).toBeTruthy();expect(restoreLegacyInputs('dilution',old.history[0].inputs).inputs.stockConcentration).toBe('');});
 it('never guesses custom dosing factors',()=>{expect(restoreLegacyInputs('reagent-dosing',{stockConcentration:10,targetConcentration:1,stockToTargetFactor:999}).warning).toBeTruthy();const valid=restoreLegacyInputs('reagent-dosing',{stockConcentration:10,targetConcentration:10,stockToTargetFactor:1000,finalVolumeMl:2});expect(calculate({calculatorId:'reagent-dosing',inputs:valid.inputs}).outputMap.stockVolumeUl).toBe(2);});
 it('keeps table, notes, normalized inputs and version through JSON reload',()=>{const inputs={startingConcentration:100,dilutionFactor:2,levels:4,totalVolumePerLevel:100};const snapshot=calculate({calculatorId:'serial-dilution',inputs});const state=addHistoryEntry(createEmptyCalculatorState(),{id:'new',calculatorId:'serial-dilution',calculatorName:'Serial',calculatorNameZh:'梯度',createdAt:'2026-09-06',methodVersion:snapshot.methodVersion,inputs,outputs:snapshot.outputs,warnings:snapshot.warnings,snapshot});expect(parseCalculatorState(JSON.stringify(state)).history[0].snapshot).toEqual(snapshot);const replacement={...state.history[0],methodVersion:'wrong'};expect(addHistoryEntry(state,replacement).history[0].methodVersion).toBe(snapshot.methodVersion);});
 it('all 31 original route IDs remain registered',()=>{const ids='hemocytometer,seeding,hydrogel,split,freezing,transfection,kill-curve,viability,od600,cfu,colony-counter,reagent-dosing,dilution,fold-dilution,serial-dilution,molarity,percent-solution,media-recipe,buffer-recipe,ic50-ec50,master-mix,ligation,tm,dna-rna-conversion,bradford-bca,elisa-4pl,wb-loading,moi,virus-titer,unit-converter,centrifuge'.split(',');for(const id of ids)expect(getCalculatorCatalog().some(tool=>tool.id===id)).toBe(true);});
});
