import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
function worker(){
 const handlers:Record<string,(event:Record<string,unknown>)=>void>={};const stores=new Map<string,Map<string,Response>>();let failure='',requests=0;
 const key=(value:string|Request)=>new URL(typeof value==='string'?value:value.url,'https://lab.test').href;
 const caches={keys:async()=>[...stores.keys()],delete:async(name:string)=>{if(['delete','quota-delete'].includes(failure))throw Error('storage deletion denied');return stores.delete(name);},open:async(name:string)=>{if(!stores.has(name))stores.set(name,new Map());const map=stores.get(name)!;return {keys:async()=>[...map.keys()].map(url=>new Request(url)),match:async(value:string|Request)=>map.get(key(value))?.clone(),put:async(value:string|Request,response:Response)=>{if(['quota','quota-delete'].includes(failure)&&name.includes('v5-'))throw new DOMException('full','QuotaExceededError');map.set(key(value),response.clone());}};}};
 const self={location:{origin:'https://lab.test'},skipWaiting:async()=>{},clients:{claim:async()=>{}},addEventListener:(name:string,fn:typeof handlers[string])=>handlers[name]=fn};
 vm.runInNewContext(readFileSync('public/tools/calculator/worker.js','utf8'),{self,caches,crypto,URL,Response,Request,AbortController,setTimeout,clearTimeout,fetch:async(value:string|Request)=>{requests++;if(failure==='timeout')throw new DOMException('timeout','AbortError');if(failure==='resource')return new Response('not found',{status:404});if(failure==='mime')return new Response('login',{headers:{'Content-Type':'text/html'}});return new Response(key(value).includes('/_next/')?'script':'<html><script src="/_next/static/a.js"></script></html>',{headers:{'Content-Type':key(value).includes('/_next/')?'application/javascript':'text/html'}});}});
 return {stores,caches,setFailure:(v:string)=>failure=v,requests:()=>requests,message:async(type:string)=>{let pending:Promise<void>|undefined,result:Record<string,unknown>={};handlers.message({data:{type,pages:['/tools/calculator'],resources:['/_next/static/a.js']},ports:[{postMessage:(r:Record<string,unknown>)=>result=r}],waitUntil:(p:Promise<void>)=>pending=p});await pending;return result;},fetch:async(path:string)=>{let pending:Promise<Response>|undefined;handlers.fetch({request:new Request('https://lab.test'+path),respondWith:(p:Promise<Response>)=>pending=p});return pending;}};
}
describe('Explicit offline generation contract',()=>{
 it('serializes simultaneous preparations without deleting either active generation mid-write',async()=>{const w=worker();const results=await Promise.all([w.message('CACHE_CALCULATOR'),w.message('CACHE_CALCULATOR')]);expect(results.every(r=>r.ok)).toBe(true);expect((await w.message('CALCULATOR_STATUS')).ok).toBe(true);expect([...w.stores.keys()].filter(k=>k.includes('v5-'))).toHaveLength(1);});
 it('publishes only complete resources and keeps last usable generation on HTTP or quota failure',async()=>{const w=worker();expect((await w.message('CACHE_CALCULATOR')).ok).toBe(true);const before=[...w.stores.keys()];for(const failure of ['resource','quota','mime','timeout']){w.setFailure(failure);expect((await w.message('CACHE_CALCULATOR')).ok).toBe(false);expect([...w.stores.keys()]).toEqual(before);expect((await w.message('CALCULATOR_STATUS')).ok).toBe(true);}});
 it('keeps a v4 fallback usable until a complete replacement succeeds, without claiming v4 completeness',async()=>{const w=worker();const old=await w.caches.open('labnest-calculator-shell-v4');await old.put('/tools/calculator',new Response('old snapshot'));w.setFailure('timeout');expect((await w.message('CALCULATOR_STATUS')).ok).toBe(false);expect(await (await w.fetch('/tools/calculator'))?.text()).toBe('old snapshot');expect((await w.message('CACHE_CALCULATOR')).ok).toBe(false);expect(w.stores.has('labnest-calculator-shell-v4')).toBe(true);w.setFailure('');expect((await w.message('CACHE_CALCULATOR')).ok).toBe(true);expect(w.stores.has('labnest-calculator-shell-v4')).toBe(false);});
 it('reports failed clear/cleanup and still accepts status and retry messages',async()=>{const w=worker();await w.message('CACHE_CALCULATOR');w.setFailure('delete');expect((await w.message('CLEAR_CALCULATOR')).ok).toBe(false);expect((await w.message('CALCULATOR_STATUS')).ok).toBe(true);expect((await w.message('CACHE_CALCULATOR')).ok).toBe(true);expect((await w.message('CALCULATOR_STATUS')).ok).toBe(true);w.setFailure('quota-delete');expect((await w.message('CACHE_CALCULATOR')).ok).toBe(false);expect((await w.message('CALCULATOR_STATUS')).ok).toBe(true);w.setFailure('');expect((await w.message('CACHE_CALCULATOR')).ok).toBe(true);expect((await w.message('CLEAR_CALCULATOR')).ok).toBe(true);});
 it('uses hashed static cache first and never caches unrelated API or writes',async()=>{const w=worker();await w.message('CACHE_CALCULATOR');const n=w.requests();await w.fetch('/_next/static/a.js');expect(w.requests()).toBe(n);expect(await w.fetch('/api/mobile/queue')).toBeUndefined();});
 it('detects eviction and clears only tool namespaces',async()=>{const w=worker();await w.message('CACHE_CALCULATOR');await w.caches.open('other-app-data');const active=[...w.stores.keys()].find(k=>k.includes('v5-'))!;w.stores.get(active)!.clear();expect((await w.message('CALCULATOR_STATUS')).ok).toBe(false);await w.message('CLEAR_CALCULATOR');expect([...w.stores.keys()]).toEqual(['other-app-data']);});
});
