import {describe,it,expect} from 'vitest';
import {calculate} from './calculator-engine';
import {convert,parseScalar} from './quantities';
import {serialPlan,mixPlan,batchPlan} from './planning';
const calc=(calculatorId:string,inputs:Record<string,unknown>)=>calculate({calculatorId,inputs});
const near=(actual:unknown,expected:number)=>expect(Math.abs(Number(actual)-expected)).toBeLessThanOrEqual(Math.max(1e-15,Math.abs(expected)*1e-9));
describe('Spec v1.0 independent acceptance',()=>{
 it('NUM-01/02/29 quantity round trips',()=>{near(convert(1,'mL','µL'),1000);near(convert(1000,'µL','mL'),1);near(convert(1,'ng/µL','µg/mL'),1);near(convert(25,'°C','°F'),77);near(convert(25,'°C','K'),298.15);});
 it('NUM-03/04/05 final dilution',()=>{const base={mode:'final',stockConcentration:10,targetConcentration:10,finalVolume:2};near(calc('dilution',base).outputMap.stockVolumeUl,2);near(calc('dilution',{...base,stockConcentration:10000,stockConcentrationUnit:'µM'}).outputMap.stockVolumeUl,2);near(calc('dilution',{...base,stockConcentration:100,targetConcentration:10,targetConcentrationUnit:'mM',finalVolume:1}).outputMap.stockVolumeUl,100);});
 it('NUM-06 add mode',()=>{const result=calc('dilution',{mode:'add',stockConcentration:100,targetConcentration:10,targetConcentrationUnit:'mM',initialConcentration:0,finalVolume:1});near(result.outputMap.stockVolumeUl,111.11111111111111);near(result.outputMap.finalVolume,1.1111111111111112);});
 it('NUM-07/08/09 distinct ratio definitions',()=>{near(calc('dilution',{mode:'fold',stockFold:10,targetFold:2,finalVolume:100}).outputMap.stockVolume,20);near(calc('dilution',{mode:'ratio',ratio:1000,finalVolume:10}).outputMap.stockVolumeUl,10);near(calc('dilution',{mode:'parts',stockParts:1,diluentParts:10,finalVolume:11}).outputMap.stockVolume,1);});
 it('NUM-10/11/12/33 weighing and purity',()=>{near(calc('molarity',{mode:'mass',molecularWeight:58.44,concentrationM:0.1,volumeL:100,volumeLUnit:'mL'}).outputMap.massG,0.5844);near(calc('percent-solution',{type:'w/v',percentage:2,targetVolumeMl:50}).outputMap.soluteAmount,1);near(calc('percent-solution',{type:'w/w',percentage:10,targetMassG:100}).outputMap.soluteAmount,10);near(calc('molarity',{mode:'mass',molecularWeight:1,concentrationM:1,volumeL:1,purityPercent:80}).outputMap.massG,1.25);});
 it('NUM-13/14 resuspension and length estimate',()=>{near(calc('resuspension',{mode:'amount',amount:25,targetMolar:100}).outputMap.finalVolumeUl,250);near(calc('dna-rna-conversion',{type:'dsDNA',length:1000,massUg:66,volumeUl:1000}).outputMap.concentrationNm,100);});
 it('NUM-15/16/17/18 live cells and balance',()=>{near(calc('hemocytometer',{counts:'10,20,30,40',dilutionFactor:2,viabilityPercent:80}).outputMap.viableCellsPerMl,400000);const inputs={stockCellsPerMl:2e6,wells:24,cellsPerWell:5e4,volumePerWellUl:500,overagePercent:10};const r=calc('seeding',inputs).outputMap;near(r.totalCells,1320000);near(r.stockVolumeMl,0.66);near(r.mediumVolumeMl,12.54);near(r.finalVolumeMl,13.2);near(calc('seeding',{...inputs,stockCellsPerMl:400000}).outputMap.stockVolumeMl,3.3);expect(()=>calc('seeding',{...inputs,stockCellsPerMl:5e4})).toThrow();});
 it('NUM-19/20 premix excludes separate templates',()=>{const r=mixPlan([{name:'Mix',volume:'10',premix:true},{name:'F',volume:'.5',premix:true},{name:'R',volume:'.5',premix:true},{name:'Template',volume:'2',premix:false},{name:'Water',volume:'7',premix:true}],26,2.6,20);near(r.total,514.8);expect(r.table.map(row=>row.batchUl)).toEqual([286,14.3,14.3,'',200.20000000000002]);near(r.separate,2);});
 it('NUM-21 DNA volume included',()=>{const r=calc('transfection',{wells:1,replicates:1,dnaUgPerWell:2,dnaConcentrationUgUl:1,reagentUlPerUg:3,complexVolumeUlPerWell:125,overagePercent:0}).outputMap;near(r.dnaVolumeUl,2);near(r.reagentUl,6);near(r.diluentUl,117);});
 it('NUM-22/23 WB rejects impossible recipes',()=>{const inputs={sampleConcentrationUgUl:2,targetProteinUg:20,finalLoadingVolumeUl:20,bufferFold:4,reducingAgentPercent:0};const r=calc('wb-loading',inputs).outputMap;near(r.sampleUl,10);near(r.loadingBufferUl,5);near(r.waterUl,5);expect(()=>calc('wb-loading',{...inputs,sampleConcentrationUgUl:.5})).toThrow();});
 it('NUM-24 invalid rows remain blank',()=>{const rows=batchPlan([{id:'A',concentration:'50',available:''},{id:'B',concentration:'5',available:''}],10,20);near(rows[0].sampleUl,4);near(rows[0].diluentUl,16);expect(rows[1].sampleUl).toBe('');});
 it('NUM-25/26/27 serial conservation',()=>{const mixed=serialPlan(100,2,4,100,false),retained=serialPlan(100,2,4,100,true);expect(mixed.map(r=>r.concentration)).toEqual([100,50,25,12.5]);expect(mixed.map(r=>r.remainingUl)).toEqual([50,50,50,100]);expect(retained.map(r=>r.mixedUl)).toEqual([187.5,175,150,100]);expect(retained.map(r=>r.transferUl)).toEqual([87.5,75,50,0]);expect(retained.map(r=>r.remainingUl)).toEqual([100,100,100,100]);});
 it('NUM-28/30/31/32 equipment and professional tools',()=>{near(calc('centrifuge',{mode:'rpm-to-rcf',radiusCm:10,rpm:1000}).outputMap.rcf,111.8);near(calc('centrifuge',{mode:'rcf-to-rpm',radiusCm:10,rcf:111.8}).outputMap.rpm,1000);near(calc('ligation',{vectorBp:5000,vectorNg:50,insertBp:1000,molarRatio:3}).outputMap.insertNg,30);near(calc('cfu',{colonies:120,dilution:1e-6,platedVolumeMl:.1,dnaUg:0}).outputMap.cfuPerMl,1.2e9);const r=calc('moi',{cells:1e5,desiredMoi:2,titer:1e8,titerUnit:'TU/mL'}).outputMap;near(r.virusVolumeUl,2);near(r.probabilityAtLeastOnePercent,86.46647167633873);});
 it('rejects blank, partial, nonfinite, ambiguity, incompatible dimensions and fractional wells',()=>{for(const value of ['', '.', '1e', 'NaN','Infinity','1,234.5'])expect(()=>parseScalar(value)).toThrow();near(parseScalar('1e6'),1e6);expect(()=>convert(1,'PFU/mL','TU/mL')).toThrow();expect(()=>calc('seeding',{wells:1.5,stockCellsPerMl:1e6,plates:1,overagePercent:0,cellsPerWell:100,volumePerWellUl:100})).toThrow();});
});
describe('extended workflow safeguards',()=>{
 it('keeps PCR groups separate and counts each group once',()=>{const rows=[{name:'Mix',volume:'18',premix:true},{name:'Template',volume:'2',premix:false}];const result=calc('master-mix',{groups:[{name:'A',reactions:'2',rows},{name:'B',reactions:'2',rows}],reactionVolumeUl:20,overagePercent:10});near(result.outputMap.totalMasterMixUl,79.2);expect(result.table?.filter(row=>row.premix==='独立加样 / Separate').every(row=>row.batchUl==='')).toBe(true);});
 it('accounts for both transfection tubes and buffer-contained reducing agent',()=>{const result=calc('transfection',{wells:1,replicates:1,dnaUgPerWell:2,dnaConcentrationUgUl:1,reagentUlPerUg:3,complexVolumeUlPerWell:125,overagePercent:0,complexMode:'two-tube',tubeAVolumeUl:62.5});expect(result.table?.map(row=>row.volumeUl)).toEqual([2,60.5,6,56.5]);near(calc('wb-loading',{sampleConcentrationUgUl:2,targetProteinUg:20,finalLoadingVolumeUl:20,bufferFold:4,bufferContainsReducingAgent:'yes',reducingAgentPercent:50}).outputMap.waterUl,5);});
 it('reports explicit rounding while retaining theoretical quantities',()=>{const result=calc('dilution',{mode:'final',stockConcentration:10,targetConcentration:11,finalVolume:2,pipetteStepUl:1,pipetteMinimumUl:3});near(result.outputMap.stockVolumeUl,2.2);near(result.table?.[0].actualUl,2);expect(result.notes.join(' ')).toContain('-9.09091');expect(result.warnings.length).toBe(1);});
 it('fits a descending response without silently dropping invalid observations',()=>{const result=calc('ic50-ec50',{mode:'inhibition',points:'0.1,99.009901\n1,90.909091\n10,50\n100,9.090909\n1000,0.990099'});expect(Number(result.outputMap.hillSlope)).toBeLessThan(0);expect(Number(result.outputMap.midpoint)).toBeCloseTo(10,1);expect(()=>calc('ic50-ec50',{mode:'activation',points:'0,0\n1,1\n10,50\n100,99'})).toThrow();});
});
describe('quantity bridges and preparation source',()=>{
 it('requires explicit MW to bridge mass and molar concentrations',()=>{const inputs={mode:'final',stockConcentration:1,stockConcentrationUnit:'mM',targetConcentration:.05,targetConcentrationUnit:'mg/mL',finalVolume:1,finalVolumeUnit:'L'};expect(()=>calc('dilution',inputs)).toThrow();near(calc('dilution',{...inputs,molecularWeight:100}).outputMap.stockVolumeUl,500000);});
 it('prepares the first gradient tube from a stronger stock',()=>{const result=calc('serial-dilution',{startingConcentration:100,dilutionFactor:2,levels:4,totalVolumePerLevel:100,firstSource:'stock',sourceConcentration:1000});near(result.table?.[0].takeUl,10);near(result.table?.[0].diluentUl,90);});
});
