import {describe,it,expect} from 'vitest';
import {calculate} from './calculator-engine';
import {transfectionPlateValues,exampleTransfectionPlan,changeTransfectionMaterial,changeTransfectionMixing,newDoseReagent,newNucleicRow,type TransfectionPlan} from './transfection';
import {resultClipboard,resultCsv} from './result-presentation';
const run=(p:TransfectionPlan)=>calculate({calculatorId:'transfection',inputs:{transfectionPlan:p,pipetteMinimumUl:2}});
function rna(){const p=changeTransfectionMaterial(exampleTransfectionPlan(),'sirna');const g=p.groups[0];g.rows=[{...newNucleicRow('sirna'),name:'siTarget',stock:'20',dose:'10'}];g.finalVolume='600';g.reagent={...newDoseReagent(),name:'RNAiMAX',amount:'1'};g.order='Dilute, mix, add to cells';return p;}
describe('transfection per-well design',()=>{
 it('keeps original legacy DNA arithmetic and two-tube sources',()=>{const r=calculate({calculatorId:'transfection',inputs:{wells:1,replicates:1,dnaUgPerWell:2,dnaConcentrationUgUl:1,reagentUlPerUg:3,complexVolumeUlPerWell:125,overagePercent:0,complexMode:'two-tube',tubeAVolumeUl:62.5}});expect(r.table?.map(r=>r.volumeUl)).toEqual([2,60.5,6,56.5]);});
 it('uses final culture volume for siRNA nM and records batch/per-well separately',()=>{const p=rna(),r=run(p),row=r.table!.find(r=>r.component==='siTarget')!;expect(row).toMatchObject({perWellUl:.3,rnaPmol:6,finalNm:10});expect(row.batchUl).toBeCloseTo(1.98);expect(r.outputMap.group0_final).toBe(600);expect(r.outputMap.group0_medium).toBe(475);expect(r.operations?.filter(o=>o.role==='dispense')[0].quantity.value).toBeCloseTo(125);expect(r.operations?.filter(o=>o.role==='dispense')[0].repetitions).toBe(6);const changed=structuredClone(p);changed.groups[0].overage='50';expect(run(changed).table![0].perWellUl).toBe(.3);expect(run(changed).table![0].batchUl).toBeCloseTo(2.7);});
 it('each vs mixture siRNA modes differ; pmol ignores tube/final-volume choice',()=>{const p=rna();p.material='multi-sirna';p.groups[0].rows.push({...p.groups[0].rows[0],name:'siOther'});expect(run(p).outputMap.group0_rna).toBe(12);p.groups[0].rnaMode='total-nm';p.groups[0].totalRna='10';expect(run(p).outputMap.group0_rna).toBe(6);expect(run(p).table![0].finalNm).toBe(5);p.groups[0].rnaMode='each-pmol';p.groups[0].rows.forEach(r=>r.dose='6');p.groups[0].finalVolume='1200';expect(run(p).table![0]).toMatchObject({rnaPmol:6,finalNm:5,perWellUl:.3});});
 it('molar ratios use size, while mass ratios do not',()=>{const p=exampleTransfectionPlan(),g=p.groups[0];p.material='multi-dna';g.rows=[{...g.rows[0],name:'P1',dose:'1',size:'3000'},{...g.rows[0],name:'P2',dose:'1',size:'6000'}];g.totalDna='3';g.dnaMode='mass-ratio';expect(run(p).table!.slice(0,2).map(r=>r.dnaMassUg)).toEqual([1.5,1.5]);g.dnaMode='molar-ratio';expect(run(p).table!.slice(0,2).map(r=>r.dnaMassUg)).toEqual([1,2]);g.rows[0].size='1.5';expect(()=>run(p)).toThrow(/integer/);g.rows[0].size='';expect(()=>run(p)).toThrow();});
 it('shRNA expression plasmid remains DNA; co-transfection sums distinct units',()=>{const p=exampleTransfectionPlan();p.material='shrna-plasmid';p.groups[0].rows[0].kind='shrna-plasmid';expect(run(p).table![0].dnaMassUg).toBe(2);p.material='dna-sirna';p.groups[0].rows.push({...newNucleicRow('sirna'),name:'siTarget',stock:'20',dose:'10'});const r=run(p);expect(r.outputMap.group0_dna).toBe(2);expect(r.outputMap.group0_rna).toBe(10);expect(r.table![1].perWellUl).toBe(.5);});
 it('add diluent vs bring to final counts every component',()=>{const p=exampleTransfectionPlan();p.groups[0].a={mode:'add',value:'50'};p.groups[0].b={mode:'add',value:'50'};expect(run(p).outputMap.group0_mixed).toBe(108);p.groups[0].a.mode='final';p.groups[0].b.mode='final';expect(run(p).outputMap.group0_mixed).toBe(100);p.groups[0].a.value='1';expect(()=>run(p)).toThrow(/exceed/);});
 it('mode switch clears hidden volume/reagent/order fields and requires new input',()=>{const p=changeTransfectionMixing(exampleTransfectionPlan(),'single');expect(p.groups[0].a.value).toBe('');expect(p.groups[0].reagent.amount).toBe('');expect(()=>run(p)).toThrow();p.groups[0].reagent={...newDoseReagent(),name:'Custom',amount:'3'};p.groups[0].single={mode:'add',value:'50'};p.groups[0].order='Add diluted DNA then reagent';p.groups[0].a.value='-99';p.groups[0].b.value='-99';expect(run(p).outputMap.group0_mixed).toBe(55);expect(run(p).table!.every(r=>r.tube==='单体系 / Single')).toBe(true);});
 it('rejects invalid product combinations and pure-siRNA P3000, including custom names',()=>{const p=rna();p.groups[0].auxiliaries=[{...newDoseReagent(),name:'P3000',amount:'1'}];expect(()=>run(p)).toThrow(/P3000/);p.groups[0].auxiliaries=[];p.protocol='rnaimax-reverse';expect(()=>run(p)).toThrow(/incompatible/);const dna=exampleTransfectionPlan();dna.groups[0].reagent.name='Lipofectamine RNAiMAX';expect(()=>run(dna)).toThrow(/RNAiMAX/);});
 it('distinct groups remain separate in table, operations and clipboard',()=>{const p=exampleTransfectionPlan();p.groups[0].rows[0].stock='20';p.groups.push({...structuredClone(p.groups[0]),name:'Control'});const r=run(p);expect(new Set(r.table!.map(r=>r.group))).toEqual(new Set(['DNA group','Control']));expect(new Set(r.operations!.map(r=>r.groupName))).toEqual(new Set(['DNA group','Control']));const copy=resultClipboard(r,false);expect(copy).toContain('Control');expect(copy).toContain('DNA group');expect(copy).not.toContain('Operations');expect(resultCsv(r,false)).toContain('transfection-v3');expect(r.structuredWarnings?.length).toBeGreaterThan(0);});
 it('product DNA enhancer and custom reagent bases are explicit and independently counted',()=>{const p=exampleTransfectionPlan();p.protocol='l3000';p.groups[0].reagent.name='Lipofectamine 3000';expect(()=>run(p)).toThrow(/P3000/);p.groups[0].auxiliaries=[{...newDoseReagent(),name:'P3000',basis:'dna',amount:'2'}];expect(run(p).table!.find(r=>r.component==='P3000')?.perWellUl).toBe(4);p.protocol='custom';p.groups[0].reagent={...newDoseReagent(),name:'Custom',basis:'custom',amount:'0.1',basisName:'Cells',basisUnit:'100000 cells',basisAmount:'5'};expect(run(p).table!.find(r=>r.component==='Custom')?.perWellUl).toBe(.5);p.groups[0].reagent.basisUnit='';expect(()=>run(p)).toThrow();});
 it('siRNA product profile requires no DNA enhancer; incompatible units and malformed drafts fail',()=>{const p=rna();p.protocol='l3000';p.groups[0].reagent.name='Lipofectamine 3000';expect(run(p).table!.some(r=>r.component==='P3000')).toBe(false);p.groups[0].rows[0].stockUnit='µg/µL';expect(()=>run(p)).toThrow();expect(()=>run({version:4} as unknown as TransfectionPlan)).toThrow(/unsupported/);});
 it('plate assignments use per-well values and reject multi-group ambiguity',()=>{const p=exampleTransfectionPlan();expect(transfectionPlateValues(p,6).group0_dna).toBe(2);expect(()=>transfectionPlateValues(p,5)).toThrow();p.groups.push({...structuredClone(p.groups[0]),name:'Other'});expect(()=>transfectionPlateValues(p,12)).toThrow();});
 it('rejects missing names, fractional wells and impossible culture totals',()=>{const p=exampleTransfectionPlan();p.groups[0].wells='1.5';expect(()=>run(p)).toThrow();p.groups[0].wells='1';p.groups[0].finalVolume='10';expect(()=>run(p)).toThrow(/culture volume/);p.groups[0].finalVolume='1000';p.groups[0].rows[0].name='';expect(()=>run(p)).toThrow();});
});
