import {afterEach,describe,it,expect,vi} from 'vitest';
import {loadCalculatorState,saveCalculatorState,retryCalculatorStorage,getCalculatorRawBackup,createEmptyCalculatorState,addHistoryEntry,calculatorStorageKey} from './calculator-storage';
import {calculate} from './calculator-engine';
import {applyPipettingOptions} from './pipetting';
const old=JSON.stringify({version:1,favorites:['dilution'],history:[{id:'original',calculatorId:'dilution',inputs:{},outputs:[],warnings:[]}],presets:[]});
function memory(raw:string|null=old){const values=new Map<string,string>();if(raw!==null)values.set(calculatorStorageKey,raw);let readFail=false,backupFail=false,verifyFail=false;const storage={getItem:(key:string)=>{if(readFail)throw Error('read');return verifyFail&&key.includes('.backup.')?'conflict':values.get(key)??null;},setItem:(key:string,value:string)=>{if(backupFail&&key.includes('.backup.'))throw Error('quota');values.set(key,value);}};vi.stubGlobal('window',{localStorage:storage});return {values,storage,failRead:(v:boolean)=>readFail=v,failBackup:(v:boolean)=>backupFail=v,failVerify:(v:boolean)=>verifyFail=v};}
afterEach(()=>vi.unstubAllGlobals());
describe('SAFE-01 S01-S08',()=>{
 it('S01/S06 backup failure remains protected through remount; explicit recovery preserves history',()=>{const m=memory();m.failBackup(true);const empty=loadCalculatorState();m.failBackup(false);expect(saveCalculatorState(empty)).toBe(false);expect(saveCalculatorState(loadCalculatorState())).toBe(false);expect(m.values.get(calculatorStorageKey)).toBe(old);const recovered=retryCalculatorStorage();expect(recovered.history[0].id).toBe('original');const next=addHistoryEntry(recovered,{...recovered.history[0],id:'new'});expect(saveCalculatorState(next)).toBe(true);expect(JSON.parse(m.values.get(calculatorStorageKey)!).history.map((x:{id:string})=>x.id)).toEqual(['new','original']);});
 it('S02 first read failure cannot overwrite with empty state',()=>{const m=memory();m.failRead(true);const state=loadCalculatorState();m.failRead(false);expect(saveCalculatorState(state)).toBe(false);expect(m.values.get(calculatorStorageKey)).toBe(old);});
 it.each(['{bad',JSON.stringify({version:99,history:[],favorites:[],presets:[]})])('S03 protects invalid or future raw bytes %s',raw=>{const m=memory(raw);expect(saveCalculatorState(loadCalculatorState())).toBe(false);expect(getCalculatorRawBackup()).toBe(raw);expect(m.values.get(calculatorStorageKey)).toBe(raw);});
 it('S04 existing conflicting backup cannot authorize migration',()=>{const m=memory();m.failVerify(true);expect(saveCalculatorState(loadCalculatorState())).toBe(false);expect(m.values.get(calculatorStorageKey)).toBe(old);});
 it('S04 malformed migration structure retains verified original backup',()=>{const raw=JSON.stringify({version:1,history:'broken',favorites:[],presets:[]});const m=memory(raw);expect(saveCalculatorState(loadCalculatorState())).toBe(false);expect([...m.values.values()].filter(value=>value===raw)).toHaveLength(2);});
 it('S05 confirmed absent storage may save',()=>{const m=memory(null);expect(saveCalculatorState(loadCalculatorState())).toBe(true);expect(JSON.parse(m.values.get(calculatorStorageKey)!).history).toEqual([]);});
 it('S07 preference changes and pending drafts do not unlock history',()=>{const m=memory();m.failBackup(true);const state=loadCalculatorState();m.failBackup(false);m.storage.setItem('labnest.appearance', '{}');expect(saveCalculatorState({...state,drafts:{task:{inputs:{x:1},example:false,updatedAt:'now'}}})).toBe(false);expect(m.values.get(calculatorStorageKey)).toBe(old);});
 it('S08 stale state cannot overwrite another tab',()=>{const m=memory(null);const stale=loadCalculatorState();const external=JSON.stringify({...createEmptyCalculatorState(),favorites:['moi']});m.values.set(calculatorStorageKey,external);expect(saveCalculatorState(stale)).toBe(false);expect(m.values.get(calculatorStorageKey)).toBe(external);expect(retryCalculatorStorage().favorites).toEqual(['moi']);});
});
const wb={bufferContainsReducingAgent:'no',reducingAgentName:'Specified stock',reducingMode:'volume-fraction',targetProteinUg:20,finalLoadingVolumeUl:20,bufferFold:4,reducingAgentPercent:5,samples:[{id:'A',concentration:'2',available:''}]};
describe('WB-01 / PIP-01 independent arithmetic',()=>{
 it('V02 all four WB components sum to 20',()=>{const row=calculate({calculatorId:'wb-loading',inputs:wb}).table![0];expect(row).toMatchObject({sampleUl:10,bufferUl:5,reducingAgentUl:1,diluentUl:4,totalUl:20});});
 it('V03 included/zero/mixed-invalid rows',()=>{expect(calculate({calculatorId:'wb-loading',inputs:{...wb,bufferContainsReducingAgent:'yes'}}).table![0]).toMatchObject({reducingAgentUl:0,diluentUl:5});expect(calculate({calculatorId:'wb-loading',inputs:{...wb,reducingAgentPercent:0}}).table![0].reducingAgentUl).toBe(0);const result=calculate({calculatorId:'wb-loading',inputs:{...wb,samples:[...wb.samples,{id:'bad',concentration:'0.5',available:''}]}});expect(result.table![1]).toMatchObject({sampleUl:'',reducingAgentUl:'',totalUl:''});expect(result.table![0].sampleUl).toBe(10);});
 it('V04 mL action detects 0.1 µL, unchanged by input volume units',()=>{for(const [value,unit] of [[100,'µL'],[0.1,'mL'],[100000,'nL']] as const){const result=calculate({calculatorId:'seeding',inputs:{stockCellsPerMl:1e6,wells:1,cellsPerWell:100,volumePerWellUl:value,volumePerWellUlUnit:unit,overagePercent:0,pipetteMinimumUl:1}});expect(result.structuredWarnings).toHaveLength(1);expect(result.structuredWarnings![0].volumeUl).toBeCloseTo(0.1,12);expect(result.outputMap.mediumVolumeMl).toBeCloseTo(0.0999,12);}});
 it('V05 equality, zero and summary volumes are not low actions',()=>{const base={calculatorId:'dilution',methodVersion:'test',outputs:[{key:'stockVolume',label:'Stock',labelZh:'母液',value:1,unit:'µL'},{key:'diluentVolume',label:'Diluent',labelZh:'稀释液',value:0,unit:'µL'},{key:'remainingUl',label:'Remaining',labelZh:'剩余',value:0.1,unit:'µL'}],outputMap:{},warnings:[],notes:[]};expect(applyPipettingOptions(base,{pipetteMinimumUl:1}).warnings).toEqual([]);expect(()=>applyPipettingOptions({...base,outputs:[{...base.outputs[0],value:-1}]},{})).toThrow();});
 it('V05 nonzero rounded to zero is infeasible',()=>{expect(()=>calculate({calculatorId:'dilution',inputs:{mode:'final',stockConcentration:10,targetConcentration:1,finalVolume:2,pipetteStepUl:1}})).toThrow(/Rounding/);});
});
