"use client";
import {createContext,useContext,useEffect,useState,useRef,type ReactNode} from 'react';
import {appearanceDefaults,appearanceKey,parseAppearance,applyAppearance,type AppearancePreferences} from '@/lib/appearance';
import {systemThemeStorageKey} from '@/lib/system-theme';
import {uiScaleStorageKey} from '@/lib/ui-scale';
const Context=createContext({preferences:{...appearanceDefaults} as AppearancePreferences,warning:'',setAppearance:((_patch:Partial<AppearancePreferences>)=>{void _patch;}),reset:()=>{}});
export const useAppearance=()=>useContext(Context);
export function AppearanceProvider({children}:{children:ReactNode}){
 const [preferences,setPreferences]=useState<AppearancePreferences>({...appearanceDefaults});const [warning,setWarning]=useState('');const original=useRef<string|null>(null),protectedData=useRef(false),current=useRef(preferences);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: dark)');const load=()=>{try{const raw=localStorage.getItem(appearanceKey);const parsed=parseAppearance(raw,localStorage.getItem(systemThemeStorageKey),localStorage.getItem(uiScaleStorageKey),localStorage.getItem('labnest.calculators.v1')!==null||localStorage.getItem(systemThemeStorageKey)!==null||localStorage.getItem(uiScaleStorageKey)!==null);original.current=raw;protectedData.current=parsed.preserve;current.current=parsed.value;setPreferences(parsed.value);applyAppearance(parsed.value,document.documentElement,media.matches);setWarning(parsed.preserve?'旧或未知外观数据已保留；本次仅临时预览 / Unrecognized preferences retained; temporary preview.':'');if(raw===null){try{const json=JSON.stringify(parsed.value);localStorage.setItem(appearanceKey,json);original.current=json;}catch{setWarning('本次更改暂未保存 / Changes not saved');}}}catch{protectedData.current=true;setWarning('本次更改暂未保存 / Changes not saved');}};const frame=requestAnimationFrame(load);const system=()=>applyAppearance(current.current,document.documentElement,media.matches);const storage=(event:StorageEvent)=>{if([appearanceKey,systemThemeStorageKey,uiScaleStorageKey,null].includes(event.key))load();};media.addEventListener('change',system);window.addEventListener('storage',storage);return()=>{cancelAnimationFrame(frame);media.removeEventListener('change',system);window.removeEventListener('storage',storage);};},[]);
 function setAppearance(patch:Partial<AppearancePreferences>){const next=parseAppearance(JSON.stringify({...current.current,...patch}),null,null,false).value;current.current=next;setPreferences(next);applyAppearance(next,document.documentElement,matchMedia('(prefers-color-scheme: dark)').matches);try{if(protectedData.current||localStorage.getItem(appearanceKey)!==original.current){protectedData.current=true;throw Error('protected');}const json=JSON.stringify(next);localStorage.setItem(appearanceKey,json);if(localStorage.getItem(appearanceKey)!==json)throw Error('verification');original.current=json;setWarning('');}catch{setWarning('本次更改暂未保存；原偏好已保留 / Changes not saved; original preferences retained.');}}
 return <Context.Provider value={{preferences,warning,setAppearance,reset:()=>setAppearance({...appearanceDefaults})}}>{children}</Context.Provider>;
}
