"use client";
import {useAppearance} from './AppearanceProvider';
import {useI18n} from './I18nProvider';
import {SystemThemePicker} from './SystemThemePicker';
import {InterfaceScalePicker} from './InterfaceScalePicker';
import {TaskIcon} from './calculators/TaskIcon';
import {defaultTasks} from '@/lib/calculators/task-definitions';
import {AppearancePreview} from './AppearancePreview';
export function AppearanceSettings(){
 const {preferences,warning,setAppearance,reset}=useAppearance();const zh=useI18n().locale==='zh';
 return <section id="appearance"><p className="mb-4 text-sm text-muted">{zh?'在此设备生效。选择后即时应用。':'Applies on this device. Changes appear immediately.'}</p>{warning?<p role="status" className="appearance-warning">{warning}</p>:null}<div className="appearance-layout"><div className="appearance-controls">
 <fieldset><legend>{zh?'明暗模式':'Display mode'}</legend><div className="flex flex-wrap gap-4">{(['light','dark','system'] as const).map(mode=><label key={mode} className="flex min-h-11 items-center gap-2"><input type="radio" name="appearance-mode" checked={preferences.mode===mode} onChange={()=>setAppearance({mode})}/>{zh?{light:'浅色',dark:'深色',system:'跟随系统'}[mode]:mode}</label>)}</div></fieldset>
 <fieldset><legend>{zh?'配色':'Color scheme'}</legend><SystemThemePicker/></fieldset>
 <fieldset><legend>{zh?'图标套件':'Icon pack'}</legend><div className="grid gap-2">{(['classic-line','lab-soft'] as const).map(pack=><label key={pack} className="appearance-icon-option"><span className="flex min-h-11 items-center gap-2"><input type="radio" name="icon-pack" checked={preferences.iconPackId===pack} onChange={()=>setAppearance({iconPackId:pack})}/>{pack==='lab-soft'?(zh?'简洁实验图标':'Lab soft'):(zh?'经典线性':'Classic line')}{preferences.iconPackId===pack?' ✓':''}</span><span className="flex justify-between">{defaultTasks.map(id=><TaskIcon key={id} taskId={id} pack={pack} size={28}/>)}</span></label>)}</div><p className="mt-2 text-xs text-muted">{zh?'简洁套件覆盖全部31项计算；图片失效时使用对应线性图标。用于计算首页、Today 和工具标题。':'Lab soft covers all 31 calculations. Failed images use corresponding line icons. Used on calculator home, Today and tool titles.'}</p></fieldset>
 <fieldset><legend>{zh?'字体':'Fonts'}</legend><div className="grid gap-3 sm:grid-cols-2"><label>{zh?'界面字体':'Interface font'}<select aria-label="Interface font" value={preferences.uiFontId} onChange={e=>setAppearance({uiFontId:e.target.value as 'system-sans'|'system-serif'})}><option value="system-sans">{zh?'系统无衬线':'System sans-serif'}</option><option value="system-serif">{zh?'系统衬线 / 宋体':'System serif / Songti'}</option></select></label><label>{zh?'数据字体':'Data font'}<select aria-label="Data font" value={preferences.dataFontId} onChange={e=>setAppearance({dataFontId:e.target.value as 'system'|'mono'})}><option value="system">{zh?'系统默认':'System default'}</option><option value="mono">{zh?'等宽':'Monospace'}</option></select></label></div><p className="mt-2 text-xs text-muted">{zh?'使用设备字体，缺失时回退系统字体。正式文档字体在下方独立管理。':'Uses device fonts with system fallbacks. Formal document typography is managed separately below.'}</p></fieldset>
 <fieldset><legend>{zh?'文字大小':'Text size'}</legend><InterfaceScalePicker/></fieldset>
 <fieldset><legend>{zh?'内容间距':'Content spacing'}</legend><div className="flex flex-wrap gap-4">{(['compact','standard','comfortable'] as const).map(densityId=><label className="flex min-h-11 items-center gap-2" key={densityId}><input type="radio" name="content-spacing" value={densityId} checked={preferences.densityId===densityId} onChange={()=>setAppearance({densityId})}/>{zh?{compact:'紧凑',standard:'标准',comfortable:'宽松'}[densityId]:densityId}</label>)}</div><p className="text-xs text-muted">{zh?'调整卡片与内容间距，不缩小文字或触控区域。':'Adjusts cards and content spacing without shrinking text or touch targets.'}</p></fieldset>
 <button type="button" className="min-h-11 text-sm underline" onClick={reset}>{zh?'恢复默认外观':'Restore default appearance'}</button><p className="text-xs text-muted">{zh?'仅影响界面外观。科研图表配色、样本分组色及正式文档导出样式分别管理。':'Interface appearance only. Scientific chart palettes, sample-group colors and formal document exports are managed separately.'}</p>
 </div><AppearancePreview/></div></section>;
}
