'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export function ExperimentStepOrderEditor({experimentId,updatedAt,steps}:{experimentId:string;updatedAt:string;steps:{id:string;groupKey:string;title:string}[]}) {
 const router=useRouter();const [ordered,setOrdered]=useState(steps);const [pending,setPending]=useState(false);const [error,setError]=useState('');
 async function save(){setPending(true);setError('');try{const response=await fetch(`/api/experiments/${experimentId}/steps/order`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:ordered.map(step=>step.id),expectedUpdatedAt:updatedAt})});const result=await response.json();if(!response.ok)throw new Error(result.error);router.refresh();}catch(error){setError(error instanceof Error?error.message:'保存失败');}finally{setPending(false);}}
 const move=(index:number,direction:number)=>setOrdered(current=>{const next=[...current];[next[index],next[index+direction]]=[next[index+direction],next[index]];return next;});
 return <details className="rounded-[var(--ln-radius-panel)] border border-hairline p-3"><summary className="focus-ring cursor-pointer text-sm text-moss">调整未开始实验的步骤顺序</summary><p className="my-2 text-xs text-muted">仅调整同一规程内顺序，备注、附件和工具仍关联原步骤 ID。</p><ol className="space-y-2">{ordered.map((step,index)=><li key={step.id} className="flex min-w-0 items-center gap-2 text-sm"><span className="min-w-0 flex-1">{index+1}. {step.title}</span><button type="button" aria-label={`上移 ${step.title}`} disabled={pending||!index||ordered[index-1].groupKey!==step.groupKey} onClick={()=>move(index,-1)} className="focus-ring min-h-11 px-2 disabled:opacity-30">↑</button><button type="button" aria-label={`下移 ${step.title}`} disabled={pending||index===ordered.length-1||ordered[index+1].groupKey!==step.groupKey} onClick={()=>move(index,1)} className="focus-ring min-h-11 px-2 disabled:opacity-30">↓</button></li>)}</ol><button type="button" onClick={save} disabled={pending} className="focus-ring mt-2 min-h-11 rounded border border-hairline px-3 text-sm text-moss">保存步骤顺序</button>{error?<p role="alert" className="text-sm text-error">{error}</p>:null}</details>;
}
