import 'dotenv/config';import {prisma} from '../src/lib/db';import {writeFileSync} from 'node:fs';import {createScientificDocument,researchPlanSections,experimentSections,resultSections,reportSections} from '../src/lib/scientific-document';import {createEmptyProtocolDocument,protocolContentBlockSchema} from '../src/lib/protocol-document';import {buildEntryContent} from '../src/lib/entry-content';
if(new URL(process.env.DATABASE_URL!).pathname!=='/labnest_stage_a_acceptance')throw Error('Synthetic only');
async function main(){const stamp=Date.now();const project=await prisma.project.create({data:{name:`Synthetic image matrix ${stamp}`}});const cases=[];
for(const position of ['beginning','middle','end','only']){
 const lines=position==='only'?['插图位置']:position==='beginning'?['插图位置','前文保留','','后文保留']:position==='middle'?['前文保留','','插图位置','后文保留']:['前文保留','','后文保留','插图位置'];
 const blocks=lines.map((text,i)=>({id:`matrix-${i}`,type:'text' as const,text}));const doc=(sections:Parameters<typeof createScientificDocument>[0])=>{const d=createScientificDocument(sections);d.sections[0].blocks=blocks;return d;};
 const plan=await prisma.researchPlan.create({data:{projectId:project.id,code:`SYN-M-${stamp}-${position}`,title:`Synthetic matrix ${position}`,contentJson:doc(researchPlanSections)}});const exp=await prisma.experiment.create({data:{runCode:`SYN-M-${stamp}-${position}`,researchPlanId:plan.id,projectId:project.id,title:`Synthetic matrix ${position}`,contentJson:doc(experimentSections)}});const result=await prisma.result.create({data:{experimentId:exp.id,title:'Synthetic matrix',resultType:'Observation',contentJson:doc(resultSections)}});const report=await prisma.report.create({data:{projectId:project.id,title:'Synthetic matrix',contentJson:doc(reportSections)}});const entry=await prisma.entry.create({data:{title:'Synthetic matrix',body:lines.join('\n\n'),contentJson:buildEntryContent(lines.join('\n\n'),[])}});const protocol=await prisma.protocol.create({data:{humanCode:`SYN-M-${stamp}-${position}`,title:'Synthetic matrix'}});const pd=createEmptyProtocolDocument();pd.sections.find(s=>s.key==='steps')!.blocks=blocks.map(b=>protocolContentBlockSchema.parse(b));const version=await prisma.protocolVersion.create({data:{protocolId:protocol.id,revision:1,title:'Synthetic matrix',contentJson:pd}});
 for(const [name,edit] of [['research-plan',`/research-plans/${plan.id}/edit`],['experiment',`/experiments/${exp.id}/edit`],['result',`/results/${result.id}/edit`],['report',`/reports/${report.id}/edit`],['protocol',`/protocols/${protocol.id}/versions/${version.id}/edit`],['entry',`/entries/${entry.id}/edit`]])cases.push({name,edit,position});
}writeFileSync('docs/debug-20260909/evidence/image-matrix-fixtures.json',JSON.stringify({synthetic:true,cases},null,2));}
main().finally(()=>prisma.$disconnect());
