import assert from "node:assert/strict";
import {readFileSync,writeFileSync} from "node:fs";
import {randomUUID} from "node:crypto";
import {prisma} from "../src/lib/db";
import {assignEntry,freezeEntrySources,getEntrySources} from "../src/lib/entry-assignment.server";
import {lockEntrySourceGraph} from "../src/lib/entry-source-lock";
import {createEntryWithFiles,updateEntryWithFiles} from "../src/lib/entry-persistence";
import {parseEntryMutationFormData} from "../src/lib/entry-mutations";
assert.equal(new URL(process.env.DATABASE_URL!).pathname,"/labnest_entry_richtext_test_20261006");
const f=JSON.parse(readFileSync("docs/qa/evidence/entry-richtext/fixtures.json","utf8")),report:{checks:unknown[];synthetic:boolean}={checks:[],synthetic:true};
const input=(body:string,extra:Record<string,string>={})=>{const form=new FormData();Object.entries({title:"测试关系与时间",contentMarkdown:body,eventTimePrecision:"unknown",...extra}).forEach(([k,v])=>form.set(k,v));return parseEntryMutationFormData(form);};
async function check(name:string,fn:()=>Promise<void>){try{await fn();report.checks.push({name,status:"通过"});}catch(e){report.checks.push({name,status:"失败",error:String(e)});throw e;}finally{writeFileSync("docs/qa/evidence/entry-richtext/relations.json",JSON.stringify(report,null,2));}}
async function main(){const {id}=await createEntryWithFiles(input("测试原始正文",{clientMutationId:randomUUID()}),[]);const before=await prisma.entry.findUniqueOrThrow({where:{id}});let target:string;
 await check("A03/A08 new experiment atomic replay and conflict",async()=>{const request={mutationId:randomUUID(),type:"experiment" as const,expectedTarget:null,newTitle:"测试新归属实验"};const r=await Promise.all([assignEntry(id,request),assignEntry(id,request)]);assert.equal(r.filter(x=>x.replay).length,1);const links=await prisma.itemLink.findMany({where:{sourceType:"entry",sourceId:id,linkType:"entry_primary"}});assert.equal(links.length,1);target=links[0].targetId;assert.equal(await prisma.experiment.count({where:{id:target}}),1);assert((await prisma.experiment.findUniqueOrThrow({where:{id:target}})).createdAt>=before.createdAt);await assert.rejects(assignEntry(id,{...request,newTitle:"不同名称"}),/内容不同/);});
 await check("A07 reassign and unfile preserve content and first timestamp",async()=>{await assignEntry(id,{mutationId:randomUUID(),type:"none",expectedTarget:`experiment:${target}`});const after=await prisma.entry.findUniqueOrThrow({where:{id}});assert.equal(after.createdAt.toISOString(),before.createdAt.toISOString());assert.deepEqual(after.contentJson,before.contentJson);assert.equal(after.occurredAt.toISOString(),before.occurredAt.toISOString());});
 await check("A04/A05 result parent validation and rollback",async()=>{const count=await prisma.result.count();await assert.rejects(assignEntry(id,{mutationId:randomUUID(),type:"result",expectedTarget:null,targetId:f.resultId,experimentId:target!}),/不属于/);assert.equal(await prisma.result.count(),count);await assignEntry(id,{mutationId:randomUUID(),type:"result",expectedTarget:null,newTitle:"测试新归入结果",experimentId:f.experimentId});const link=await prisma.itemLink.findFirstOrThrow({where:{sourceType:"entry",sourceId:id,linkType:"entry_primary"}});target=link.targetId;assert.equal((await prisma.result.findUniqueOrThrow({where:{id:target}})).experimentId,f.experimentId);assert.equal((await prisma.result.findUniqueOrThrow({where:{id:target}})).qualityStatus,"not_assessed");});
 await check("A11 mutable source and frozen source are separate versions",async()=>{await updateEntryWithFiles(id,input("测试已更新同源",{expectedUpdatedAt:(await prisma.entry.findUniqueOrThrow({where:{id}})).updatedAt.toISOString()}),[],[],[]);assert.equal((await getEntrySources("result",target!,false)).sources[0].markdown,"测试已更新同源");await prisma.$transaction(async tx=>{await lockEntrySourceGraph(tx);await freezeEntrySources(tx,"result",target!);await tx.result.update({where:{id:target},data:{recordStatus:"reviewed"}});});await updateEntryWithFiles(id,input("测试审核后更新",{expectedUpdatedAt:(await prisma.entry.findUniqueOrThrow({where:{id}})).updatedAt.toISOString()}),[],[],[]);assert.equal((await getEntrySources("result",target!,true)).sources[0].markdown,"测试已更新同源");await assert.rejects(assignEntry(id,{mutationId:randomUUID(),type:"none",expectedTarget:`result:${target}`}),/冻结/);});
 await check("A08 competing requests cannot create two primary links",async()=>{const e=await createEntryWithFiles(input("测试并发记录"),[]);const rs=await Promise.allSettled([assignEntry(e.id,{mutationId:randomUUID(),type:"experiment",expectedTarget:null,targetId:f.experimentId}),assignEntry(e.id,{mutationId:randomUUID(),type:"experiment",expectedTarget:null,newTitle:"测试竞争新建"})]);assert.equal(rs.filter(x=>x.status==="fulfilled").length,1);assert.equal(await prisma.itemLink.count({where:{sourceType:"entry",sourceId:e.id,linkType:"entry_primary"}}),1);});
 await check("C03/C05 mutation identity and stale save protection",async()=>{const op=randomUUID(),fields=input("测试幂等保存",{clientMutationId:op});const first=await createEntryWithFiles(fields,[]),second=await createEntryWithFiles(fields,[]);assert.equal(first.id,second.id);await assert.rejects(createEntryWithFiles(input("不同正文",{clientMutationId:op}),[]),/内容发生变化/);const current=await prisma.entry.findUniqueOrThrow({where:{id:first.id}});const updated=input("测试首次更新",{clientMutationId:randomUUID(),expectedUpdatedAt:current.updatedAt.toISOString()});await updateEntryWithFiles(first.id,updated,[],[],[]);await updateEntryWithFiles(first.id,updated,[],[],[]);await assert.rejects(updateEntryWithFiles(first.id,input("测试过期覆盖",{expectedUpdatedAt:current.updatedAt.toISOString()}),[],[],[]),/另一窗口/);});
 await check("Run context creates one primary source and rejects a frozen parent",async()=>{const e=await createEntryWithFiles(input("测试 Run 来源",{experimentId:f.experimentId}),[]);assert.equal(await prisma.itemLink.count({where:{sourceType:"entry",sourceId:e.id,linkType:"entry_primary",targetType:"experiment",targetId:f.experimentId}}),1);assert((await getEntrySources("experiment",f.experimentId,false)).sources.some(s=>s.id===e.id));const exp=await prisma.experiment.create({data:{title:"测试冻结 Run",runCode:"TEST-FROZEN-"+Date.now(),recordStatus:"submitted"}});await assert.rejects(createEntryWithFiles(input("不可新增",{experimentId:exp.id}),[]),/read-only/);assert.equal(await prisma.entry.count({where:{experimentId:exp.id}}),0);});
 await check("A09/A10 date-only legacy precision survives editing",async()=>{const old=await prisma.entry.create({data:{title:"测试仅日期旧记录",body:"测试旧正文",createdAt:new Date("2026-10-01T01:15:00Z"),occurredAt:new Date("2026-09-30"),eventTimePrecision:"date"}});await updateEntryWithFiles(old.id,input("测试仅日期编辑",{eventTimePrecision:"date",occurredAt:"2026-09-30"}),[],[],[]);const after=await prisma.entry.findUniqueOrThrow({where:{id:old.id}});assert.equal(after.eventTimePrecision,"date");assert.equal(after.occurredAt.toISOString(),"2026-09-30T00:00:00.000Z");assert.equal(after.createdAt.toISOString(),"2026-10-01T01:15:00.000Z");});
}
main().finally(()=>prisma.$disconnect());
