import 'dotenv/config';import {prisma} from '../src/lib/db';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
if(new URL(process.env.DATABASE_URL!).pathname!=='/labnest_stage_a_acceptance')throw Error('Synthetic only');
async function main(){
const stamp=Date.now();const project=await prisma.project.create({data:{name:`Synthetic historical Run ${stamp}`}});const planName='合成历史研究方案'+ '长名称'.repeat(20);const plan=await prisma.researchPlan.create({data:{projectId:project.id,code:`SYN-H-${stamp}`,title:planName}});const versions=[];
for(let i=0;i<3;i++){const title=`合成历史规程${i+1}`+'方法名称'.repeat(12);const protocol=await prisma.protocol.create({data:{humanCode:`SYN-H-${stamp}-${i}`,title,canonicalTitle:title}});const version=await prisma.protocolVersion.create({data:{protocolId:protocol.id,revision:1,displayVersion:'1.0',title,reviewStage:'reviewed'}});versions.push({protocol,version});}
const exp=await prisma.experiment.create({data:{runCode:`SYN-H-${stamp}`,title:'Synthetic historical Run',projectId:project.id,researchPlanId:plan.id,primaryProtocolVersionId:versions[0].version.id,status:'running',protocolSnapshotJson:{methodMode:'protocol',researchPlanTitle:planName,versions:versions.map(v=>({protocolVersionId:v.version.id,protocolTitle:v.protocol.title,displayVersion:'1.0'}))},protocolVersions:{create:versions.map((v,i)=>({protocolVersionId:v.version.id,order:i}))},contentJson:{schemaVersion:1,sections:[{key:'execution',title:'执行记录',blocks:[{id:'handwritten',type:'text',text:'手写内容始终保留'}]}]}}});
await prisma.protocolRun.create({data:{experimentId:exp.id,protocolVersionId:versions[0].version.id,parametersJson:{sample_count:2,actual_temperature_c:37}}});
await prisma.experimentStep.createMany({data:['正常取样','偏差培养','异常处理','未执行检测'].map((title,i)=>({experimentId:exp.id,groupKey:'g'+Math.min(i,2),groupOrder:Math.min(i,2),groupTitle:'规程组'+Math.min(i+1,3),order:i+1,title,description:'完整原始操作不应默认展开',allowsDeviation:true}))});
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844}});const base='http://localhost:3232';
try{
await page.goto(`${base}/experiments/${exp.id}/run`,{waitUntil:'networkidle'});
for(const [index,type,note] of [[0,'',''],[1,'timing','实际延长5分钟'],[2,'incident','设备停机；已更换设备后继续']] as const){
 if(index){await page.getByText('Record a deviation',{exact:true}).click();await page.locator('select[name^=mobileDeviationType]').selectOption(type);await page.locator('textarea[name^="mobileDeviation:"]').fill(note);}
 await page.getByRole('button',{name:'Confirm step completion',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('button[disabled][name=completedCurrentStepId]'));await page.reload({waitUntil:'networkidle'});
}
const steps=await prisma.experimentStep.findMany({where:{experimentId:exp.id},orderBy:{order:'asc'}});assert.deepEqual(steps.map(s=>s.completed),[true,true,true,false]);assert.equal(steps[2].deviationType,'incident');assert.equal(steps[2].deviationNote,'设备停机；已更换设备后继续');
await prisma.protocolVersion.create({data:{protocolId:versions[0].protocol.id,revision:2,displayVersion:'2.0',title:'新版方法',reviewStage:'reviewed'}});await prisma.protocol.update({where:{id:versions[0].protocol.id},data:{title:'新名称不应覆盖历史',canonicalTitle:'新名称不应覆盖历史'}});
for(const suffix of ['', '/edit']){await page.goto(`${base}/experiments/${exp.id}${suffix}`,{waitUntil:'networkidle'});const paper=page.locator('.document-a4-paper');const text=await paper.innerText();for(const expected of ['手写内容始终保留','✓ 正常取样','偏差：实际延长5分钟','异常：设备停机；已更换设备后继续','未完成 未执行检测','本次执行参数（实验级记录','actual_temperature_c','37'])assert.ok(text.includes(expected),expected);assert.ok(!text.includes('新名称不应覆盖历史'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`docs/debug-20260909/evidence/history-${suffix?'edit':'view'}-mobile.png`,fullPage:true});}
await page.goto(`${base}/experiments/${exp.id}`);await page.pdf({path:'docs/debug-20260909/evidence/history-run.pdf',preferCSSPageSize:true,printBackground:true});const printed=execFileSync('pdftotext',['docs/debug-20260909/evidence/history-run.pdf','-'],{encoding:'utf8'}).replace(/\s/g,'');for(const v of versions)assert.ok(printed.includes(v.protocol.title.replace(/\s/g,'')),v.protocol.title);assert.ok(printed.includes('异常：设备停机；已更换设备后继续'));
writeFileSync('docs/debug-20260909/evidence/run-history.json',JSON.stringify({synthetic:true,experimentId:exp.id,versionCreation:'New reviewed version and rename via synthetic DB setup; publication UI not exercised',checks:['Three steps completed through actual mobile Run form, fourth left incomplete','DB readback retains actual deviation and incident handling text','Edit/read/print retain handwritten body, step order and experiment-level actual parameters','New reviewed version and rename do not overwrite frozen original names/version','All three long method names retained in PDF; 390px has no horizontal overflow']},null,2));
}finally{await browser.close();await prisma.$disconnect();}}
main().catch(e=>{console.error(e);process.exitCode=1});
