"use client";
import {useState} from 'react';
import type {CalculatorState} from '@/lib/calculators/calculator-storage';
import {TaskIcon} from './TaskIcon';
import {TaskLink,TaskHelp} from './TaskHelp';
import {taskPresentation} from '@/lib/calculators/task-presentation';
export function CommonTasks({pins,state,update,zh,contextQuery=""}:{contextQuery?:string;pins:string[];state:CalculatorState|null;update:(state:CalculatorState)=>void;zh:boolean}){
 const [editing,setEditing]=useState(false);
 return <section data-testid="common-tasks"><div className="flex min-h-11 items-center gap-3"><h2 className="mr-auto text-sm font-semibold">{zh?'常用任务':'Pinned tasks'}</h2><TaskHelp ids={pins.slice(0,6)} zh={zh}/><button className="min-h-11 text-xs text-moss" type="button" onClick={()=>setEditing(!editing)}>{editing?(zh?'完成':'Done'):(zh?'编辑':'Edit')}</button></div><div className="common-task-grid">{pins.slice(0,6).map(id=><TaskLink contextQuery={contextQuery} id={id} zh={zh} key={id} className="common-task-tile focus-ring"><TaskIcon taskId={id}/><span>{taskPresentation(id,zh).name}</span></TaskLink>)}</div>{!pins.length?<p className="text-xs">{zh?'尚未固定任务，可在全部工具中添加。':'No pinned tasks. Add from all tools.'}</p>:null}{pins.length>6?<details><summary className="min-h-11 text-sm">{zh?'全部收藏':'All favorites'} ({pins.length})</summary><div className="common-task-grid">{pins.slice(6).map(id=><TaskLink contextQuery={contextQuery} id={id} zh={zh} key={id} className="common-task-tile"><TaskIcon taskId={id}/><span>{taskPresentation(id,zh).name}</span></TaskLink>)}</div></details>:null}{editing&&state?<div className="rounded border border-hairline p-2 text-xs"><p>{zh?'前六项显示于首页；从下方全部工具固定或移除。':'First six appear here. Pin additional tasks from all tools below.'}</p>{pins.map((id,index)=><div key={id} className="flex items-center gap-2"><span className="mr-auto">{taskPresentation(id,zh).name}</span><button className="min-h-11" disabled={index===0} onClick={()=>{const next=[...pins];[next[index-1],next[index]]=[next[index],next[index-1]];update({...state,favoritesConfigured:true,favorites:next});}}>{zh?'前移':'Move earlier'}</button><button className="min-h-11" onClick={()=>update({...state,favoritesConfigured:true,favorites:pins.filter(key=>key!==id)})}>{zh?'移除':'Remove'}</button></div>)}</div>:null}</section>;
}
