"use client";
import {useEffect,useState} from 'react';
import {prepareOffline,clearOfflineTools,offlineStatus,OfflineError} from '@/lib/calculators/offline';
export function OfflineCalculator({zh,panel=false}:{zh:boolean;panel?:boolean}) {
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[prepared,setPrepared]=useState(false),[failed,setFailed]=useState(false);
 const ready=(pages:string[]=[])=>zh?`可离线打开：${pages.join('、')}。缓存可能被浏览器回收。`:`Available offline: ${pages.join(', ')}. The browser may reclaim caches.`;
 useEffect(()=>{let active=true;offlineStatus().then(r=>{if(active&&r.ok&&r.pages?.length){setStatus(ready(r.pages));setPrepared(true);}}).catch(()=>{});return()=>{active=false;};},[zh]); // eslint-disable-line react-hooks/exhaustive-deps
 async function prepare(){setBusy(true);try{const result=await prepareOffline(stage=>setStatus(stage==='documents'?(zh?'检查主页与当前页面…':'Checking home and current page…'):(zh?'准备脚本、样式和图标…':'Preparing scripts, styles and icons…')));setStatus(ready(result.pages));setPrepared(true);setFailed(false);}catch(error){setFailed(true);const kind=error instanceof OfflineError?error.kind:'resource';const labels={environment:['此环境不支持离线页面。请使用受信任HTTPS或本机地址；输入草稿独立保存。','Offline pages require trusted HTTPS or localhost. Input drafts are saved separately.'],registration:['离线服务注册/作用域失败，请重试并检查站点配置。','Worker registration/scope failed. Retry and check site configuration.'],resource:['必要页面或资源加载失败。保持联网后重试，原有可用缓存保留。','A required page or resource failed. Retry online; previous cache is retained.'],quota:['缓存空间不足，请清除工具缓存后重试。历史和草稿不会清除。','Cache storage is full. Clear tool caches and retry; history and drafts are retained.'],timeout:['准备超时，请检查连接并重试。','Preparation timed out. Check the connection and retry.']};setStatus(labels[kind][zh?0:1]);console.info('Calculator offline diagnostic',{kind,detail:String(error),secure:window.isSecureContext,protocol:location.protocol});}finally{setBusy(false);}}
 const content=<><p>{zh?'缓存计算器主页和当前页面。':'Cache calculator home and the current page.'}</p><div className="flex flex-wrap gap-3"><button disabled={busy} type="button" className="min-h-11 text-moss" onClick={prepare}>{busy?(zh?'正在准备…':'Preparing…'):failed?(zh?'重试':'Retry'):prepared?(zh?'更新离线内容':'Update offline content'):(zh?'准备离线使用':'Prepare offline')}</button><button disabled={busy} type="button" className="min-h-11 text-moss" onClick={async()=>{setBusy(true);try{await clearOfflineTools();setPrepared(false);setFailed(false);setStatus(zh?'离线缓存已清除；草稿、预设、历史和同步队列保留。':'Offline caches cleared; drafts, presets, history and sync queue retained.');}catch{setStatus(zh?'清除失败，请重试清除。':'Could not clear caches; retry clearing.');}finally{setBusy(false);}}}>{zh?'清除离线缓存':'Clear offline caches'}</button></div><p role="status" aria-live="polite">{status||(zh?'尚未确认可离线页面。':'No offline pages confirmed yet.')}</p></>;
 return panel?<div className="calculator-offline text-sm">{content}</div>:<details className="calculator-offline text-xs text-muted"><summary className="min-h-11 cursor-pointer">{zh?'离线使用':'Offline use'}</summary>{content}</details>;
}
