"use client";
import {TransfectionResult} from './TransfectionResult';
import {LiquidOperations} from "./LiquidOperations";
import type {CalculatorResult} from '@/lib/calculators/calculator-engine';
import {compatibleUnits} from '@/lib/calculators/quantities';
import {presentedOutputs,presentedTable,formatQuantity,tableUnitsFor} from '@/lib/calculators/result-presentation';
import {tableColumnLabel} from '@/lib/calculators/presentation';
import {ResultExport} from './ResultExport';
import {FitPlot} from './FitPlot';
export function ResultPanel({result,zh,onSave,disabled,onApplyToPlate,onUnit}:{result:CalculatorResult;zh:boolean;onSave:()=>void;disabled:boolean;onApplyToPlate?:()=>void;onUnit?:(key:string,unit:string)=>void}){
 const picker=(key:string,unit:string,label:string)=>compatibleUnits(unit).length>1&&onUnit?<select aria-label={`${label} ${zh?'显示单位':'display unit'}`} className="min-h-11 max-w-28 rounded border border-hairline bg-transparent px-1 text-xs" value={result.displayUnits?.[key]??unit} onChange={e=>onUnit(key,e.target.value)}>{compatibleUnits(unit).map(value=><option key={value}>{value}</option>)}</select>:<span className="text-xs">{unit}</span>;
 const table=presentedTable(result,zh);
 return <div className="min-w-0 space-y-3"><p className="text-xs">{result.status==='estimate'?(zh?'估算：核对方法与条件':'Estimate: review method and conditions'):result.status==='partial'?(zh?'部分样本无效，请查看状态':'Some samples invalid; review status'):(zh?'条件成立':'Valid conditions')}</p><p role="status" className="text-sm">{({passed:'通过所设移液下限检查 / Passed configured minimum check','below-minimum':'存在低于所设移液下限的步骤 / Steps below configured minimum','not-set':'未设置移液下限 / Minimum not set',incomplete:'未完成移液检查（含定容目标或无可量化操作） / Pipetting check incomplete', 'not-applicable':'移液检查不适用 / No pipetting operation'} as const)[result.pipettingCheck?.status??'incomplete']}</p>{result.operations?(result.methodVersion==='transfection-v3'?<details><summary className="min-h-11 text-xs">{zh?'操作明细':'Operation details'}</summary><LiquidOperations operations={result.operations}/></details>:<LiquidOperations operations={result.operations}/>):<p>旧快照未记录操作 / Legacy snapshot did not record operations</p>}<ResultExport result={result} zh={zh}/><FitPlot result={result}/><dl className="divide-y divide-hairline">{presentedOutputs(result).map(output=><div key={output.key} className="flex items-center justify-between gap-2 py-1"><dt className="text-xs">{zh?output.labelZh:output.label}</dt><dd className="flex items-center gap-1 font-mono text-sm"><span>{typeof output.value==='number'?formatQuantity(output.value):output.value}</span>{output.unit?picker(output.key,result.outputs.find(o=>o.key===output.key)!.unit!,zh?output.labelZh:output.label):null}</dd></div>)}</dl>{table.length?<><div className="flex flex-wrap gap-2">{Object.keys(result.table![0]).filter(key=>tableUnitsFor(result)[key]).map(key=><label key={key} className="text-xs">{tableColumnLabel(key,zh)} {picker('table:'+key,tableUnitsFor(result)[key],tableColumnLabel(key,zh))}</label>)}</div>{result.methodVersion==='transfection-v3'?<TransfectionResult result={result} zh={zh}/>:<div className="max-h-72 overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{Object.keys(table[0]).map(key=><th key={key} className="whitespace-nowrap p-2">{key}</th>)}</tr></thead><tbody>{table.map((row,index)=><tr key={index} className="border-t border-hairline">{Object.values(row).map((value,column)=><td key={column} className="p-2 font-mono">{typeof value==='number'?formatQuantity(value):value}</td>)}</tr>)}</tbody></table></div>}</>:null}{result.warnings.map(w=><p key={w} className="rounded bg-warning-surface p-3 text-xs text-warning">{w}</p>)}{result.notes.map(note=><p key={note} className="text-xs text-muted">{note}</p>)}{onApplyToPlate?<button type="button" className="min-h-11 w-full rounded bg-moss text-warm" onClick={onApplyToPlate}>{zh?'写回所选孔位':'Send to selected wells'}</button>:null}<button type="button" className="min-h-11 w-full rounded border border-moss text-moss disabled:opacity-40" disabled={disabled} onClick={onSave}>{zh?'保存到本机历史':'Save to local history'}</button></div>;
}
