"use client";
import {compatibleUnits,convert,parseScalar} from "@/lib/calculators/quantities";
import type { MixRow, SampleRow } from '@/lib/calculators/planning';
const control='min-h-11 w-full min-w-0 rounded-lg border border-hairline bg-surface px-2 text-sm';
export function MixEditor({rows,onChange,zh}:{rows:MixRow[];onChange:(rows:MixRow[])=>void;zh:boolean}) {
  return <fieldset className="min-w-0 space-y-2"><legend>{zh?'组分（每反应µL）':'Components (µL per reaction)'}</legend>{rows.map((row,index)=><div key={index} className="rounded border border-hairline p-2"><div className="grid grid-cols-[minmax(0,1fr)_70px_70px_44px] items-center gap-1"><input aria-label={zh?'组分名称':'Component name'} className={control} value={row.name} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,name:e.target.value}:r))}/><input aria-label={zh?'每反应体积':'Volume per reaction'} className={control} value={row.volume} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,volume:e.target.value}:r))}/><label className="text-xs"><input type="checkbox" checked={row.premix} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,premix:e.target.checked}:r))}/>{zh?'预混':'Premix'}</label><button type="button" className="min-h-11" onClick={()=>onChange(rows.filter((_,i)=>i!==index))} aria-label={zh?'移除组分':'Remove component'}>×</button></div><details className="text-xs"><summary className="min-h-11 cursor-pointer">{zh?'用母液/目标浓度计算用量':'Calculate volume from stock / target concentration'}</summary><label><input type="checkbox" checked={row.inputMode==='concentration'} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,inputMode:e.target.checked?'concentration':'volume'}:r))}/>{zh?'按浓度计算（忽略固定体积）':'Use concentrations (ignore fixed volume)'}</label>{row.inputMode==='concentration'?<div className="grid grid-cols-2 gap-2">{(['stock','target'] as const).map(key=><div key={key} className="grid min-w-0 grid-cols-[minmax(0,1fr)_64px] gap-1"><input aria-label={key==='stock'?'Stock concentration':'Target concentration'} className={control} value={row[key]??''} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[key]:e.target.value}:r))}/><select aria-label={`${key} unit`} className={control} value={row[`${key}Unit`]??(key==='stock'?'mM':'µM')} disabled={Boolean(row[key]?.trim())&&!Number.isFinite(Number(row[key]))} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[key]:row[key]?.trim()?String(convert(parseScalar(row[key]),row[`${key}Unit`]??(key==='stock'?'mM':'µM'),e.target.value)):'',[`${key}Unit`]:e.target.value}:r))}>{compatibleUnits('M').map(unit=><option key={unit}>{unit}</option>)}</select></div>)}</div>:null}</details></div>)}<button type="button" className="min-h-11 text-sm text-moss" onClick={()=>onChange([...rows,{name:'',volume:'',premix:true}])}>{zh?'＋添加组分':'＋ Add component'}</button><p className="text-xs text-muted">{zh?'样本模板取消勾选预混；水自动补足至单反应体积。':'Uncheck premix for sample-specific template; water fills the remaining volume.'}</p></fieldset>;
}
export function SampleEditor({rows,onChange,zh,unit}:{rows:SampleRow[];onChange:(rows:SampleRow[])=>void;zh:boolean;unit:string}) {
  return <fieldset className="space-y-2"><legend>{zh?`样本（浓度 ${unit}，可用体积µL）`:`Samples (concentration ${unit}, available µL)`}</legend><textarea aria-label={zh?'粘贴样本表':'Paste samples'} className={control} placeholder={zh?'粘贴Excel：ID、浓度、可用体积（可选）；Tab分列，无标题':'Paste Excel: ID, concentration, available volume (optional); tab separated, no header'} onChange={e=>onChange(e.target.value.split(/\r?\n/).filter(line=>line.trim()).map(line=>{const cells=line.split(/\t|,/);return{id:cells[0]??'',concentration:cells[1]??'',available:cells[2]??''};}))}/>{rows.map((row,index)=><div key={index} className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_44px] gap-1">{(['id','concentration','available'] as const).map(key=><input key={key} aria-label={`${key} ${index+1}`} className={control} value={row[key]} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[key]:e.target.value}:r))}/>)}<button className="min-h-11" type="button" aria-label="Remove sample" onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" className="min-h-11 text-moss" onClick={()=>onChange([...rows,{id:'',concentration:'',available:''}])}>{zh?'＋添加样本':'＋ Add sample'}</button></fieldset>;
}
export type RecipeRow={name:string;amount:string;unit:string;inputMode?:string;stock?:string;target?:string;stockUnit?:string;targetUnit?:string};
export function RecipeEditor({rows,onChange,zh}:{rows:RecipeRow[];onChange:(rows:RecipeRow[])=>void;zh:boolean}) {
 const update=(index:number,patch:Partial<RecipeRow>)=>onChange(rows.map((row,i)=>i===index?{...row,...patch}:row));
 return <fieldset className="space-y-2"><legend>{zh?'结构化配方组分':'Structured recipe components'}</legend>{rows.map((row,index)=><div key={index} className="space-y-2 rounded-lg border border-hairline p-2"><div className="grid grid-cols-[minmax(0,1fr)_44px] gap-1"><input aria-label="Component name" className={control} value={row.name} onChange={e=>update(index,{name:e.target.value})}/><button className="min-h-11" type="button" onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>×</button></div><select className={control} aria-label="Component input mode" value={row.inputMode??'amount'} onChange={e=>update(index,{inputMode:e.target.value})}><option value="amount">{zh?'按基准体积的称量/原液用量':'Mass or stock volume at recipe base volume'}</option><option value="concentration">{zh?'母液→最终目标浓度':'Stock → final target concentration'}</option></select>{row.inputMode==='concentration'?<div className="grid grid-cols-2 gap-2">{(['stock','target'] as const).map(key=><label key={key} className="min-w-0 text-xs">{key==='stock'?(zh?'母液浓度':'Stock concentration'):(zh?'目标浓度':'Target concentration')}<span className="grid grid-cols-[minmax(0,1fr)_64px] gap-1"><input className={control} value={row[key]??''} onChange={e=>update(index,{[key]:e.target.value})}/><select className={control} disabled={Boolean(row[key]?.trim())&&!Number.isFinite(Number(row[key]))} value={row[`${key}Unit`]??(key==='stock'?'mM':'µM')} onChange={e=>update(index,{[key]:row[key]?.trim()?String(convert(parseScalar(row[key]),row[`${key}Unit`]??(key==='stock'?'mM':'µM'),e.target.value)):'',[`${key}Unit`]:e.target.value})}>{compatibleUnits('M').map(unit=><option key={unit}>{unit}</option>)}</select></span></label>)}</div>:<div className="grid max-w-[18rem] grid-cols-[minmax(0,1fr)_64px] gap-1.5"><input aria-label="Amount at base volume" className={control} value={row.amount} onChange={e=>update(index,{amount:e.target.value})}/><select aria-label="Component unit" className={control} value={row.unit} disabled={Boolean(row.amount.trim())&&!Number.isFinite(Number(row.amount))} onChange={e=>update(index,{amount:row.amount.trim()?String(convert(parseScalar(row.amount),row.unit,e.target.value)):'',unit:e.target.value})}>{['g','mg','µg','mL','µL','L'].map(unit=><option key={unit} disabled={Boolean(row.amount.trim())&&!compatibleUnits(row.unit).includes(unit)}>{unit}</option>)}</select></div>}</div>)}<button className="min-h-11 text-moss" type="button" onClick={()=>onChange([...rows,{name:'',amount:'',unit:'mL'}])}>{zh?'＋添加组分':'＋ Add component'}</button></fieldset>;
}
export type ReactionGroup={name:string;reactions:string;rows:MixRow[]};
export function ReactionGroups({groups,onChange,zh}:{groups:ReactionGroup[];onChange:(groups:ReactionGroup[])=>void;zh:boolean}) {
 return <div className="space-y-3">{groups.map((group,index)=><fieldset key={index} className="min-w-0 space-y-2 rounded-lg border border-hairline p-3"><legend>{zh?'独立配液组':'Separate mix group'} {index+1}</legend><input className={control} aria-label="Group name" value={group.name} placeholder="Group name" onChange={e=>onChange(groups.map((g,i)=>i===index?{...g,name:e.target.value}:g))}/><label className="text-xs">{zh?'本组实际反应数（已含重复和对照）':'Actual reactions in this group (including repeats and controls)'}<input className={control} value={group.reactions} onChange={e=>onChange(groups.map((g,i)=>i===index?{...g,reactions:e.target.value}:g))}/></label><MixEditor zh={zh} rows={group.rows} onChange={rows=>onChange(groups.map((g,i)=>i===index?{...g,rows}:g))}/><button type="button" className="min-h-11 text-sm" onClick={()=>onChange(groups.filter((_,i)=>i!==index))}>{zh?'移除此组':'Remove group'}</button></fieldset>)}<button className="min-h-11 text-moss" type="button" onClick={()=>onChange([...groups,{name:'',reactions:'',rows:[]}])}>{zh?'＋添加独立配液组':'＋ Add separate mix group'}</button></div>;
}
export function CurveEditor({value,onChange,zh}:{value:string;onChange:(value:string)=>void;zh:boolean}) {
 const rows=value?value.split(/\r?\n/).map(line=>line.split(/,|\t/)):[];
 const update=(next:string[][])=>onChange(next.map(row=>row.join('\t')).join('\n'));
 return <fieldset className="space-y-2"><legend className="text-sm">{zh?'浓度与反应值（保留重复点）':'Concentration and response (replicates retained)'}</legend>{rows.map((row,index)=><div key={index} className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_44px] gap-2">{[0,1].map(column=><input key={column} aria-label={`${column===0?'Concentration':'Response'} row ${index+1}`} className={control} value={row[column]??''} onChange={e=>update(rows.map((r,i)=>i===index?[column===0?e.target.value:r[0]??'',column===1?e.target.value:r[1]??'']:r))}/>)}<button type="button" className="min-h-11" onClick={()=>update(rows.filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" className="min-h-11 text-moss" onClick={()=>update([...rows,['','']])}>{zh?'＋添加点':'＋ Add point'}</button><details><summary className="min-h-11 cursor-pointer text-xs">{zh?'粘贴数据':'Paste data'}</summary><textarea aria-label="Paste concentration and response" className={control} value={value} onChange={e=>onChange(e.target.value)}/></details></fieldset>;
}
