"use client";
import {useState,useRef} from 'react';
import {compatibleUnits,convert,parseScalar} from '@/lib/calculators/quantities';
import type {MixRow,SampleRow} from '@/lib/calculators/planning';
const control='min-h-11 w-full min-w-0 rounded border border-hairline bg-surface px-2 text-sm';
function Remove({onClick,zh}:{onClick:()=>void;zh:boolean}) {return <button type="button" aria-label={zh?'移除此行':'Remove row'} onClick={onClick}>×</button>;}
function confirmRemove(filled:boolean,zh:boolean,remove:()=>void) {if(!filled||window.confirm(zh?'移除此行？':'Remove this row?'))remove();}
type Concentrations={stock?:string;target?:string;stockUnit?:string;targetUnit?:string};
function ConcentrationFields({row,onChange,zh}:{row:Concentrations;onChange:(patch:Concentrations)=>void;zh:boolean}) {
 return <div className="grid grid-cols-2 gap-2">{(['stock','target'] as const).map(key=><label key={key} className="text-xs">{key==='stock'?(zh?'母液浓度':'Stock concentration'):(zh?'目标浓度':'Target concentration')}<span className="flex gap-1"><input className={control} value={row[key]??''} onChange={e=>onChange({[key]:e.target.value})}/><select aria-label={`${key} unit`} className={control} value={row[`${key}Unit`]??(key==='stock'?'mM':'µM')} disabled={Boolean(row[key]?.trim())&&!Number.isFinite(Number(row[key]))} onChange={e=>onChange({[key]:row[key]?.trim()?String(convert(parseScalar(row[key]),row[`${key}Unit`]??(key==='stock'?'mM':'µM'),e.target.value)):'',[`${key}Unit`]:e.target.value})}>{compatibleUnits('M').map(unit=><option key={unit}>{unit}</option>)}</select></span></label>)}</div>;
}
export function MixEditor({rows,onChange,zh}:{rows:MixRow[];onChange:(rows:MixRow[])=>void;zh:boolean}) {
 const root=useRef<HTMLFieldSetElement>(null);
 const update=(index:number,patch:Partial<MixRow>)=>onChange(rows.map((r,i)=>i===index?{...r,...patch}:r));
 return <fieldset ref={root} className="min-w-0 calculator-row-stack"><legend>{zh?'组分':'Components'}</legend><div className="calculator-data-scroll"><table><thead><tr>{(zh?['组分名称','依据','每反应 µL','预混','操作']:['Component','Basis','Per reaction µL','Premix','Actions']).map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><MixInputRow key={index} row={row} zh={zh} update={patch=>update(index,patch)} remove={()=>confirmRemove(Boolean(row.name||row.volume),zh,()=>onChange(rows.filter((_,i)=>i!==index)))}/>)}</tbody></table></div><button type="button" className="text-moss" onClick={()=>{onChange([...rows,{name:'',volume:'',premix:true}]);requestAnimationFrame(()=>root.current?.querySelectorAll<HTMLInputElement>('input[data-component-name]').item(rows.length)?.focus());}}>{zh?'添加组分':'Add component'}</button><p className="text-xs text-muted">{zh?'未勾选预混的组分须单独加入；水补足至单反应体积。':'Unchecked components are added separately; water fills the reaction volume.'}</p></fieldset>;
}
function MixInputRow({row,update,remove,zh}:{row:MixRow;update:(patch:Partial<MixRow>)=>void;remove:()=>void;zh:boolean}) {
 return <><tr><td><input data-component-name aria-label={zh?'组分名称':'Component name'} className={control} value={row.name} onChange={e=>update({name:e.target.value})}/></td><td><select aria-label={zh?'计算依据':'Calculation basis'} className={control} value={row.inputMode??'volume'} onChange={e=>update({inputMode:e.target.value as MixRow['inputMode']})}><option value="volume">{zh?'体积':'Volume'}</option><option value="concentration">{zh?'浓度':'Concentration'}</option></select></td><td>{row.inputMode!=='concentration'?<input aria-label={zh?'每反应体积':'Volume per reaction'} className={control} value={row.volume} onChange={e=>update({volume:e.target.value})}/>:<span>{zh?'按浓度':'Calculated'}</span>}</td><td><input aria-label={zh?'加入预混':'Include in premix'} type="checkbox" checked={row.premix} onChange={e=>update({premix:e.target.checked})}/></td><td><Remove zh={zh} onClick={remove}/></td></tr>{row.inputMode==='concentration'?<tr><td colSpan={5}><ConcentrationFields row={row} zh={zh} onChange={update}/></td></tr>:null}</>;
}
function PasteRows({zh,label,columns,onApply}:{zh:boolean;label:string;columns:number;onApply:(text:string)=>void}) {
 const [draft,setDraft]=useState(''),[error,setError]=useState('');
 return <details><summary>{label}</summary><label className="block text-xs">{zh?'按表头顺序粘贴，无标题行':'Paste in column order, without headers'}<textarea className={control} value={draft} onChange={e=>{setDraft(e.target.value);setError('');}}/></label>{error?<p role="alert" className="text-error">{error}</p>:null}<button type="button" onClick={()=>{const lines=draft.split(/\r?\n/).filter(l=>l.trim());const bad=lines.findIndex(l=>{const cells=l.split(/\t|,/);return cells.length<2||cells.length>columns;});if(bad>=0){setError(zh?`第${bad+1}行列数不正确，请修正。`:`Incorrect column count on row ${bad+1}.`);return;}onApply(lines.join('\n'));setError('');}}>{zh?'应用数据':'Apply data'}</button></details>;
}
export function SampleEditor({rows,onChange,zh,unit}:{rows:SampleRow[];onChange:(rows:SampleRow[])=>void;zh:boolean;unit:string}) {
 const root=useRef<HTMLFieldSetElement>(null);
 return <fieldset ref={root} className="min-w-0 calculator-row-stack"><legend>{zh?'样品':'Samples'}</legend><PasteRows zh={zh} label={zh?'粘贴样本表':'Paste samples'} columns={3} onApply={text=>onChange(text.split(/\r?\n/).filter(line=>line.trim()).map(line=>{const cells=line.split(/\t|,/);return{id:cells[0]??'',concentration:cells[1]??'',available:cells[2]??''};}))}/><div className="calculator-data-scroll"><table><thead><tr><th>{zh?'样品':'Sample'}</th><th>{zh?'浓度':'Concentration'} {unit}</th><th>{zh?'可用量':'Available'} µL</th><th>{zh?'操作':'Actions'}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{(['id','concentration','available'] as const).map(key=><td key={key}><input data-sample-field={key} aria-label={`${key} ${index+1}`} className={control} value={row[key]} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[key]:e.target.value}:r))}/></td>)}<td><Remove zh={zh} onClick={()=>confirmRemove(Boolean(row.id||row.concentration),zh,()=>onChange(rows.filter((_,i)=>i!==index)))}/></td></tr>)}</tbody></table></div><button type="button" className="text-moss" onClick={()=>{onChange([...rows,{id:'',concentration:'',available:''}]);requestAnimationFrame(()=>root.current?.querySelectorAll<HTMLInputElement>('[data-sample-field="id"]').item(rows.length)?.focus());}}>{zh?'添加样本':'Add sample'}</button></fieldset>;
}
export type RecipeRow={name:string;amount:string;unit:string;inputMode?:string;stock?:string;target?:string;stockUnit?:string;targetUnit?:string};
export function RecipeEditor({rows,onChange,zh}:{rows:RecipeRow[];onChange:(rows:RecipeRow[])=>void;zh:boolean}) {
 const update=(index:number,patch:Partial<RecipeRow>)=>onChange(rows.map((row,i)=>i===index?{...row,...patch}:row));
 return <fieldset className="min-w-0 calculator-row-stack"><legend>{zh?'配方组分':'Recipe components'}</legend>{rows.map((row,index)=><div key={index} className="border-t border-hairline py-2"><div className="grid grid-cols-2 gap-2"><label>{zh?'名称':'Name'}<input className={control} value={row.name} onChange={e=>update(index,{name:e.target.value})}/></label><label>{zh?'依据':'Basis'}<select className={control} value={row.inputMode??'amount'} onChange={e=>update(index,{inputMode:e.target.value})}><option value="amount">{zh?'基准体积用量':'Amount at base volume'}</option><option value="concentration">{zh?'母液与目标浓度':'Stock / target concentration'}</option></select></label>{row.inputMode==='concentration'?<div className="col-span-2"><ConcentrationFields row={row} zh={zh} onChange={patch=>update(index,patch)}/></div>:<label>{zh?'用量':'Amount'}<span className="flex gap-1"><input className={control} value={row.amount} onChange={e=>update(index,{amount:e.target.value})}/><select aria-label={zh?'组分单位':'Component unit'} className={control} value={row.unit} disabled={Boolean(row.amount.trim())&&!Number.isFinite(Number(row.amount))} onChange={e=>update(index,{amount:row.amount.trim()?String(convert(parseScalar(row.amount),row.unit,e.target.value)):'',unit:e.target.value})}>{['g','mg','µg','mL','µL','L'].map(unit=><option key={unit} disabled={Boolean(row.amount.trim())&&!compatibleUnits(row.unit).includes(unit)}>{unit}</option>)}</select></span></label>}<Remove zh={zh} onClick={()=>confirmRemove(Boolean(row.name||row.amount),zh,()=>onChange(rows.filter((_,i)=>i!==index)))}/></div></div>)}<button className="text-moss" type="button" onClick={()=>onChange([...rows,{name:'',amount:'',unit:'mL'}])}>{zh?'添加组分':'Add component'}</button></fieldset>;
}
export type ReactionGroup={name:string;reactions:string;rows:MixRow[]};
export function ReactionGroups({groups,onChange,zh}:{groups:ReactionGroup[];onChange:(groups:ReactionGroup[])=>void;zh:boolean}) {
 const [active,setActive]=useState(0);const index=Math.min(active,Math.max(0,groups.length-1)),group=groups[index];
 return <div className="calculator-row-stack"><nav className="calculator-group-tabs" aria-label={zh?'配液组':'Mix groups'}>{groups.map((g,i)=><button type="button" key={i} aria-pressed={i===index} onClick={()=>setActive(i)}>{g.name||`${zh?'组':'Group'} ${i+1}`}</button>)}</nav>{group?<fieldset className="min-w-0"><div className="grid grid-cols-2 gap-2"><label>{zh?'组名':'Group name'}<input className={control} aria-label="Group name" value={group.name} onChange={e=>onChange(groups.map((g,i)=>i===index?{...g,name:e.target.value}:g))}/></label><label>{zh?'实际反应数（含重复及对照）':'Actual reactions (incl. repeats and controls)'}<input className={control} value={group.reactions} onChange={e=>onChange(groups.map((g,i)=>i===index?{...g,reactions:e.target.value}:g))}/></label></div><MixEditor zh={zh} rows={group.rows} onChange={rows=>onChange(groups.map((g,i)=>i===index?{...g,rows}:g))}/><button type="button" onClick={()=>confirmRemove(true,zh,()=>onChange(groups.filter((_,i)=>i!==index)))}>{zh?'移除此组':'Remove group'}</button></fieldset>:null}<button className="text-moss" type="button" onClick={()=>{onChange([...groups,{name:'',reactions:'',rows:[]}]);setActive(groups.length);}}>{zh?'添加独立配液组':'Add separate mix group'}</button></div>;
}
export function CurveEditor({value,onChange,zh,columns=2}:{value:string;onChange:(value:string)=>void;zh:boolean;columns?:number}) {
 const root=useRef<HTMLFieldSetElement>(null);const rows=value?value.split(/\r?\n/).map(line=>line.split(/,|\t/)):[];
 const update=(next:string[][])=>onChange(next.map(row=>row.join('\t')).join('\n'));
 return <fieldset ref={root} className="min-w-0 calculator-row-stack"><legend>{columns===3?(zh?'稀释系列':'Dilution series'):(zh?'标准点（保留重复测量）':'Standards (replicates retained)')}</legend><div className="calculator-data-scroll"><table><thead><tr><th>{columns===3?(zh?'稀释度':'Dilution'):(zh?'浓度':'Concentration')}</th><th>{columns===3?(zh?'阳性孔':'Positive wells'):(zh?'反应值':'Response')}</th>{columns===3?<th>{zh?'总孔数':'Total wells'}</th>:null}<th>{zh?'操作':'Actions'}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{Array.from({length:columns},(_,i)=>i).map(column=><td key={column}><input data-curve-column={column} aria-label={`${column===0?'Concentration':'Response'} row ${index+1}`} className={control} value={row[column]??''} onChange={e=>update(rows.map((r,i)=>i===index?Array.from({length:columns},(_,c)=>c===column?e.target.value:r[c]??''):r))}/></td>)}<td><Remove zh={zh} onClick={()=>confirmRemove(row.some(Boolean),zh,()=>update(rows.filter((_,i)=>i!==index)))}/></td></tr>)}</tbody></table></div><button type="button" className="text-moss" onClick={()=>{update([...rows,Array(columns).fill('')]);requestAnimationFrame(()=>root.current?.querySelectorAll<HTMLInputElement>('[data-curve-column="0"]').item(rows.length)?.focus());}}>{zh?'添加点':'Add point'}</button><PasteRows zh={zh} label={zh?'粘贴数据':'Paste data'} columns={columns} onApply={onChange}/></fieldset>;
}
