"use client";
import {CalculatorLinkProgress} from "./CalculatorLinkProgress";
import {useEffect,useLayoutEffect,useId,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import Link from 'next/link';
import {taskPresentation} from '@/lib/calculators/task-presentation';
export function TaskLink({id,zh,children,className,contextQuery=""}:{contextQuery?:string;id:string;zh:boolean;children:ReactNode;className?:string}){
 const tooltipRef=useRef<HTMLDivElement>(null);
 const tooltipId=useId(),ref=useRef<HTMLAnchorElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const [position,setPosition]=useState<{left:number;top:number}|null>(null);const meta=taskPresentation(id,zh);
 useLayoutEffect(()=>{if(!position||!tooltipRef.current)return;const r=tooltipRef.current.getBoundingClientRect();if(r.bottom>innerHeight-8)setPosition({...position,top:Math.max(8,innerHeight-r.height-8)});},[position]);
 const close=()=>{clearTimeout(timer.current);setPosition(null);};
 const open=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>{const r=ref.current?.getBoundingClientRect();if(r)setPosition({left:Math.max(8,Math.min(innerWidth-308,r.left)),top:Math.max(8,Math.min(innerHeight-160,r.bottom+6))});},300);};
 useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){clearTimeout(timer.current);setPosition(null);}};document.addEventListener('keydown',escape);return()=>{clearTimeout(timer.current);document.removeEventListener('keydown',escape);};},[]);
 const leave=()=>{clearTimeout(timer.current);timer.current=setTimeout(close,150);};
 return <><Link prefetch={false} onClick={event=>{if(!navigator.onLine){event.preventDefault();location.assign(`/tools/calculator/${id}${contextQuery?`?${contextQuery}`:""}`);}}} ref={ref} href={`/tools/calculator/${id}${contextQuery?`?${contextQuery}`:""}`} className={className} aria-describedby={position?tooltipId:undefined} onMouseEnter={()=>{if(matchMedia('(hover:hover)').matches)open();}} onMouseLeave={leave} onFocus={open} onBlur={close} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}}}>{children}<CalculatorLinkProgress/></Link>{position?createPortal(<div ref={tooltipRef} id={tooltipId} role="tooltip" className="fixed z-[100] max-w-[300px] max-h-[calc(100dvh-16px)] overflow-auto rounded border border-hairline bg-surface p-3 text-xs text-ink shadow-md" style={position} onMouseEnter={()=>clearTimeout(timer.current)} onMouseLeave={leave}><strong>{meta.fullName}</strong><p>{meta.description}</p><p className="mt-2">{meta.advice}</p></div>,document.body):null}</>;
}
export function TaskHelp({ids,zh,label}:{ids:string[];zh:boolean;label?:string}){const ref=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);return <><button ref={trigger} type="button" className="min-h-11 text-xs text-moss" onClick={()=>ref.current?.showModal()}>{label??(zh?'使用说明':'Help')}</button><dialog ref={ref} className="task-help-dialog fixed inset-x-0 bottom-0 top-auto m-0 max-h-[80vh] w-full max-w-none overflow-auto rounded-t-xl border border-hairline bg-surface p-4 text-ink sm:inset-0 sm:m-auto sm:max-w-lg" onKeyDown={event=>{if(event.key==='Tab'){const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex="0"]')??[]);const first=items[0],last=items.at(-1);if((event.shiftKey&&document.activeElement===first)||(!event.shiftKey&&document.activeElement===last)){event.preventDefault();(event.shiftKey?last:first)?.focus();}}}} onClose={()=>trigger.current?.focus()}><div className="flex items-center justify-between"><h2>{zh?'使用说明':'Task help'}</h2><button type="button" className="min-h-11 min-w-11" aria-label={zh?'关闭说明':'Close help'} onClick={()=>ref.current?.close()}>×</button></div>{ids.map(id=>{const meta=taskPresentation(id,zh);return <section key={id} className="border-t border-hairline py-3"><h3 className="font-semibold">{meta.fullName}</h3><p className="text-sm">{meta.description}</p><p className="text-sm text-muted">{meta.advice}</p></section>})}</dialog></>;}
