"use client";
import Link from 'next/link';
import {isTransfectionPlan,newTransfectionPlan,newTransfectionGroup,newNucleicRow,newDoseReagent,changeTransfectionMaterial,changeTransfectionMixing,transfectionProtocols,type TransfectionPlan,type TransfectionGroup,type NucleicRow,type DoseReagent,type Material,type TubeVolume} from '@/lib/calculators/transfection';
const control='min-h-11 w-full min-w-0 rounded border border-hairline bg-surface px-2 text-sm';
function Field({label,value,onChange,unit='',text=false}:{label:string;value:string;onChange:(s:string)=>void;unit?:string;text?:boolean}){return <label className="transfection-field"><span>{label}</span><div><input aria-label={label} className={control} inputMode={text?undefined:'decimal'} value={value} onChange={e=>onChange(e.target.value)}/>{unit?<span>{unit}</span>:null}</div></label>;}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(s:string)=>void}){return <label className="transfection-field"><span>{label}</span><select className={control} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;}
function Reagent({value,onChange,zh,allowDna,allowRna}:{value:DoseReagent;onChange:(r:DoseReagent)=>void;zh:boolean;allowDna:boolean;allowRna:boolean}){
 const t=(cn:string,en:string)=>zh?cn:en;return <div className="transfection-row"><Field text label={t('试剂名称','Reagent name')} value={value.name} onChange={name=>onChange({...value,name})}/><Select label={t('用量依据','Dose basis')} value={value.basis} options={[['direct',t('直接填写每孔体积','Volume per well')],...(allowDna?[['dna',t('每µg总DNA','Per µg total DNA')]]:[]),...(allowRna?[['sirna',t('每pmol总siRNA','Per pmol total siRNA')]]:[]),['custom',t('自定义方案依据','Custom protocol basis')]]} onChange={basis=>onChange({...value,basis:basis as DoseReagent['basis'],amount:'',basisAmount:'',basisName:'',basisUnit:''})}/><Field label={t('试剂用量','Reagent amount')} unit={value.basis==='direct'?'µL/孔':value.basis==='dna'?'µL/µg':value.basis==='sirna'?'µL/pmol':`µL/${value.basisUnit||t('依据单位','basis unit')}`} value={value.amount} onChange={amount=>onChange({...value,amount})}/>{value.basis==='custom'?<><Field text label={t('适用对象/依据','Applicable object / basis')} value={value.basisName} onChange={basisName=>onChange({...value,basisName})}/><Field text label={t('依据单位','Basis unit')} value={value.basisUnit} onChange={basisUnit=>onChange({...value,basisUnit})}/><Field label={t('每孔依据量','Basis quantity per well')} unit={value.basisUnit} value={value.basisAmount} onChange={basisAmount=>onChange({...value,basisAmount})}/></>:null}</div>;
}
function Volume({value,onChange,zh,label}:{value:TubeVolume;onChange:(v:TubeVolume)=>void;zh:boolean;label:string}){return <div className="transfection-volume"><Select label={label} value={value.mode} options={[[ 'add',zh?'加入稀释液':'Add diluent'],['final',zh?'用稀释液补足至总体积':'Bring to total volume with diluent']]} onChange={mode=>onChange({mode:mode as TubeVolume['mode'],value:''})}/><Field label={value.mode==='add'?(zh?'稀释液加入量 / 孔':'Diluent added per well'):(zh?'配好后总体积 / 孔':'Prepared total per well')} value={value.value} unit="µL" onChange={v=>onChange({...value,value:v})}/></div>;}
export function TransfectionEditor({plan,onChange,zh}:{plan?:TransfectionPlan;onChange:(plan:TransfectionPlan)=>void;zh:boolean}){
 const t=(cn:string,en:string)=>zh?cn:en;if(!isTransfectionPlan(plan))return <section><p>{t('当前为旧版DNA输入；旧记录保留原有计算。请新建明确材料和体积定义的方案。','Legacy DNA inputs retain their original calculation. Start a new plan to specify material and volumes.')}</p><button type="button" className="min-h-11 text-moss" onClick={()=>onChange(newTransfectionPlan())}>{t('新建转染方案','New transfection plan')}</button></section>;
 const update=(index:number,g:TransfectionGroup)=>onChange({...plan,groups:plan.groups.map((item,i)=>i===index?g:item)});const hasDna=!['sirna','multi-sirna'].includes(plan.material),hasRna=['sirna','multi-sirna','dna-sirna'].includes(plan.material);const profile=transfectionProtocols[plan.protocol];
 return <section className="transfection-editor space-y-3"><div className="transfection-row"><Select label={t('转染内容','Transfection material')} value={plan.material} options={[[ 'dna',t('单个DNA质粒','Single DNA plasmid')],['multi-dna',t('多个DNA共转染','Multiple DNA plasmids')],['sirna',t('siRNA','siRNA')],['multi-sirna',t('多个siRNA混合','Multiple siRNAs')],['shrna-plasmid',t('shRNA表达质粒','shRNA expression plasmid')],['dna-sirna',t('DNA＋siRNA共转染','DNA + siRNA')]]} onChange={v=>onChange(changeTransfectionMaterial(plan,v as Material))}/><Select label={t('配制方式','Preparation mode')} value={plan.mixing} options={[[ 'two-tube',t('双管（核酸A＋试剂B）','Two tubes (nucleic acid A + reagent B)')],['single',t('单体系','Single mixture')]]} onChange={v=>onChange(changeTransfectionMixing(plan,v as TransfectionPlan['mixing']))}/></div>
 <p className="text-xs text-muted">{t('病毒载体转导使用MOI工具。切换材料或配制模式会清空不再适用的试剂/体积参数，须重新填写。','Use the MOI tool for viral transduction. Material or mode changes clear inapplicable reagent/volume values for re-entry.')} <Link className="text-moss" href="/tools/calculator/moi">MOI →</Link></p>
 <Select label={t('产品方案（独立于用量）','Product protocol (doses set separately)')} value={plan.protocol} options={[[ 'custom',t('自定义已验证方案','Custom validated protocol')],...Object.entries(transfectionProtocols).filter(([,p])=>p.materials.includes(plan.material)&&p.mixing===plan.mixing).map(([id,p])=>[id,p.name])]} onChange={protocol=>{const p=transfectionProtocols[protocol];onChange({...plan,protocol,groups:plan.groups.map(g=>({...g,reagent:{...newDoseReagent(),name:p?.reagent??''},auxiliaries:protocol.startsWith('l3000')&&hasDna?[{...newDoseReagent(),name:'P3000',basis:'dna',amount:'2'}]:[],a:{mode:'final',value:''},b:{mode:'final',value:''},single:{mode:'final',value:''},order:''}))});}}/>
 {profile?<p className="text-xs"><a href={profile.source} target="_blank" rel="noreferrer" className="text-moss">{t('查看具体说明书/方案','Read the specific product protocol')}</a> · {t('按说明填写用量，不自动套用其他材料或规格。','Enter doses from this protocol, without substituting other materials or formats.')}{!hasDna&&plan.protocol==='l3000'?t(' 纯siRNA不加P3000。',' No P3000 for siRNA only.'):null}</p>:null}
 {plan.groups.map((g,gi)=>{const rowChange=(ri:number,r:NucleicRow)=>update(gi,{...g,rows:g.rows.map((v,i)=>i===ri?r:v)});const nucleic=<><div className="transfection-row">{hasDna?<><Select label={t('DNA用量方式','DNA dosing')} value={g.dnaMode} options={[[ 'amount',t('逐个填写每孔质量','Mass per plasmid per well')],['mass-ratio',t('总质量＋质量比','Total mass + mass ratio')],['molar-ratio',t('总质量＋摩尔比','Total mass + molar ratio')]]} onChange={v=>update(gi,{...g,dnaMode:v as TransfectionGroup['dnaMode'],totalDna:'',rows:g.rows.map(r=>r.kind==='sirna'?r:{...r,dose:'',size:''})})}/>{g.dnaMode!=='amount'?<Field label={t('每孔总DNA质量','Total DNA mass per well')} unit="µg" value={g.totalDna} onChange={totalDna=>update(gi,{...g,totalDna})}/>:null}</>:null}{hasRna?<><Select label={t('siRNA用量含义','siRNA dose meaning')} value={g.rnaMode} options={[[ 'each-nm',t('每种终浓度','Each siRNA final concentration')],['each-pmol',t('每种每孔pmol','Each siRNA pmol per well')],['total-nm',t('混合物总终浓度＋比例','Mixture total concentration + ratios')],['total-pmol',t('混合物总pmol＋比例','Mixture total pmol + ratios')]]} onChange={v=>update(gi,{...g,rnaMode:v as TransfectionGroup['rnaMode'],totalRna:'',rows:g.rows.map(r=>r.kind==='sirna'?{...r,dose:''}:r)})}/>{g.rnaMode.startsWith('total')?<Field label={t('siRNA混合物总用量 / 孔','Total siRNA mixture dose per well')} unit={g.rnaMode.endsWith('nm')?'nM':'pmol'} value={g.totalRna} onChange={totalRna=>update(gi,{...g,totalRna})}/>:null}</>:null}</div>
 {g.rows.map((r,ri)=><fieldset className="transfection-nucleic" key={ri}><legend>{r.kind==='sirna'?'siRNA':r.kind==='shrna-plasmid'?t('shRNA表达质粒','shRNA expression plasmid'):'DNA'} {ri+1}</legend><div className="transfection-row"><Field text label={t('核酸名称','Nucleic acid name')} value={r.name} onChange={name=>rowChange(ri,{...r,name})}/><Field label={t('母液浓度','Stock concentration')} unit={r.stockUnit} value={r.stock} onChange={stock=>rowChange(ri,{...r,stock})}/><Select label={t('母液浓度单位','Stock concentration unit')} value={r.stockUnit} options={(r.kind==='sirna'?['µM','nM']:['µg/µL','ng/µL']).map(u=>[u,u])} onChange={stockUnit=>rowChange(ri,{...r,stockUnit,stock:''})}/><Field label={r.kind==='sirna'?(g.rnaMode.startsWith('total')?t('混合比例','Mixture ratio'):t('每孔siRNA用量','siRNA dose per well')):g.dnaMode==='amount'?t('每孔DNA质量','DNA mass per well'):t('质粒比例','Plasmid ratio')} unit={r.kind==='sirna'?(g.rnaMode.startsWith('total')?'':g.rnaMode.endsWith('nm')?'nM':'pmol'):g.dnaMode==='amount'?'µg':''} value={r.dose} onChange={dose=>rowChange(ri,{...r,dose})}/>{r.kind!=='sirna'&&g.dnaMode==='molar-ratio'?<><Select label={t('分子量依据','Molecular weight basis')} value={r.sizeBasis} options={[[ 'bp',t('dsDNA长度','dsDNA length')],['mw',t('实际分子量','Actual molecular weight')]]} onChange={v=>rowChange(ri,{...r,sizeBasis:v as NucleicRow['sizeBasis'],size:''})}/><Field label={t('长度或分子量','Length or molecular weight')} unit={r.sizeBasis==='bp'?'bp':'g/mol'} value={r.size} onChange={size=>rowChange(ri,{...r,size})}/></>:null}</div>{g.rows.length>1?<button type="button" className="min-h-11 text-xs" onClick={()=>update(gi,{...g,rows:g.rows.filter((_,i)=>i!==ri)})}>{t('移除此核酸','Remove nucleic acid')}</button>:null}</fieldset>)}
 {['multi-dna','multi-sirna','dna-sirna'].includes(plan.material)?<div className="flex flex-wrap gap-3">{(hasDna?['dna']:[]).concat(hasRna?['sirna']:[]).map(kind=><button type="button" key={kind} className="min-h-11 text-moss text-sm" onClick={()=>update(gi,{...g,rows:[...g.rows,newNucleicRow(kind as NucleicRow['kind'])]})}>+ {kind==='dna'?'DNA':'siRNA'}</button>)}</div>:null}
 {g.auxiliaries.map((r,ri)=><fieldset key={ri}><legend>{t('辅助试剂','Auxiliary reagent')} {ri+1}</legend><Reagent value={r} zh={zh} allowDna={hasDna} allowRna={hasRna} onChange={r=>update(gi,{...g,auxiliaries:g.auxiliaries.map((a,i)=>i===ri?r:a)})}/><button type="button" className="min-h-11 text-xs" onClick={()=>update(gi,{...g,auxiliaries:g.auxiliaries.filter((_,i)=>i!==ri)})}>{t('移除辅助试剂','Remove auxiliary')}</button></fieldset>)}<button type="button" className="min-h-11 text-moss text-sm" onClick={()=>update(gi,{...g,auxiliaries:[...g.auxiliaries,newDoseReagent()]})}>+ {t('辅助试剂','Auxiliary reagent')}</button></>;
 return <fieldset className="transfection-group" key={gi}><legend>{t('独立实验组','Independent group')} {gi+1}</legend><div className="transfection-row"><Field text label={t('实验组名称','Group name')} value={g.name} onChange={name=>update(gi,{...g,name})}/><Field label={t('实际孔数（含重复）','Actual wells (including replicates)')} value={g.wells} onChange={wells=>update(gi,{...g,wells})}/><Field label={t('整批配制余量','Batch overage')} unit="%" value={g.overage} onChange={overage=>update(gi,{...g,overage})}/><Field label={t('每孔最终培养体积（含混合液）','Final culture volume per well (including mixture)')} unit="µL" value={g.finalVolume} onChange={finalVolume=>update(gi,{...g,finalVolume})}/><Field text label={t('稀释液名称','Diluent name')} value={g.diluent} onChange={diluent=>update(gi,{...g,diluent})}/></div>
 <div className={plan.mixing==='two-tube'?'transfection-tubes':'transfection-single'}><section><h3>{plan.mixing==='two-tube'?t('核酸管（A）','Nucleic acid tube (A)'):t('单体系组分','Single mixture components')}</h3>{nucleic}{plan.mixing==='single'?<Reagent value={g.reagent} zh={zh} allowDna={hasDna} allowRna={hasRna} onChange={reagent=>update(gi,{...g,reagent})}/>:null}<Volume label={plan.mixing==='two-tube'?t('A管体积定义','Tube A volume definition'):t('单体系体积定义','Single mixture volume definition')} value={plan.mixing==='two-tube'?g.a:g.single} zh={zh} onChange={value=>update(gi,plan.mixing==='two-tube'?{...g,a:value}:{...g,single:value})}/></section>{plan.mixing==='two-tube'?<section><h3>{t('转染试剂管（B）','Transfection reagent tube (B)')}</h3><Reagent value={g.reagent} zh={zh} allowDna={hasDna} allowRna={hasRna} onChange={reagent=>update(gi,{...g,reagent})}/><Volume label={t('B管体积定义','Tube B volume definition')} value={g.b} zh={zh} onChange={b=>update(gi,{...g,b})}/></section>:null}</div>
 {profile?<p className="text-xs leading-5">{profile.order}</p>:<Field text label={t('加样顺序（按自定义方案）','Addition order (custom protocol)')} value={g.order} onChange={order=>update(gi,{...g,order})}/>}{plan.groups.length>1?<button type="button" className="min-h-11 text-sm" onClick={()=>onChange({...plan,groups:plan.groups.filter((_,i)=>i!==gi)})}>{t('移除此实验组','Remove group')}</button>:null}</fieldset>;})}
 <button type="button" className="min-h-11 text-moss" onClick={()=>{const fresh=changeTransfectionMaterial({...newTransfectionPlan(),groups:[newTransfectionGroup()]},plan.material).groups[0];onChange({...plan,groups:[...plan.groups,{...fresh,reagent:{...fresh.reagent,name:profile?.reagent??''},auxiliaries:plan.protocol.startsWith('l3000')&&hasDna?[{...newDoseReagent(),name:'P3000',basis:'dna',amount:'2'}]:[]}]});}}>+ {t('独立实验组（不混管）','Independent group (separate preparation)')}</button>
 </section>;
}
